### ISSUE TITLE
Spring Boot Actuator does not serve several JVM Prometheus metrics in native image

### ISSUE THREAD

**Issue by psinghal04** [spring-projects-experimental/spring-native#1006]
**Description**
When building and deploying a Spring Boot app as a native image using Spring Native, the Actuator's Prometheus endpoint does not serve several JVM metrics that are available via the same endpoint when the app is run in non-native mode.

**Steps to Reproduce**
1. git clone https://github.com/spring-guides/gs-rest-service
cd gs-rest-service/complete
2. Make the following changes: 
  * Add the following dependencies to pom.xml:
  ```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
```
* Add application.properties with the following properies:
```
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,prometheus
```

3. First, run the app in non-native mode ```mvn spring-boot:run```. Access http://localhost:8080/actuator/prometheus and review the metrics.

4. Modify the app for native mode per Spring Native "Getting Started" directions. Build and run the app in native mode. Access http://localhost:8080/actuator/prometheus and review the metrics.

**Expected Result**
Actuator Prometheus endpoint serves identical metrics in standard and native builds.
[prometheus_expected.txt](https://github.com/spring-projects-experimental/spring-native/files/7073533/prometheus_expected.txt)
 
**Actual Result**
Several JVM metrics are missing from the  Actuator Prometheus endpoint response when built as deployed as native image using Spring Native.
[prometheus_actual.txt](https://github.com/spring-projects-experimental/spring-native/files/7073535/prometheus_actual.txt)

**Context**
Spring Boot version: 2.5.4
Spring Native version: 0.10.3

**Comment by psinghal04** [comment]
Perhaps this is due to the fact that the underlying SubstrateVM within GraalVM does not publish the JMX MBeans that Micrometer relies on to publish these metrics via the Prometheus endpoint. See https://github.com/micrometer-metrics/micrometer/issues/2637

**Comment by sdeleuze** [comment]
@shakuzen Could you please help qualify this one to understand if that's already covered by the issues we discussed around Tomcat?

**Comment by shakuzen** [comment]
It's separate from the missing Tomcat metrics. As mentioned in the linked issue and shared with the GraalVM team in [this document](https://docs.google.com/document/d/1ueXQx8okRQZWXBwUI921I9m1GZQCgwVhMCc37jaW_BA/edit#), GC and memory metrics are not available due to unimplemented methods/MBeans in SubstrateVM. I have not heard from the GraalVM team on if the things missing will be addressed.

**Comment by xlf12** [comment]
Having the Prometheus metrics up and running for a Service is an expected behavior. We use/rely in all our K8s platforms on this for the observability ... well, IMHO I expect many to expect this too.

**Comment by shakuzen** [comment]
Process/system CPU usage will be back in GraalVM 22.2 - see https://github.com/micrometer-metrics/micrometer/issues/3121#issuecomment-1111948795. If you would like to see that fix available sooner, you should reach out to the GraalVM team about backporting it to a patch release.

As for memory and GC metrics, see my previous comment. You can track the related issues in GraalVM via https://github.com/oracle/graal/issues/4510 and https://github.com/oracle/graal/issues/1039. I don't think there's any change to make in Spring Native or Micrometer at this point. Things need to change in GraalVM to support this. I'm sure they would be happy to receive a contribution.
