### ISSUE TITLE
Docker native compilation gets stuck while registering reflection metadata

### ISSUE THREAD

**Issue by ivangfr** [spring-projects-experimental/spring-native#1008]
Hi, I've updated recently this project [`spring-cloud-stream-event-sourcing-testcontainers`](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers) to **spring-boot** `2.5.4` and **spring-native** `0.10.3`.

Somehow, I am not able to build **anymore** the Docker native image of `user-service` and `event-service`. The compilation process gets stuck while registering reflection metadata [See screenshot in Issues Section](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers#issues).

Maybe, it's a problem with my computer. Can somebody else try it out? Thanks!

How to reproduce

- git clone https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers.git
- cd spring-cloud-stream-event-sourcing-testcontainers
- ./docker-build.sh native

**Comment by ttddyy** [comment]
@ivangfr Hi, it worked for me.

```
[INFO]
[INFO] Successfully built image 'docker.io/ivanfranchin/event-service:1.0.0'
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:02 min
[INFO] Finished at: 2021-08-31T11:09:11-07:00
[INFO] ------------------------------------------------------------------------
```

I used `graalvm-ce 21.2.0` on osx.

You might need to assign more resources to docker: 
https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-buildpacks-system-requirements

I have assigned 6 CPU and 9G memory.

Here is the output: [output.txt](https://github.com/spring-projects-experimental/spring-native/files/7086190/output.txt)

**Comment by ivangfr** [comment]
Hey @ttddyy Thanks for trying it out, I really appreciate.

I've realised that, in your `output.txt`, it took almost 40 min to build `event-service`.

I was not waiting too much, maximum 20 min. By waiting a bit more, the images were built successfully.

Thanks!
