### ISSUE TITLE
Unable to start ServletWebServerApplicationContext in muti-module project

### ISSUE THREAD

**Issue by arielcarrera** [spring-projects-experimental/spring-native#1009]
After some tries to buid and run a simple multi-module project that works with Spring Boot, it fails during runtime with:

> 14:28:30.437 [main] ERROR org.springframework.boot.SpringApplication - Application run failed org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.Appli cationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean

Reproducer:
[sample project](https://github.com/arielcarrera/spring-native-multimodule)

things I've tried:
- change the starter dependency to PROVIDED in core module and add the dependency to main module
- change the starter class from core module to main module extending an abstract class
- add indexer and configuration plugin to core module:
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
			<optional>true</optional>
		</dependency>
```
- if I copy all classes in same module and comment the core dependency it works
```
<!-- 		<dependency> -->
<!-- 			<groupId>com.github.arielcarrera.spring-native</groupId> -->
<!-- 			<artifactId>spring-native-multimodule-core</artifactId> -->
<!-- 		</dependency> -->
```

**Comment by mhalbritter** [comment]
This works now with Spring native 0.12.0 - tested the sample, but had to remove log4j2.
