### ISSUE TITLE
Add support for `spring-data-envers`

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects-experimental/spring-native#1016]
I'm unsuccessfully trying to extend `spring-data-jpa` sample to also use `spring-data-envers`.

It would be great to have a complete working sample with an `@Audited` `@Entity` associated with a `RevisionRepository` in an application with `@EnableEnversRepositories`.

**Comment by snicoll** [comment]
@ch4mpy please move that to Spring Data Envers as we're not going to act on this here. It's in a different org so I can't move the issue unfortunately. If you can attach a small sample with Spring Boot 3 that would be helpful.

**Comment by ch4mpy** [comment]
@snicoll https://github.com/spring-projects/spring-data-envers says

> This project is now part of [Spring Data JPA 3.0](https://github.com/spring-projects/spring-data-jpa).

So, should I open an issue for envers native support in `spring-data-jpa`?

Also, after this [blog post](https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5), I was expecting an almost ready starter project for the sample you request from https://start.spring.io, but I get an error message saying that boot versions >= 2.4.3 and < 3.0.0-M1 are supported only

**Comment by snicoll** [comment]
> So, should I open an issue for envers native support in spring-data-jpa?

Yes.

> Also, after this [blog post](https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5),

The blog post you've referenced mentions that the support is moving away from Spring Native to be included out-of-the-box. I suppose the "error message" you got was about adding Spring Native which is no longer necessary with Spring Boot 3.

**Comment by ch4mpy** [comment]
Will wait untill I can find some documentation about building native images with spring-boot 3 and maven. Things seem to have quite changed since I last did (when I opened those tickets which are blockers on my project) and I couldn't get JPA samples work (tried with 1.0.x and sb-3.0.x branches).
