### ISSUE TITLE
Bean definition extending FactoryBean with generics is not injected

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#1022]
This problem can be seen with the `hateoas` and `data-rest` samples currently.
They're both contributing `PluginRegistry<T,S>` beans through `PluginRegistryFactoryBean<T,S>` declared as bean definitions.

Samples fails with the following:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type 'org.springframework.plugin.core.PluginRegistry<org.springframework.hateoas.server.LinkRelationProvider, 
org.springframework.hateoas.server.LinkRelationProvider$LookupContext>' available:
expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

While debugging the issue, we've found that the current code generation process contributes that definition to the context with: 

```java
BeanDefinitionRegistrar.of("relProviderPluginRegistry", ResolvableType.forClassWithGenerics(PluginRegistryFactoryBean.class, LinkRelationProvider.class, LinkRelationProvider.LookupContext.class)).withFactoryMethod(HateoasConfiguration.class, "relProviderPluginRegistry")
            .instanceSupplier(() -> context.getBean(HateoasConfiguration.class).relProviderPluginRegistry()).register(context);
```

Declaring the `FactoryBean` type as the `ResolvableType` target type in the definition seems to confuse the core container in the `org.springframework.beans.factory.support.DefaultListableBeanFactory#doResolveDependency` and especially the `org.springframework.beans.factory.support.DefaultListableBeanFactory#findAutowireCandidates` sequence. Instead of considering the generic type of the bean produced by the `FactoryBean` and if it's assignable to the required type for the injection point, this seems to only consider the provided target type.

This might be linked with the fact that we're heavily using the `instanceSupplier` mechanism instead of factory methods.

We've validated that tweaking the targetType to represent the actual type produced by the `FactoryBean` fixes the issue, but this might not be in line with the expected API usage. This should be discussed in a Spring Framework issue (to be linked here).

**Comment by bclozel** [comment]
Blocked until spring-projects/spring-framework#27383 is triaged.

**Comment by snicoll** [comment]
Depending on the outcome and what Juergen recommends, we could write the target of the factory bean instead. This would hide the fact that the bean itself is using a `FactoryBean` behind the scenes.

**Comment by snicoll** [comment]
Closing in favor of #1030
