### ISSUE TITLE
Improve compatibility with Factory Beans

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1030]
Various samples shed some lights on different use cases around factory beans that we should streamline:

* Using a `ResolvableType` on a `BeanDefinition` that uses a factory bean is problematic as framework's resolution algorithm is not going to apply the same heuristics if a type is set.
* Us specifying a resolvable type without generics being resolved means framework won't attempt to resolve them by, for example, looking at the return type of the factory method.

Talking to @jhoeller, the best course of action seems to use `setBeanClass` with the implementation of the `FactoryBean`coupled with the [`OBJECT_TYPE_ATTRIBUTE`](https://github.com/spring-projects/spring-framework/blob/b1a4d3033be769073d3b4408ececf2cef63164d9/spring-beans/src/main/java/org/springframework/beans/factory/FactoryBean.java#L75). 

This should help us remove the Spring Data specific code that we have for something more generic.

An extra case should be added as well to support Spring Plugin as it sets both a beanClass and a resolvabletype at the moment and does not use the attribute.

**Comment by snicoll** [comment]
Something to keep in mind is that `FactoryBean` could be injected in some cases so we can't lose that type.

**Comment by snicoll** [comment]
I've pushed a couple of commits but that's just workarounds rather than fixing anything. I'll keep this one open and revisit based on progress made in the framework issue.

**Comment by snicoll** [comment]
Some experience working on this. Changing the exposed type to be the target type is problematic on several fronts. We lose the ability to inject the factory bean itself if need to be and the AOT inspection uses the "bean type". Switching to the target type of the factory bean means that inspection for autowired methods and fields happen on the target bean, not the factory bean. We'd have to revisit this to be able to separate the two in `BeanInstanceDescriptor`.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
