### ISSUE TITLE
Upgrade to native build tools 0.9.5

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#1031]

**Comment by sdeleuze** [comment]
As discussed previously, on Gradle side we should try to do this part programmatically in order to remove this from our documentation and start.spring.io:
```
nativeBuild {
	classpath(processAotResources.outputs, compileAotJava.outputs)
}
nativeTest {
	classpath(processAotTestResources.outputs, compileAotTestJava.outputs)
}
```

**Comment by darxriggs** [comment]
for reference: https://github.com/graalvm/native-build-tools/releases/tag/0.9.5
