### ISSUE TITLE
BeanFactoryAnalyzer does not handle ScannedGenericBeanDefinition

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1032]
If a configuration class is scanned, it is not linked back to the class that triggered component scan. As a result, links to this classes are not available either.

Use case, a scanned `@Configuration` class with `@EnableAsync`.

**Comment by snicoll** [comment]
This was a problem when we were relying on the `BeanFactoryStructure` for import links but we aren't anymore. The issue is still real though, moving outside of M1 bucket.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
