### ISSUE TITLE
CoreBeanDefinitionOriginAnalyzer should not log errors for inner beans

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1049]
The analyzer does not take inner beans into account so we end up with misleading error logs such as:

```
2021-09-20 13:51:55.654 ERROR 27188 --- [           main] o.s.c.a.CoreBeanDefinitionOriginAnalyzer : No bean definition found for ConfigurationClass: beanName 'null', class path resource [org/springframework/boot/autoconfigure/hateoas/HypermediaAutoConfiguration$HypermediaConfiguration.class]
```

**Comment by snicoll** [comment]
We're not using `BeanFactoryStructure` for import aware links so I've moved this one out of the M1 bucket.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
