### ISSUE TITLE
Fix Spring Cloud config and discovery samples

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1070]
`configclient-new`, `configserver` and `discoveryclient` samples, cc @OlgaMaciaszek.

`configclient` should be removed since not supported anymore, and `configclient-new` should be renamed to `configclient`.

Support documentation should be updated to mention bootstrap is not supported anymore.

**Comment by OlgaMaciaszek** [comment]
Will do.
