### ISSUE TITLE
BeanInstanceExecutableSupplier does not detect constructor when a property value does not match a collection type

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-projects-experimental/spring-native#1075]
The following error message is being logged:
```
Failed to handle bean default.org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration.LoadBalancerClientSpecification with definition Root bean: class [org.springframework.cloud.loadbalancer.annotation.LoadBalancerClientSpecification]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
```

No constructor is being resolved, cause the argument types don't match; the constructor signature is `public LoadBalancerClientSpecification(String name, Class<?>[] configuration)` and the types in `BeanDefinition` are `class java.lang.String` and `class java.lang.String[]` , so the second argument type does not match and the `resolveConstructor(...)` method returns `null`.

**Comment by snicoll** [comment]
Closing in favor of PR #1140
