### ISSUE TITLE
APPLICATION FAILED TO START after successful build image

### ISSUE THREAD

**Issue by venkataklagisetty** [spring-projects-experimental/spring-native#1080]
using spring boot 2.5.4
spring-native 0.10.3

Here is creator log during build:
[INFO]  > Running creator
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     5 of 12 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/ca-certificates 2.3.2
[INFO]     [creator]     paketo-buildpacks/graalvm         6.3.0
[INFO]     [creator]     paketo-buildpacks/executable-jar  5.1.2
[INFO]     [creator]     paketo-buildpacks/spring-boot     4.4.2
[INFO]     [creator]     paketo-buildpacks/native-image    4.2.0
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/graalvm:jdk" from cache
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/native-image:native-image" from cache
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     Restoring data for "paketo-buildpacks/graalvm:jdk" from cache
[INFO]     [creator]     Restoring data for "paketo-buildpacks/native-image:native-image" from cache
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]
[INFO]     [creator]     Paketo CA Certificates Buildpack 2.3.2
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
[INFO]     [creator]
[INFO]     [creator]     Paketo GraalVM Buildpack 6.3.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/graalvm
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_VERSION              11              the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0               the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes  the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250             the number of threads in memory calculation
[INFO]     [creator]         $JAVA_TOOL_OPTIONS                           the JVM launch flags
[INFO]     [creator]       GraalVM JDK 11.0.12: Contributing to layer
[INFO]     [creator]         Downloading from https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java11-linux-amd64-21.2.0.tar.gz
[INFO]     [creator]         Verifying checksum
[INFO]     [creator]         Expanding to /layers/paketo-buildpacks_graalvm/jdk
[INFO]     [creator]         Adding 128 container CA certificates to JVM truststore
[INFO]     [creator]       GraalVM Native Image Substrate VM 11.0.12
[INFO]     [creator]         Downloading from https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/native-image-installable-svm-java11-linux-amd64-21.2.0.jar
[INFO]     [creator]         Verifying checksum
[INFO]     [creator]         Installing substrate VM
[INFO]     [creator]     Processing Component archive: /tmp/6fc4c6becbe0331aa0a038660fde7c4769c6d6e97d5a90a716a898188d3a6df9/native-image-installable-svm-java11-linux-amd64-21.2.0.jar
[INFO]     [creator]     Installing new component: Native Image (org.graalvm.native-image, version 21.2.0)
[INFO]     [creator]         Writing env.build/JAVA_HOME.override
[INFO]     [creator]         Writing env.build/JDK_HOME.override
[INFO]     [creator]
[INFO]     [creator]     Paketo Executable JAR Buildpack 5.1.2
[INFO]     [creator]       https://github.com/paketo-buildpacks/executable-jar
[INFO]     [creator]       Class Path: Contributing to layer
[INFO]     [creator]         Writing env.build/CLASSPATH.delim
[INFO]     [creator]         Writing env.build/CLASSPATH.prepend
[INFO]     [creator]
[INFO]     [creator]     Paketo Spring Boot Buildpack 4.4.2
[INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
[INFO]     [creator]       Class Path: Contributing to layer
[INFO]     [creator]         Writing env.build/CLASSPATH.append
[INFO]     [creator]         Writing env.build/CLASSPATH.delim
[INFO]     [creator]       Image labels:
[INFO]     [creator]         org.opencontainers.image.title
[INFO]     [creator]         org.opencontainers.image.version
[INFO]     [creator]         org.springframework.boot.version
[INFO]     [creator]
[INFO]     [creator]     Paketo Native Image Buildpack 4.2.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/native-image
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_NATIVE_IMAGE                  true            enable native image build
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILD_ARGUMENTS  --enable-https  arguments to pass to the native-image command
[INFO]     [creator]       Native Image: Contributing to layer
    O]     [creator]         GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)

AND BELOW IS THE ERROR LOG WHEN RAN WITH DOCKER RUN COMMAND.

Error log here:
2021-09-24 16:17:28.277  INFO 1 --- [           main] c.j.infrastructure.listener.Application  : Starting Application using Java 11.0.12 on 6b97de4c7956 with PID 1 (/workspace/com.jbhunt.infrastructure.listener
.Application started by cnb in /workspace)
2021-09-24 16:17:28.277  INFO 1 --- [           main] c.j.infrastructure.listener.Application  : The following profiles are active: DEV,KUBE
2021-09-24 16:17:28.351  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.facto
ry.BeanCreationException: Error creating bean with name 'healthEndpointGroupsBeanPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.
class]: Initialization of bean failed; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: Invalid declaration of container type [org.springframework.jms.annotation.JmsList
eners] for repeatable annotation [org.springframework.jms.annotation.JmsListener]; nested exception is java.lang.NoSuchMethodException: No value method found
2021-09-24 16:17:28.353  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-09-24 16:17:28.354 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for No value method found is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

**Comment by cschaible** [comment]
Hi @venkataklagisetty,

it is "normal" that applications can fail to start successfully, even if a build succeeds. When the GraalVM compiles the code, it does a static code analysis to figure out which classes have to be packaged into the native image. The java Reflection API though cannot be detected entirely through that [mechanism](https://www.graalvm.org/reference-manual/native-image/Reflection/) (because it's by design evaluated at runtime).
As suggested in the output you have to add a native hint to your application. If your code or one of your libraries uses reflection, then the GraalVM needs a hint to know that this class is required at runtime.
For many spring modules those hints were already created and are automatically applied if the libraries are detected. A list of the supported modules can be found in the [documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support-spring-boot).
For some third party libraries there are also NativeHints defined. You can find them [here](https://github.com/spring-projects-experimental/spring-native/tree/main/spring-native-configuration/src/main/java). 
You have to look into the stacktrace / code to figure out in which class the "value" method is defined and then define a native hint as described [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints).

If there is no way of getting it successfully started, by defining native hints explicitly as described in the documentation, you can try to use the [GraalVM Tracing Agent](https://www.graalvm.org/reference-manual/native-image/Agent/) to generate the config files while running the jar normally on a GraalVM (non-native). This although is not ideal as it is hard to maintain.

**Comment by venkataklagisetty** [comment]
@cschaible , Need help on native hint/type hint usage

**Comment by cschaible** [comment]
@venkataklagisetty, I don't have an application with JmsListeners at hand and not so much time at the moment. My guess though is that you have to define something like:
```
@TypeHint(types = JmsListeners.class, methods = {@MethodHint(name = "value", parameterTypes = {JmsListener[].class})})
@SpringBootApplication
public class XyzApplication {
...
}
``` 

Maybe this [link](https://medium.com/geekculture/spring-native-beta-release-a70919da4762) helps to better understand how spring AOT works / hints are applied.
