### ISSUE TITLE
CPU Usage double higher than OpenJDK

### ISSUE THREAD

**Issue by vavramovski** [spring-projects-experimental/spring-native#1087]
Hello, 
I'm doing research where I compare benchmark and other stats between GraalVM Native Image and standard JAR Spring Boot Applications.

The application is simple, I am accessing endpoint with JWT PS512 Auth and database access.

Both applications are dockerized (JAR and Native Image) and the Native Image is winning in every stat except CPU Usage. 
When running 
docker stats <container>
I get **above 100%** for Dockerized Native image
and
About **40%** for Dockerized JAR 

Is there any particular reason for it, or is it only on my side?

**Comment by sdeleuze** [comment]
Native can consume more than the JVM due to less runtime optimizations, but such difference is suspicious, could you please share the related project and document how you measured those figures ?

**Comment by vavramovski** [comment]
The project: https://github.com/vavramovski/graalvm-native-demo/tree/port-jwt
There's the Dockerfile that I used to create the docker image for the given JAR file.

I'm running them using 
**docker run -p 8080:8080 -d <image-name>** 

And getting the stats with the command 
**docker stats <container id>**

Then, to load-test the application i use npm package called **loadtest**
running the command with 
```
loadtest -c 4 --rps 200 -H Authorization:"Bearer eyJhbGciOiJQUzUxMiJ9.eyJzdWIiOiJWaWt0b3IiLCJpYXQiOjE2MzI3MzYwMDcsImV4cCI6MTYzMjgyMjQwN30.GojK2CEfylPNeb93uh788E54N1qvkCAn-y10Bp7WCU6nr0PbbKn8MGIt8MB_NiqR7c2g7treAMT_t8wq52iM2M3aU__Qye1lLlPDrM8B6i_hk0Alq5iv_chsh3CBgZDYlOtfwttHU_71NJtXLSTdbGSNuI69wgzfkwolFk7e-tfE-a5sRFBf1nsY2KbrBUl4FDAR8DgDi2Am0EkriEG0h8w9_mTpUSMHH5VQ0dYhVX3r0DkBXezkgimJkUZRoc_Hx_t7rZuH4dDxnOf1gWMHV4fG-wHJ4PlWIYWpJqTHW8oAc6B1WkrPIAslUa2WR6kXAHzNOyj9YhHaxCnCoTKw0Q" http://18.192.197.154:8081/cart/2
```
The IP in this case was my EC2 instance, and if you get Unauthorized exception then you can LogIn with the following request 
POST {{host}}/auth/signin
BODY {
    "username":"Viktor",
    "password":"123456"
}

**Comment by vavramovski** [comment]
Guess the issue was this:
I was building the Native Docker Image on Windows 10 
and was running it on Ubuntu 20.04 Server

Now i build and ran the image on Ubuntu 20.04 Server, and it has normal cpu usage, about 40% 

Is it possible that was the case ?
