### ISSUE TITLE
EventListener registration does not work with package private annotated types

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-native#1089]
## Steps to reproduce

```bash
$ git clone https://github.com/odrotbohm/spring-restbucks
$ cd spring-restbucks
$ git checkout hacking/aot
$ ./mvnw verify -DskipTests
```

## Outcome

Compilation fails due to references to package protected classes from `target/generated-sources/spring-aot/src/main/java/org/springframework/aot/ContextBootstrapInitializer.java`:

```java
context.registerBean("org.springframework.aot.EventListenerRegistrar", EventListenerRegistrar.class, () -> new EventListenerRegistrar(context,
  EventListenerMetadata.forBean("engine", Engine.class).eventListenerFactoryBeanName("org.springframework.transaction.config.internalTransactionalEventListenerFactory").annotatedMethod("handleOrderPaidEvent", OrderPaid.class),
  EventListenerMetadata.forBean("orderInitializer", OrderInitializer.class).annotatedMethod("init", ApplicationReadyEvent.class)
));
```

The references to `Engine` and `OrderInitializer` cause the compile errors, as they're package protected. Making them `public` as a workaround works.

## Expected outcome

The generated code compiles successfully.

## Other observations

I see the actual instance creation code generated into the application package for the package protected classes, too. So it seems that it's the event listener related, generated code that does not yet honor the package protection.

**Comment by snicoll** [comment]
Event listener registrations don't support package private event listeners indeed. This is something that was on my TODO list. Thanks for raising the issue.

**Comment by snicoll** [comment]
Moving to M1 to give restbucks a chance to work sooner than later.
