### ISSUE TITLE
NativeHint requirement for non public class

### ISSUE THREAD

**Issue by venkataklagisetty** [spring-projects-experimental/spring-native#1090]
I am getting exception when I ran docker run command.
The class that shows error is a non public class so unable to use it in NativeHint or TypeHint

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.facto
ry.BeanCreationException: Error creating bean with name 'healthEndpointGroupsBeanPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.
class]: Initialization of bean failed; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: Invalid declaration of container type [org.springframework.jms.annotation.JmsList
eners] for repeatable annotation [org.springframework.jms.annotation.JmsListener]; nested exception is java.lang.NoSuchMethodException: No value method found
2021-09-27 16:02:35.302  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

**Comment by venkataklagisetty** [comment]
@cschaible  ,Please help

**Comment by venkataklagisetty** [comment]
Finally I am able to cross the above issue. it seems passed. but getting similar issues for other classes.
I declared below nativehint in my springbootapplication class.
@NativeHint(trigger = HealthEndpointAutoConfiguration.class ,
        types = @TypeHint(types  ={JmsListener.class, JmsListeners.class}))


Please guide me if some other better option available

**Comment by cschaible** [comment]
If you have to use a non-public class in a NativeHint/TypeHint you can use the `typeNames` parameter instead of the `types` parameter. Use the fully qualified class name as a string.

```
@TypeHint(typeNames = {"com...."})
```
