### ISSUE TITLE
Runtime dependencies imported in ContextBootstrapInitializer code cause IDE compilation issues

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-projects-experimental/spring-native#1093]
Sample that reproduces the issue: `discovery-client`.
After packaging the sample with maven with AOT and running it with the IDE (used IntelliJ for my tests), the IDE was complaining that the aot-generated sources contained imports from missing dependencies, i.e. Google's `Gson`; adding the dep to pom and refreshing IDE mvn setup fixes the issue, but it's a usability concern.

**Comment by odrotbohm** [comment]
A similar issue is caused when the projects use ByteBuddy for code transformation as that only considers the compile classpath. I've filed [an issue](https://github.com/raphw/byte-buddy/issues/1121) for that to be able to tweak that.

**Comment by odrotbohm** [comment]
Just for reference, ByteBuddy just released [1.11.19](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.11.19), which contains an option to work against the runtime classpath.

**Comment by sdeleuze** [comment]
@aclement Could you please check if that's of interest for us?

**Comment by sdeleuze** [comment]
Spring AOT already considers `runtime` and not `compile` classpath for the generation.

What happens here is `com.netflix.eureka:eureka-client` using `runtime` dependency for GSON, so as expected it is taken in account.
```
[INFO] |  +- com.netflix.eureka:eureka-client:jar:1.10.17:compile
[INFO] |  |  +- com.netflix.netflix-commons:netflix-eventbus:jar:0.3.0:compile
[INFO] |  |  |  +- com.netflix.netflix-commons:netflix-infix:jar:0.3.0:runtime
[INFO] |  |  |  |  +- commons-jxpath:commons-jxpath:jar:1.3:runtime
[INFO] |  |  |  |  +- joda-time:joda-time:jar:2.3:runtime
[INFO] |  |  |  |  +- org.antlr:antlr-runtime:jar:3.4:runtime
[INFO] |  |  |  |  |  +- org.antlr:stringtemplate:jar:3.2.1:runtime
[INFO] |  |  |  |  |  \- antlr:antlr:jar:2.7.7:runtime
[INFO] |  |  |  |  \- com.google.code.gson:gson:jar:2.8.9:runtime
```

The IDE automatically attaches the generated code and is using the compile classpath, hence the errors repported:
![image](https://user-images.githubusercontent.com/141109/149509511-abc9214a-b934-4159-9e8c-54924f4e6ae9.png)

After discussing with @snicoll, I think what we would need here is to find a way that IDEs configure the generated code with runtime classpath, or compile + runtime. That may require raising issues on IDE side, so for now I move it to the backlog.

**Comment by sdeleuze** [comment]
After a discussion with @bclozel, let's change the name of the directory to avoid it to be recognized by IDEA automatically with the wrong classpath, and document how to configure it properly.
