### ISSUE TITLE
Investigate Adding Fallback for Beans with no Matching Generic Parameters

### ISSUE THREAD

**Issue by garyrussell** [spring-projects-experimental/spring-native#1097]
https://github.com/spring-projects-experimental/spring-native/pull/1078#discussion_r716381177

For example, Boot auto configures a `KafkaTemplate<Object, Object>` without AOT, the framework has several layers fallbacks such that `KafkaTemplate<String, String>` can be auto wired as a dependency.

Unfortunately, AOT does not support this "feature" so there is no match during wiring since a bean with the expected generic type parameters is required.

While this might be the correct behavior, it feels like missing functionality with AOT.

The work around in the Kafka samples was to use `<Object, Object>`.

Perhaps a better work around would be to inject the beans with no generics and perform an unchecked cast....

```java
	@Bean
	public ApplicationRunner runner(KafkaTemplate templateArg,
				ConsumerFactory cfArg) {

		@SuppressWarnings("unchecked")
		KafkaTemplate<String, String> template = templateArg;
		@SuppressWarnings("unchecked")
		ConsumerFactory<String, String> cf = cfArg;
		cf.addListener(new ConsumerFactory.Listener() { });
		return args -> {
			template.send("graal", "foo");
			System.out.println("++++++Sent:foo");
			Thread.sleep(5000);
		};
	}
```

**Comment by snicoll** [comment]
paging @jhoeller

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
