### ISSUE TITLE
Review SpringFactoriesProcessor infrastructure

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1114]
`ActuatorMetricsEliminator` seems not wired with Spring AOT properties, and @aclement hinted that potentially there is no gain anymore when removing the JMeter infra (why, already removed by the new AOT engine?).

`BackgroundPreInitializerDeactivator` is likely not required since there is a filter in `DefaultFactoriesCodeContributor`.

`ConfigurableSpringFactoriesProcessor` is probably not useful anymore.

So not sure if we should remove `SpringFactoriesProcessor` infra or maybe just update implementations and use it to avoid hardcoded behavior in `DefaultFactoriesCodeContributor`. Maybe the second option ?

**Comment by aclement** [comment]
This is all gone now with no noticeable impact on the numbers. Aot is taking care of it.
