### ISSUE TITLE
"Freeze GraalVM Version" section in documentation uses an older, incompatible version of GraalVM

### ISSUE THREAD

**Issue by psinghal04** [spring-projects-experimental/spring-native#1129]
Refer to the "Freeze GraalVM Version" section of the Spring Native v0.10.4 documentation: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_freeze_graalvm_version

The plugin code as illustrated uses the following image: "gcr.io/paketo-buildpacks/java-native-image:5.3.0". Version 5.3.0 of the image contains version 21.0 of GraalVM, which is incompatible with this version of Spring Native. It should be version 5.8.0, which contains GraalVM 21.2.

**Comment by sdeleuze** [comment]
Fixed with `5.5.0` (as documented on Buildpack side) not `5.8.0`.
