### ISSUE TITLE
Migrate remaining ComponentProcessor to BeanFactoryNativeConfigurationProcessor

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#1130]
Currently 0.11 is still driving component processors from a synthesized `spring.components`. We should review what the right way is to handle this in an Aot world and perhaps port the existing processors (where still required) if/when there is an Aot alternative mechanism.

**Comment by sdeleuze** [comment]
Remaining ones are listed [here](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native-configuration/src/main/resources/META-INF/services/org.springframework.nativex.type.ComponentProcessor).

**Comment by sdeleuze** [comment]
[Ongoing full build](https://ci.spring.io/teams/spring-native/pipelines/spring-native-0.11.x/jobs/build-samples-java11/builds/100) after @aclement changes before doing the final cleanup.

**Comment by aclement** [comment]
Done!  All ComponentProcessors migrated and `ComponentProcessor` interface deleted. Now whether the new classes should be `BeanFactoryNativeConfigurationProcessor`s or just `BeanNativeConfigurationProcessor`s. That is something to review at some point.

**Comment by sdeleuze** [comment]
Thanks, I have created #1289 as a follow-up issue.
