### ISSUE TITLE
Remove outdated Maven and Gradle configuration options

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1133]

**Comment by bclozel** [comment]
Since the AOT processing has been rewritten for 0.11, a few options are not available/useful anymore:

* `removeUnusedConfig`
* `failOnMissingSelectorHint` 
* `buildTimePropertiesChecks` 
* `buildTimePropertiesMatchIfMissing` 
* `ignoreHintsOnExcludedConfig`
