### ISSUE TITLE
Native reflection configuration for brave.kafka.clients.TracingProducer is missing

### ISSUE THREAD

**Issue by matus753** [spring-projects-experimental/spring-native#1138]
Hi, 

I was trying to use spring-native on our microservice which simply read avro data from on kafka topic and send it to another kafka  topic as json, using spring-cloud-stream and functional approach
Due to distributed tracing we are using spring-cloud-starter-sleuth too which should be supported, as is written in your documentation 
After a lot of troubles I finally successfully built native image, but I am not able to start it
At first I've got a weird error: 
`Native reflection configuration for java.util.LinkedHashMap.<init> is missing`
I do not uderstand why there was not created native reflection for this by spring-native but I solve this by type hint:
`@TypeHint(typeNames = "java.util.LinkedHashMap", methods = @MethodHint(name = "<init>"))`
I just end up with another error (this one I  can at least point at something):
`Native reflection configuration for brave.kafka.clients.TracingProducer is missing`
Brave is used by spring-cloud-starter-sleuth which you claimed is supported, but it look like it has a problem when it should work with Kafka.
Shouldn't be this handled by spring native? I was expecting that I will need to use TypeHint annotation only in case of some custom implementations.

**Comment by sdeleuze** [comment]
Could you please share a sample project to allow us to refine the support?

**Comment by matus753** [comment]
Hi,

I am sending small dummy project to reproduce error:
[dummy-app.zip](https://github.com/spring-projects-experimental/spring-native/files/7467366/dummy-app.zip)

steps:
mvn -Pnative package
target/dummy-app

**Comment by garyrussell** [comment]
@sdeleuze I suggest assigning this to the spring-cloud-sleauth team

    Native reflection configuration for brave.kafka.clients.TracingProducer is missing.

This class (and others) is a wrapper around the `KafkaProducer` class (from `kafka-clients.jar`) and has nothing to do with spring-kafka; the problem may also apply to use of Kafka clients with sleuth without using spring-kafka.

I also am not familiar with all the nuances of sleuth so it would be better for that team to address this, although I am happy to consult with them as needed.

Thanks.

**Comment by sdeleuze** [comment]
@OlgaMaciaszek Could you please take care of this one?

**Comment by OlgaMaciaszek** [comment]
Will do.
