### ISSUE TITLE
Explore native configuration inference for programmatic API

### ISSUE THREAD

**Issue by oclay1st** [spring-projects-experimental/spring-native#1152]
Almost every time I use Jackson to convert something to a POJO, I end up adding that POJO class to the @SerializationHint annotation. Can anyone tell me why this process is necessary (from an end-user point of view) and if it could be improved in the future, is it a really annoying process?

Why do Spring Native and Quarkus need to support third-party libraries instead of creating a standard support agreement?

Sorry for the newbie questions, but I think many others will ask the same, thanks for the amazing work.

**Comment by sdeleuze** [comment]
Probably worth to explore later.

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by sdeleuze** [comment]
On Spring Native side no, but we are going likely to explore this in Spring Framework 6 and Spring Boot 3.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
