### ISSUE TITLE
Add support for FactoryBean constructor

### ISSUE THREAD

**Issue by artembilan** [spring-projects-experimental/spring-native#1155]
There are some use-cases when `FactoryBean` target type cannot be determined from generics or some other info during `beanFactory.resolveDependency()`.
For this purpose we rely on the `FactoryBean.OBJECT_TYPE_ATTRIBUTE` attribute setting on `BeanDefinition`.
Such an attribute should be copied to the target generated code.
This way we won't need to develop our own simple `BeanRegistrationWriter` just for a sake of this attribute carrying on.

**Comment by snicoll** [comment]
I changed my mind and I added a dedicated writer for the case of a `FactoryBean` whose target type is not defined upfront but via the attribute. It does some additional checks to verify that the attribute is compatible with the bounds of the factory bean.
