### ISSUE TITLE
Add support for non Spring Boot tests

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1170]
We don't support anything that's not a `SpringBootTestContextBootstrapper` and the mapping currently assumes that everything is a Spring Boot test. In the interest of making our support a bit more generic, it would be nice to have an `AotTestContextProcessor` that handles the TCF as well as a way to create the mapping for multiple implementations.

**Comment by snicoll** [comment]
FTR, we no longer have an assumption about Spring Boot test for the mapping as this is taken care of by the `AotTestContextProcessor` implementation now.

**Comment by sbrannen** [comment]
Great work, @snicoll! 👏
