### ISSUE TITLE
Missing hints for health indicators

### ISSUE THREAD

**Issue by olivierboudet** [spring-projects-experimental/spring-native#1183]
Hello,

I am using spring native 0.11.0-SNAPSHOT (sha1 78bfed5) with Spring Boot 2.6.0-RC1.
I have following gradle dependencies : 
```
implementation 'org.springframework.boot:spring-boot-starter-actuator'
implementation 'org.springframework.boot:spring-boot-starter-web'
implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
```
It builds fine but I have an error at runtime :

```
2021-10-24 19:55:20.628 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for org.springframework.boot.actuate.mongo.MongoHealthIndicator.<init>(org.springframework.data.mongodb.core.MongoTemplate) is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

```

**Comment by olivierboudet** [comment]
Sorry @snicoll but is this possible to reopen this issue ? It is not working with the current `main`snapshot, I think the polishing broke something.
You can reproduce the issue with this repo : https://github.com/olivierboudet/spring-native-demo
I always have the error when running the application : 
```
Native reflection configuration for org.springframework.boot.actuate.mongo.MongoHealthIndicator.<init>(org.springframework.data.mongodb.core.MongoTemplate) is missing.

```

**Comment by snicoll** [comment]
Alright, It is probably registered but with the wrong type.

**Comment by olivierboudet** [comment]
> Alright, It is probably registered but with the wrong type.

yep it seems to be registered just as `Object` (ie. `beanFactory.getBeanDefinition(beanName).getResolvableType().toClass();` returns `Object`).
The only solution I found to have the correct type is to use `beanFactory.getBean(beanName).getClass();`.

**Comment by snicoll** [comment]
>  The only solution I found to have the correct type is to use beanFactory.getBean(beanName).getClass();.

You can't do that as it instantiates the the bean and we can't do that at build time. I'll have a look shortly.

**Comment by snicoll** [comment]
The problem is the composite pattern in Spring Boot returns either a composite of `T` or `T` if there is only one instance. Because a single method is doing both, the return type is `HealthContributor`, hiding the actual type that the composite is going to use via reflection. 

We'll have to inspect things a bit more to get back the actual type.

**Comment by olivierboudet** [comment]
Thank you ! I will test it soon :)
