### ISSUE TITLE
Contribute resources from AOT test bootstrap generation

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#1192]
Just like the main AOT bootstrap generation phase, the test one should contribute resources and especially reflection configuration.

**Comment by sbrannen** [comment]
Related issues:

- https://github.com/graalvm/native-build-tools/pull/132
- https://github.com/graalvm/native-build-tools/issues/150

**Comment by sdeleuze** [comment]
Good catch, let's do the next steps as part of #1202.

**Comment by sdeleuze** [comment]
Reopening it because the native configuration is not generated correctly with Gradle.
