### ISSUE TITLE
Best approach to manage/declare native hint for common libraries

### ISSUE THREAD

**Issue by neoludo** [spring-projects-experimental/spring-native#1201]
Hi there,

I can see that all Native Hints are gathered into spring-native-configuration (ex.: https://github.com/spring-projects-experimental/spring-native/blob/c075048144293f0a3bed729782d9c41914c425c2/spring-native-configuration/src/main/java/org/springframework/messaging/MessagingAnnotationHints.java) and not in respective libraries projects.
We have home made common librairies, that we want to use for native projects.

We had to add in these projects annotations in application usinf those libraries :
```
@SpringBootApplication
@AotProxyHint(targetClass = com.mycompany.common.springboot.losspi.config.LosspiConfig.class)
@AotProxyHint(targetClass = com.mycompany.common.springboot.losspi.LosspiHelper.class)
```

I don't want to add these annotations for each project using that LIB. 
What is the best approach ?
- have a central native-configuration project gathering all the native hints for all home made commons libs
- integrate hints in each home made commons libs (do you have a sample for this)
- other ?

Thanks in advance for your help.
Ludovic

**Comment by sdeleuze** [comment]
That's an interesting use case to explore, and I think the related extension model is not yet fully defined.

Hint annotations are expected to be provided on `@Configuration` classes used by your project, can you try to provide this in your library and maybe follow https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration to make it automatically registered when it is in the classpath?

Please let us know how it goes.

**Comment by neoludo** [comment]
Good idea Seb.
I did that :
```
@Configuration
@ConditionalOnClass(AotProxyHint.class)
@AotProxyHint(targetClass = com.lodh.common.springboot.losspi.config.LosspiConfig.class)
@AotProxyHint(targetClass = com.lodh.common.springboot.losspi.LosspiHelper.class)
public class LosspiNativeAutoConfiguration {
}
```
in the auto-configure module of my starter, and it works fine in the apps using that library.
Put the dependency on spring native optional.

Seems to be a good approach.

Thanks for your help
Ludo
