### ISSUE TITLE
Invalid root directory

### ISSUE THREAD

**Issue by Ragin-LundF** [spring-projects-experimental/spring-native#1209]
Hi,

I'm using Gradle together with Spring Boot 2.5.6 and Spring Native 0.10.5 in an environment with subprojects for each layer (REST, domain, server part ...).
After adding the dependencies, it shows me always the following message:

> * What went wrong:
> Execution failed for task ':generateAot'.
>  Invalid root directory 'C:\Users\username\\.gradle\caches\modules-2\files-2.1\org.springframework.experimental\spring-native\0.10.5\436e7a80f345814e577200a6e4c2a098d1cd668d\spring-native-0.10.5.jar'

The directory exists, the jar file is there.

What I figured out so far was, that I can't delete the directory without a restart. Something blocks the file, but I was not able to see what (closed the IDE and all Java processes before).

Has anybody a hint for this issue?

**Comment by sdeleuze** [comment]
Please share the project if you want us to test if this is reproducible.

**Comment by sdeleuze** [comment]
I am wondering what is this strange `C:\Users<user>` path prefix, is it really printed like that or is it a typo you did during replacing the real user name?

**Comment by Ragin-LundF** [comment]
Hi.

I can't share so far the project, but I can try to prepare a similar thing.
The C:\Users\<user> was only anonymized by me ;).

**Comment by bclozel** [comment]
This sounds like the build plugin was applied on the root project instead of the Spring Boot application module. In this case, the error message would mean that AOT processing failed to find a main class in the classes folder and instead tried to scan dependencies (and failed).

Did you have a look at the [multi-modules samples](https://github.com/spring-projects-experimental/spring-native/tree/main/samples/multi-modules)?

**Comment by Ragin-LundF** [comment]
Thank you very much. This was the issue.
I looked into this project, but I didn't see it clear enough.

Maybe a hint in the documentation would be good that the plugin should be applied only at the submodule which contains the final executable.

**Comment by sdeleuze** [comment]
I see it [on the CI](https://ci.spring.io/teams/spring-native/pipelines/spring-native-0.11.x/jobs/build-samples-java11/builds/83) as well so it is likely something we should fix, I will have a deeper look.
