### ISSUE TITLE
Fix petclinic-jpa test compilation issue

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1212]
See related error in https://ci.spring.io/teams/spring-native/pipelines/spring-native-0.11.x/jobs/build-samples-java11/builds/83.

**Comment by snicoll** [comment]
The good news is that the bean definition that refers to test classes is a `BeanDefinitionRegistryPostProcessor` that is useless at build time and should be removed. It's not ROLE_INFRASTRUCTURE at the moment and should be. Once I fix that in Spring Boot, it might just fix itself.

**Comment by snicoll** [comment]
It did. Closing in favor of https://github.com/spring-projects/spring-boot/issues/28540
