### ISSUE TITLE
Spring Security error related to AuthenticationFailureBadCredentialsEvent with 0.11

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1215]
Spring Security seems to be broken with 0.11-M1 and 0.11-M2.
I've attached a really simple COnfiguration class (credentionals crossed out) for in Memory Auth.
While this worked for all prev versions, it breaks since M1 and M2:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain': Unexpected exception during bean creation; nested exception is java.lang.RuntimeException: Authentication event class org.springframework.security.authentication.event.AuthenticationFailureBadCredentialsEvent has no suitable constructor
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
```

[](url
[SecurityConfiguration.txt](https://github.com/spring-projects-experimental/spring-native/files/7481348/SecurityConfiguration.txt)
)

**Comment by sdeleuze** [comment]
@eleftherias Could you please take care of this issue?

**Comment by snicoll** [comment]
That looks like AOT isn't using the right creator for the bean.

**Comment by snicoll** [comment]
@goafabric I can't reproduce the problem you've described using the configuration class. Can you please share a minimal sample that reproduces the problem? You can do so by attaching a zip to this issue or sharing a link to a GitHub repository.

**Comment by goafabric** [comment]
@snicoll 
thx 4 the fast reply ... and sorry did not see your post.
yes sure .. there is a rather small service example
https://github.com/goafabric/callee-service/tree/spring-native-0.11

handling of spring native is handled by a profile inside the parent pom ..

it works with 0.10 and breaks when upgrading .. but maybe i got something wrong here ...

also i compile with eclipse-temurin jdk 17, but set the compiler level to 11

**Comment by sdeleuze** [comment]
The compile script seems to be broken (deploy does not work, wrong version used for the Docker image) but doing `mvn clean package -P docker-image-native` then `docker run --name callee-service-native --rm -p50900:50900 goafabric/callee-service-native:1.1.1-native11-SNAPSHOT` works for me.

@goafabric Could you please double check on your side?

**Comment by goafabric** [comment]
@sdeleuze 
you are right, the build-native script is incorrect .. which doesn't matter because everything is built through github actions
additionally spring security was deactivated on that branch .. sry i should have made that clear

i reactivated and triggered a new build .. which will break eventually

**Comment by goafabric** [comment]
build works .. but the docker run from maven then crashes
                                    <goals>
                                        <goal>exec</goal>
                                    </goals>
                                    <configuration>
                                        <executable>docker</executable>
                                        <arguments>
                                            <argument>run</argument>
                                            <argument>${docker.registry}/${project.artifactId}-native:${project.version}

**Comment by goafabric** [comment]
So what's the status of this Ticket ?
Upgrading not 11-RC1 did not help .. but what i found out is, that setting a Typehint for
AuthenticationFailureBadCredentialsEvent, seems to work.
But only to crash with the next class that is not accessible.
Something odd is going on here

**Comment by snicoll** [comment]
> So what's the status of this Ticket ?

You are the reporter so I suspect you are subscribed to it and you can see that the team hasn't got the time to look into it. Sorry we didn't make it in time for RC1 but submitting a PR or investigating what the next type hint is could help us track down a solution for this.

**Comment by goafabric** [comment]
@snicoll thx 4 letting me know...
judging from the logs the next Typehint would be "AuthenticationFailureExpiredEvent", but from the experience i have with native images until know, i don't think it will stop there. And everything worked perfectly fine with 10.x .. so that is the strange thing here

**Comment by sdeleuze** [comment]
I can indeed reproduce the `org.springframework.security.authentication.event.AuthenticationFailureExpiredEvent has no suitable constructor` error.

@eleftherias Could you please have a deeper look to check if we missed type hints on classes like `AuthenticationFailureExpiredEvent`?

**Comment by goafabric** [comment]
Add alle the TypeHints below at least now allows the application to be bootstrapped
But then during access we run into the next error:

-- cut ---
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'permitAll' cannot be found on object of type 'org.springframework.security.web.access.expression.WebSecurityExpressionRoot' - maybe not public or not valid?
---

Honestly .. there seem to be some massive breaking changes going on under the hood ..

--- cut ---

@TypeHint(types = {
        AuthenticationFailureBadCredentialsEvent.class,
        AuthenticationFailureCredentialsExpiredEvent.class,
        AuthenticationFailureDisabledEvent.class,
        AuthenticationFailureExpiredEvent.class,
        AuthenticationFailureLockedEvent.class,
        AuthenticationFailureProviderNotFoundEvent.class,
        AuthenticationFailureProxyUntrustedEvent.class,
        AuthenticationFailureServiceExceptionEvent.class,

})

**Comment by snicoll** [comment]
> Honestly .. there seem to be some massive breaking changes going on under the hood ..

@goafabric you've already stated that and I don't think that's constructive to repeat that over again. This issue is still open and we intend to fix. Perhaps it would help to mention that Spring Native 0.11.x is a major rewrite of what we had in 0.10 and is still an experimental project. We've done our best to keep things running for people while fixing structural problems with build time and memory consumption, but regressions like these are unavoidable. Thanks for bearing with us.

**Comment by goafabric** [comment]
@snicoll i get your point and sorry for that ... 
but as a long term (15 years+) spring user, and getting used to how amazingly stable Spring APIs always where,
it's a little bit frustrating how fragile Spring Native sometimes seems ...
but sure .. it's still  a beta the 11.0 is just an RC .. and I can only imagine how much effort it is
to migrate such a massively dynamic Framework like Spring to the static AOT world of GraalVM

so no offence .. and thx for the good work guys

**Comment by snicoll** [comment]
> but as a long term (15 years+) spring user, and getting used to how amazingly stable Spring APIs always where,
it's a little bit frustrating how fragile Spring Native sometimes seems ...
but sure .. it's still a beta the 11.0 is just an RC .. 

To conclude on this topic, Spring Native is an experimental _project_. I wasn't talking about the milestones or the RC. The whole project is experimental, see the name of the GitHub org and [the readme of the project]. As such, comparing it with the maturity of the core framework isn't fair IMO. But we're getting there with Spring Framework 6!

**Comment by eleftherias** [comment]
The problem is when you exclude the `SecurityAutoConfiguration`.
```
@SpringBootApplication(exclude = { SecurityAutoConfiguration.class })
```
Many of the [security hints](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/security/servlet/SecurityHints.java#L53) use this class as a trigger. It's still not clear to me why this worked in 0.10.x, since this has always been the trigger for the missing classes.

We can fix this by changing the trigger for those classes to something else, potentially `WebSecurityConfiguration` and `WebFluxSecurityConfiguration`.

What do you think @sdeleuze?

**Comment by snicoll** [comment]
Using an auto-configuration as a trigger feels generally a bad idea to me as the user could configure things themselves and the auto-configuration could back-off early as well. Using components that would be available for the relevant hints sounds both more robust and more precise regarding what needs what.

**Comment by eleftherias** [comment]
Thanks @snicoll, that makes sense to me. I'll submit a PR to update the hints.

**Comment by sdeleuze** [comment]
Make sense, see #342 related issue.
