### ISSUE TITLE
Reflection hints are missing for loading test contexts

### ISSUE THREAD

**Issue by sbrannen** [spring-projects-experimental/spring-native#1235]
`AotContextLoader` uses reflection to load `org.springframework.aot.TestContextBootstrapInitializer` and invoke its static `getContextLoaders()` method; however, there is currently no entry in `reflect-config.json` to allow that.

Some basic logging reveals the following.

> Failed to invoke method [getContextLoaders()] on class [org.springframework.aot.TestContextBootstrapInitializer]: java.lang.ClassNotFoundException: org.springframework.aot.TestContextBootstrapInitializer

**Comment by snicoll** [comment]
This code is generated so we probably need to improve our `NativeConfigurationRegistry` to handle generated code as well.

**Comment by snicoll** [comment]
The infrastructure for contributing reflection config of generated code was added with #1239
