### ISSUE TITLE
PrimaryDefaultValidatorPostProcessor triggered at different time with AOT leads to incomplete Validator bean definition

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-projects-experimental/spring-native#1243]
In [this sample](https://github.com/OlgaMaciaszek/fork-dummy-app), in AOT mode, `NoUniqueBeanDefinition` is thrown for `Validator` beans, even though one of the two is annotated with `@ConditionalOnMissingBean`:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'integrationMessageHandlerMethodFactory': Unsatisfied dependency expressed through method 'messageHandlerMethodFactory' parameter 1; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.validation.Validator' available: expected single matching bean but found 2: defaultValidator,mvcValidator`

**Comment by snicoll** [comment]
The problem is a different order of processing for `BeanDefinitionRegistryPostProcessor`. I have changed a custom code to use a callback of framework and that fixed the issue. Unfortunately, calling these has the side effects of contributing quite some more bean definitions, certain with not the type I'd expect. I am investigating.

**Comment by snicoll** [comment]
This was already fixed as part of #1213 but I've added a test to validate the behaviour. @OlgaMaciaszek your sample app still doesn't work unfortunately as Spring Integration is not yet supported.

**Comment by OlgaMaciaszek** [comment]
Ok - the users will need to wait till that's done then for these kinds of projects. Anyway, that user-provided sample has allowed us to discover and fix at least 3 different issues :) . Thanks, @matus753.
