### ISSUE TITLE
AOT generated `ContextBoostrapInitializer` does not work for `FlywayAutoConfiguration`

### ISSUE THREAD

**Issue by marcust** [spring-projects-experimental/spring-native#1244]
I threw `0.11.0-M2` at an existing project (migrated to boot 1.6. RC) and got:

```
> Task :compileAotMainJava
build/generated/sources/aotMain/org/springframework/boot/autoconfigure/flyway/ContextBootstrapInitializer.java:10: error: StringOrNumberToMigrationVersionConverter has private access in FlywayAutoConfiguration
    BeanDefinitionRegistrar.of("stringOrNumberMigrationVersionConverter", FlywayAutoConfiguration.StringOrNumberToMigrationVersionConverter.class).withFactoryMethod(FlywayAutoConfiguration.class, "stringOrNumberMigrationVersionConverter")
```

I am not sure how much feedback you want on those things, but currently you can not compile an app that uses Flyway. I am not sure how Spring handles that internally, I guess the Bean Definition has to use the more generic base type?

**Comment by sdeleuze** [comment]
Likely already fixed via https://github.com/spring-projects/spring-boot/issues/28437 by [this commit](https://github.com/spring-projects/spring-boot/commit/837e2ac277bf9496e07238431710251c083c7a0b#diff-eeafdb972416cd3b95198ce3acd830206b4031920363e8cdac43ff76e0b30df3R402) which will be part of Spring Boot 2.6.0.
