### ISSUE TITLE
Add native hints for AssertJ soft assertions

### ISSUE THREAD

**Issue by sbrannen** [spring-projects-experimental/spring-native#1245]
## Overview

If you attempt to use AssertJ's `SoftAssertions.assertSoftly(...)` feature, you currently will encounter an exception similar to the following.

```
java.lang.RuntimeException: java.lang.NoSuchMethodException: org.assertj.core.api.SoftAssertions.<init>()
  org.assertj.core.api.SoftAssertionsProvider.assertSoftly(SoftAssertionsProvider.java:117)
  org.assertj.core.api.SoftAssertions.assertSoftly(SoftAssertions.java:162)
  com.example.commandlinerunner.CommandlinerunnerApplicationTests.contextLoads(CommandlinerunnerApplicationTests.java:27)
  java.lang.reflect.Method.invoke(Method.java:566)
  org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
  [...]
Caused by: java.lang.NoSuchMethodException: org.assertj.core.api.SoftAssertions.<init>()
  java.lang.Class.getConstructor0(DynamicHub.java:3349)
  java.lang.Class.getConstructor(DynamicHub.java:2151)
  org.assertj.core.api.SoftAssertionsProvider.assertSoftly(SoftAssertionsProvider.java:115)
  [...]
```

## Related Issues

- #1223

## Deliverables

- [ ] Update `AssertJHints` to support soft assertions.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
