### ISSUE TITLE
Migrate `*-agent` samples to Native Build Tools agent support

### ISSUE THREAD

**Issue by sbrannen** [spring-projects-experimental/spring-native#1247]
The `commandlinerunner-agent` sample currently does not work.

At this point we should remove the following...

https://github.com/spring-projects-experimental/spring-native/blob/77be942e39c6c441beb65293d94e9e80de7ccd69/samples/commandlinerunner-agent/pom.xml#L47-L63

and 

https://github.com/spring-projects-experimental/spring-native/blob/77be942e39c6c441beb65293d94e9e80de7ccd69/samples/commandlinerunner-agent/pom.xml#L80

... and switch to using the built-in support for [running with the GraalVM agent](https://graalvm.github.io/native-build-tools/0.9.7.1/maven-plugin.html#agent-support) using Native Build Tools.

**Comment by sbrannen** [comment]
Blocked by:

- https://github.com/graalvm/native-build-tools/issues/162

**Comment by sdeleuze** [comment]
I am not sure to understand why `native-agent` mode configuration [has been removed](https://github.com/spring-projects-experimental/spring-native/commit/0d6cd88ef01caa0f3bd7ab2c82c7c6d5ad96b8de#diff-c49e07941ee78a48d0b48116b91254aad0cc9c200ad0715c583b3fba20828b9eL68), could you please share more about that?

**Comment by sbrannen** [comment]
> I am not sure to understand why `native-agent` mode configuration [has been removed](https://github.com/spring-projects-experimental/spring-native/commit/0d6cd88ef01caa0f3bd7ab2c82c7c6d5ad96b8de#diff-c49e07941ee78a48d0b48116b91254aad0cc9c200ad0715c583b3fba20828b9eL68), could you please share more about that?

Good catch!

That was an experiment that I forgot to undo before committing.

I'll add it back.

**Comment by sdeleuze** [comment]
So far it seems we are blocked by an issue on GraalVM 21.3.

When executing the agent on tests, it generates this kind of entry that make native tests fail:
```
[
  {
    "name":"org.springframework.boot.availability.ApplicationAvailabilityBean",
    "allDeclaredFields":true,
    "queryAllPublicMethods":true
  }
]
```
With this error:
```
java.lang.ClassCastException: sun.reflect.generics.tree.FieldTypeSignature[] cannot be cast to java.lang.reflect.Type[]
       sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getBounds(TypeVariableImpl.java:87)
       com.sun.beans.TypeResolver.erase(TypeResolver.java:242)
       com.sun.beans.TypeResolver.erase(TypeResolver.java:274)
       java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:391)
       java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:118)
```
This error happen when executing native test, native compilation of the app is fine.

Also when using `queryAllPublicMethods` instead of `allPublicMethods`, it works as expected:
```
[
  {
    "name":"org.springframework.boot.availability.ApplicationAvailabilityBean",
    "allDeclaredFields":true,
    "allPublicMethods":true
  }
]
```
We need to bring that to GraalVM team attention. I think that mean we need to move agent support to at least `0.11.1`.

**Comment by sdeleuze** [comment]
Will require NBT 0.9.9 due to https://github.com/graalvm/native-build-tools/issues/179.

**Comment by sdeleuze** [comment]
Blocked by 2 additional issues with NBT `0.9.10`, see https://github.com/sdeleuze/spring-native/commit/test-agent.

**Comment by sdeleuze** [comment]
I created graalvm/native-build-tools#207 and graalvm/native-build-tools#208 related issues.

**Comment by sdeleuze** [comment]
Works with NBT `0.9.12-SNAPSHOT`, `mvn -Pnative -DskipNativeTests package` and the following configuration:
```
<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-agent-config</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<mkdir dir="${project.build.directory}/native/agent-output/main"/>
								<copy todir="${project.build.directory}/native/agent-output/main">
									<fileset dir="${project.build.directory}/native/agent-output/test" />
								</copy>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.experimental</groupId>
				<artifactId>spring-aot-maven-plugin</artifactId>
				<configuration>
					<mode>native-agent</mode>
					<removeSpelSupport>true</removeSpelSupport>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<agent>
						<enabled>true</enabled>
						<options name="test">
							<option>access-filter-file=${basedir}/access-filter.json</option>
						</options>
					</agent>
				</configuration>
			</plugin>
		</plugins>
	</build>
```
I will update the agent samples once NBT 0.9.12 has been released.
