### ISSUE TITLE
JDK 17 support

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-native#1251]
Hi

Does this project support JDK 17? I tried to build native image using the following GraalVM image:  g**hcr.io/graalvm/graalvm-ce:java17-21.3**

And build.gradle:

```

plugins {
     id 'org.springframework.boot' version '2.5.6' apply true
     id 'org.springframework.experimental.aot' version '0.10.5'
     id 'org.graalvm.buildtools.native' version '0.9.7'    
}

apply from: "../gradle-scripts/build-spring-boot.gradle"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")
    { exclude group: "org.springframework.boot", module: "spring-boot-starter" }    
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/release' }
}

springAot {
	removeXmlSupport = true
	removeJmxSupport = true
}

nativeBuild {
	classpath(processAotResources.outputs, compileAotJava.outputs)
}

nativeTest {
	classpath(processAotTestResources.outputs, compileAotTestJava.outputs)
}
```

When I run the command: **gradle nativeBuild** I receive the following error message:

`Execution failed for task ':service:generateAot'.                                                                                                                                            > Unsupported class file major version 61`

**Comment by sdeleuze** [comment]
[Spring Native `0.11.0-M2`](https://github.com/spring-projects-experimental/spring-native/releases/tag/0.11.0-M2) and above support Java 17, not 0.10.x, you can found this information in the support page in the reference documentation.

**Comment by sergey-morenets** [comment]
@sdeleuze Thank you, I will try that.
