### ISSUE TITLE
Document Maven compatibility issues with Native Build Tools

### ISSUE THREAD

**Issue by sbrannen** [spring-projects-experimental/spring-native#1256]
## Overview

See https://github.com/spring-projects-experimental/spring-native/pull/1206#issuecomment-961674277

## Related Issues

- https://github.com/graalvm/native-build-tools/issues/151

**Comment by sdeleuze** [comment]
I think the current "Required with Maven Surefire 2.x" comment in the Maven code snippet of https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native-docs/src/main/asciidoc/getting-started-native-build-tools.adoc#add-the-native-build-tools-plugin bring by 81ac63bb9f9eac37d1973b4e59c361d3ea477026 is good enough.
