### ISSUE TITLE
Update support section of the reference guide

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#1287]
The need to stick to a very specific patch version of Spring Boot is not a strong requirement anymore with the AOT engine. There are probably also a number of entries for starter that are outdated by now. We should probably revisit [the whole section](https://docs.spring.io/spring-native/docs/current-SNAPSHOT/reference/htmlsingle/#support-spring-boot).

**Comment by sdeleuze** [comment]
We still have substitutions of critical classes like `SpringApplication`, so I have mixed feelings about relaxing the documentation of using a specific patch version of Boot. Any thoughts?

I will update the list of starters supported based on the 0.11 changelog and the samples.

**Comment by snicoll** [comment]
> We still have substitutions of critical classes like SpringApplication, so I have mixed feelings about relaxing the documentation of using a specific patch version of Boot.

That is a good point and there's nothing wrong with keeping things as they are if you feel this way, but:

1. I don't expect things like `SpringApplication` being changed any further in patch releases. It could happen and us tracking snapshots and building daily should help us figure out if a recent snapshot broke us or not
2. If we keep this route, we'll have to keep our rigid range on start.spring.io, which means that users are likely to be on snapshots soon.

Updating the list of supported starters is important as we'll have to sync that on start.spring.io. Thanks!

**Comment by sdeleuze** [comment]
I see the value of relaxing a bit our recommendation, I have refined the wording with "Spring Native {version} has been tested against Spring Boot {spring-boot-version}" among other updates, feel free to refine if needed.
