### ISSUE TITLE
spring-aot-maven-plugin don't generate records in the 'target/test-classes/META-INF/native-image/org.springframework.aot/spring-aot/resource-config.json' for 'src/main/resources'

### ISSUE THREAD

**Issue by metlaivan** [spring-projects-experimental/spring-native#1315]
During run test 
` mvn clean -Pnative test`
the spring-aot-maven-plugin don't generate records in the 'target/test-classes/META-INF/native-image/org.springframework.aot/spring-aot/resource-config.json' for resources located in the main space 'src/main/resources'

Versions: 
spring-aot-maven-plugin = 0.10.5
spring-native = 0.10.5
GraalVM = CE 21.2.0
junit-platform-native = 0.9.4

**Comment by sdeleuze** [comment]
Could you please check with `0.11.0-RC1` or `0.11.0-SNAPSHOT` as well?

**Comment by metlaivan** [comment]
Thx a lot. This is fixed in 0.11.0-RC1.
