### ISSUE TITLE
Missing hint for org.hibernate.cfg.beanvalidation.TypeSafeActivator.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-native#1328]
Though the project ([odrotbohm/spring-restbucks](https://github.com/odrotbohm/spring-restbucks/tree/hacking/native-0.11)) does not make use of `javax.validation` within its code there's an error on startup caused by missing reflection configuration for `org.hibernate.cfg.beanvalidation.TypeSafeActivator`.

spring-native: 0.11.0-SNAPSHOT
Branch: [odrotbohm/spring-restbucks/native-0.11](https://github.com/odrotbohm/spring-restbucks/tree/hacking/native-0.11)
Module: server
Additional Required Configuration: [NativeConfiguration.java](https://github.com/odrotbohm/spring-restbucks/blob/hacking/native-0.11/server/src/main/java/org/springsource/restbucks/NativeConfiguration.java#L35)

**Comment by sdeleuze** [comment]
We have [a related hint](https://github.com/spring-projects-experimental/spring-native/blob/d82371b478ad299a788cc19ea91719b866008431/spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaHints.java#L131) which is probably using the wrong trigger or is defined with a too narrow access. Could you refine it based on your findings on this sample?

**Comment by snicoll** [comment]
Closing in favor of #1331
