### ISSUE TITLE
[Question/Feature] Compile Time DI

### ISSUE THREAD

**Issue by voduku** [spring-projects-experimental/spring-native#1335]
Does spring-native come with compile time DI like Dagger 2? If not, will this be added anytime soon as this seems like a very important feature for DI libraries which remove the dependency on reflection.

**Comment by snicoll** [comment]
Compile-time DI is an unrelated concern, really and we don't believe that reflection is such a problem that it should be banned the way you mean. If we ever wanted to support compile-time dependency injection, we'd do that at the core framework level and such a topic [has already been raised](https://github.com/spring-projects/spring-framework/issues/20906) in the past.
