### ISSUE TITLE
Allow to not invoke the test aot task with Gradle

### ISSUE THREAD

**Issue by julb** [spring-projects-experimental/spring-native#1338]
Dear team,

I was thinking that I could be interesting to have an easy way to disable AOT for unit tests.
Indeed, for example, I'm currently building a Spring cloud function and I haveimplemented unit tests as indicated in Spring Cloud Function docs.
I will package this function with Native, but I don't want to tackle the native part for unit tests, the classic unit tests are fine.

In the gradle plugin, [this section](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-aot-gradle-plugin/src/main/java/org/springframework/aot/gradle/SpringAotGradlePlugin.java#L155-L166) enables the aotTest for all tasks of type `Test`. Wouldn't it be good to do that section for GraalVM `nativeTest` task only ?

Also, `aotMain` seems to be run only for `nativeCompile` task so I think it would make sense to do the same for test.

What do you think ?

**Comment by olegz** [comment]
But isn't disabling AOT is as simple as setting VM option `-DspringAot=false`?

**Comment by julb** [comment]
Hello,
Thanks for your feedback.

I tried with:
```
test {
    useJUnitPlatform()
    jvmArgs = ["-DspringAot=false"]
}
```
or using `./gradlew test -DspringAot=false` and it has no effect.

The classpath for unit tests and the system properties are still modified by the plugin.

**Comment by sdeleuze** [comment]
AOT mode for tests is useful for both JVM and native since it allows to ensure that the AOT flavor run fines on JVM (fast feedback loop) before going on native side (slower).

I think for now, AOT generation for test happen unconditionally (IMO not a major issue) and execution of tests in AOT mode (JVM or native) happen if generated test files are detected. I don't think we support `-DspringAot=false` for executing tests in regular mode but I think that could indeed be a good thing to support it.

For disabling native tests, Gradle Native Build Tools plugin allow to disable native tests via:
```
graalvmNative {
    testSupport = false
}
```
Maven Native Build Tools plugin allow to disable native test by removing the `test-native` execution and will support shortly doing that onthe command line via `-DskipNativeTests`, see https://github.com/graalvm/native-build-tools/issues/179.

**Comment by julb** [comment]
Thanks @sdeleuze for this feedback 👍 

In the meantime, if someone else is interested by having a workaround, I did this for now in a `subprojects` block:
 
```
afterEvaluate {
if (project.plugins.hasPlugin('org.springframework.experimental.aot')) {
  generateTestAot.onlyIf { false }
  test.configure { t ->
    t.systemProperties.remove('spring.test.context.default.CacheAwareContextLoaderDelegate')
  }
}
}
```

**Comment by snicoll** [comment]
For the record, this is only a problem with Gradle as far as I can see as Maven has two separate goals and you could decide to include them or not. If I understood correctly, generateTestAot is invoked with no way to disable it? I wouldn't put pressure on fixing this but that looks a little odd to me.

**Comment by sdeleuze** [comment]
> For the record, this is only a problem with Gradle 

I am not sure I agree since with Maven `test` invoke AOT generation and someone could need to execute tests in regular mode without having to modify the `pom.xml`.

**Comment by snicoll** [comment]
Yes but that's not the same problem. I understand there is no easy way to not invoke the test aot task with Gradle. IMO it is a more severe limitations than what you've described.

**Comment by bclozel** [comment]
It is the way it is right now because we initially decided to make it the default.
But we could create a new `aotTest` task that depends on `check`.

**Comment by sdeleuze** [comment]
I renamed this issue to clarify it is about allowing to not invoke the test aot task with Gradle, and created #1356 about providing a way to use regular codepath for test execution.

**Comment by haroldlbrown** [comment]
For us, disabling AOT in Gradle for tests would also be beneficial.
We use `MockBean`s in our Spring integration tests. `MockBean` is currently not supported in AOT.
So disabling AOT would help us in not having to rewrite our Spring integration tests.
