### ISSUE TITLE
Add spring-cloud-starter-sleuth support

### ISSUE THREAD

**Issue by gabac** [spring-projects-experimental/spring-native#135]
Bit unsure if this is a bug with the `spring-graalvm-native` or just a misconfiguration on my side

After some tinkering I did get my app running but I had to remove some dependencies.

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-logging</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-trace</artifactId>
		</dependency>
```

If I try to compile my app with them I get following exception

```
Fatal error:org.springframework.graal.type.MissingTypeException: Unable to find class file for org/springframework/cloud/openfeign/FeignAutoConfiguration
	at org.springframework.graal.type.TypeSystem.resolveSlashed(TypeSystem.java:161)
	at org.springframework.graal.type.TypeSystem.resolve(TypeSystem.java:193)
	at org.springframework.graal.type.TypeSystem.resolve(TypeSystem.java:197)
	at org.springframework.graal.type.TypeSystem.Lresolve(TypeSystem.java:201)
	at org.springframework.graal.type.Type.getAutoConfigureBeforeOrAfter(Type.java:1313)
	at org.springframework.graal.support.ResourcesHandler.processType(ResourcesHandler.java:934)
	at org.springframework.graal.support.ResourcesHandler.processType(ResourcesHandler.java:729)
	at org.springframework.graal.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:724)
	at org.springframework.graal.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:658)
	at org.springframework.graal.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:495)
	at org.springframework.graal.support.ResourcesHandler.register(ResourcesHandler.java:117)
	at org.springframework.graal.support.SpringFeature.beforeAnalysis(SpringFeature.java:79)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)
```

Is this really an issue with `spring-graalvm-native` and therefor its correct to post that here? If not, sorry about this! But if someone has some hints for me how to get the configuration right I would be very grateful 😆

**Comment by garc33** [comment]
Get the same issue just by adding ‘ org.springframework.cloud: spring-cloud-starter-sleuth’ in my classpath

**Comment by spencergibb** [comment]
There has been no work done for any spring-cloud project and spring-graalvm-native

**Comment by aclement** [comment]
Do you by any chance have a sample project we could include in our samples directory that demonstrates the typical use case? Given that we have no samples for Spring cloud, not totally surprised it doesn't work. You could, in the interim, try with the agent, as per https://repo.spring.io/snapshot/org/springframework/experimental/spring-graal-native-docs/0.6.0.BUILD-SNAPSHOT/spring-graal-native-docs-0.6.0.BUILD-SNAPSHOT.zip!/reference/index.html#hybrid (recognizing those docs are a little out of date - 0.7.0 is due very soon).

**Comment by gabac** [comment]
@aclement I did try it already with the agent but was not successful. But most likely I haven't fully figured out anything. The comment of you @spencergibb matched my expectation, that so far no work has been done in the spring-cloud project. I guess my best chance is the agent 👍 

I can create a sample project but actually just the dependency as such is enough to create the desired behaviour. Do you still want me to create one?

**Comment by aclement** [comment]
If just adding the dependency is enough I'll try it out.

**Comment by aclement** [comment]
I find when I add
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
```

to the springmvc-tomcat sample we have in the repository (no other changes) it will fail to compile with the feature, but works fine with the agent. It looks like a GraalVM analysis issue (where it is not coping with something missing at analysis time which it should) - might raise an issue against them for that. For the agent scenario, it just works.

Did you get a different error when trying with the agent or the same thing as with the feature?

I think I will need a basic repro project because right now I can't see the error you are seeing in either of my variants.

**Comment by aclement** [comment]
I've raised https://github.com/oracle/graal/issues/2529 which I think is the failing on missing type error (my missing type error, not the FeignAutoConfiguration one shown above)

**Comment by aclement** [comment]
Although I can't recreate it, i can fix that FeignAutoConfiguration problem I think, so I have put that change in. Doesn't mean a spring cloud app will work, but it may get further.

**Comment by gabac** [comment]
@aclement I created a sample repo for you to showcase how to reproduce the error
https://github.com/gabac/graalvm_missing_type_openfeign

Thanks a lot for raising the issue with graal!

**Comment by aclement** [comment]
Thanks for the test project.  I could build it and hit the original FeignAutoConfiguration issue. It is using 0.7.0.BUILD-SNAPSHOT version number but I see it is using the old artifact ID of spring-graal-native, the project recently transitioned to spring-graalvm-native. The former will still work for 0.7.0 snapshots but won't be picking up recent fixes.  When I switched it to the new artifact id it picked up my fix, got further then hit the problem I raised with the graal team.

I then switched over to working with the agent - this looked more promising but unfortunately it looks like a bit of spring cloud infrastructure hasn't adopted `proxyBeanMethods=false`:
```
org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [org.springframework.cloud.sleuth.instrument.reactor.TraceReactorAutoConfiguration$TraceReactorConfiguration$HooksRefresherConfiguration]
```
@spencergibb looks like we need to take a pass over spring cloud and do what we can to make those configurations compatible, don't know if this is the only one or not.

**Comment by spencergibb** [comment]
We did do that, but possibly missed some.

**Comment by spencergibb** [comment]
@marcingrzejszczak

**Comment by gabac** [comment]
I updated the sample repo accordingly.

**Comment by sdeleuze** [comment]
@gabac `spring-cloud-starter-sleuth` support was improved after your last comment, could you try with the new 0.8.2 I will release today ?

**Comment by gabac** [comment]
@sdeleuze Sure thing 👍

**Comment by sdeleuze** [comment]
There is a need for working properly on Sleuth support since the outdated supported has recently been removed.

**Comment by marcingrzejszczak** [comment]
> There is a need for working properly on Sleuth support since the outdated supported has recently been removed.

What do you mean exactly?

**Comment by sdeleuze** [comment]
A partial Sleuth support was added and tested in the `wavefront` sample, but we decided to use only metrics one because such support increased too much the footprint and was not properly designed and tested (I have no Sleuth knowledge myself).

During latest upgrade to Spring Cloud 2020.0.0, I figured out that a lot of configuration classes has been refactored and that was not tested, so I preferred to remove that broken support temporarily as part of https://github.com/spring-projects-experimental/spring-native/commit/881311819ca73671c57caa8fea438371c9282733.

We can probably discuss this topic and Spring Cloud team involvement in `spring-native` next week during our weekly meeting.

**Comment by marcingrzejszczak** [comment]
cc @jonatan-ivanov

**Comment by AndersClausen** [comment]
Hi @sdeleuze @marcingrzejszczak @Jonatan-ivanov. Just curious to know if this is being worked on or not, as I'm heavily depended on Sleuth working with spring-native.
Also, is there anything that I can help with on this issue or is it purely an in-house thing?
Appreciate all your work.

**Comment by marcingrzejszczak** [comment]
@AndersClausen please check https://github.com/spring-projects-experimental/spring-native/pull/614
