### ISSUE TITLE
org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module

### ISSUE THREAD

**Issue by ahmedeldeeb25** [spring-projects-experimental/spring-native#1352]
I have created a simple spring boot app and added spring-web and spring-native dependencies.
when I'm trying to build the native image with `mvn clean package spring-boot:build-image `, I have this error

```
[INFO]     [creator]     The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.

[INFO]     [creator]     Error: Image build request failed with exit status 137
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 137
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

**Comment by sdeleuze** [comment]
Likely not the source of the error (see the `INFO` level), more likely memory configuration issue, see https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_out_of_memory_error_when_building_the_native_image.

About removing this message, the native config is provided by Tomcat itself so worth to submit a PR in https://github.com/apache/tomcat/pulls to fix this if you can.
