### ISSUE TITLE
Windows Defender is flagging GraalVM's svm.jar during build on windows

### ISSUE THREAD

**Issue by Anu-cool-007** [spring-projects-experimental/spring-native#1364]
When running the command: `mvnw -Pnative clean package` Windows defender quarantines the svm.jar present in the directory **..\graalvm-ce-java17-21.3.0\lib\svm\builder\**

The step was the execution of 
..\graalvm-ce-java17-21.3.0\bin\native-image.cmd -cp ...

![image](https://user-images.githubusercontent.com/16525919/145527230-70238182-79c2-4e63-92f2-090f1f377df2.png)

I had to mark the file as safe in order to complete the process and not get the 'Path Entry not readable' error

**Comment by sdeleuze** [comment]
Please report this issue on https://github.com/oracle/graal/issues instead.
