### ISSUE TITLE
spring-data-jpa @EnableJpaRepositories not supported?

### ISSUE THREAD

**Issue by liupengpop** [spring-projects-experimental/spring-native#1368]
@EnableJpaRepositories(repositoryBaseClass = MyJpaRepository.class)
not supported?

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for com.test.MyJpaRepository is missing.

Action:

Native configuration for a class accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

**Comment by snicoll** [comment]
@liupengpop it is hard to give you support with this level of details. Spring Data JPA is supported. You haven't shared which version of Spring Native you're using or what your setup looks like. For us to be able to help you, we'd need that information.
