### ISSUE TITLE
Regression in ClientHttpRequestFactoryHints

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1370]
**Intro**
Two Nativehints that where fixed in previous Versions of Spring native,
are broken again in native11.
I was able to get everything working by readding the Typehints again, with the now changed "TypeAccess"
My proposal might by a bit verbose, but the DEFAULT does not work
Would be nice if these are fixed in 11 again

**setConnectionTimeout**
https://github.com/spring-projects-experimental/spring-native/issues/954
=> 
@TypeHint(types = org.springframework.http.client.SimpleClientHttpRequestFactory.class, access = {TypeAccess.DECLARED_CLASSES, TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_METHODS})

**Support for EntityListeners**
https://github.com/spring-projects-experimental/spring-native/issues/869
=> 
@TypeHint(types = AuditJpaListener.class, access = {TypeAccess.DECLARED_CLASSES, TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_METHODS})
=> This is of course specific to my Class, don't know how the generic fix would like

Demo Branch
https://github.com/goafabric/person-service/tree/native-11-github

**Comment by sdeleuze** [comment]
I focus this issue on fixing the regression in `ClientHttpRequestFactoryHints`, I think the other issue may be covered by #1371.
