### ISSUE TITLE
Injection of EntityManager not working since 0.11 final

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1372]
The Injection of EntityManager does not work since the final Version 0.11

A simple 
@Autowired EntityManager entityManager;

Now results in the exception below.

Can be mitigated by adding an 
@Qualifier("org.springframework.orm.jpa.SharedEntityManagerCreator#0")
but besides beeing a hack .. this crashes in normal JVM mode.

So in native mode 2 Entitymanager seems to get created.
I am using complete Autoconfiguration here and Spring Data Repositories

-- cut ---
Unsatisfied dependency expressed through field 'entityManager'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'javax.persistence.EntityManager' available: more than one 'primary' bean found among candidates: [org.springframework.orm.jpa.SharedEntityManagerCreator#0, org.springframework.orm.jpa.SharedEntityManagerCreator#1]

**Comment by snicoll** [comment]
@goafabric you'll have to share a sample I am afraid rather than code snippet like this. Please do so as a zip attached to this issue or a link to a GitHub repository.

**Comment by liupengpop** [comment]
@PersistenceContext
	private EntityManager entityManager;

**Comment by goafabric** [comment]
@snicoll 
thx 4 your fast reply and looking so fast into the other tickets
its basically the same github as inside the other tickets:
https://github.com/goafabric/person-service/tree/native-11-github

But basically its really simple .. the class is AuditJPAListener . which is a dirty class and also the problem of the other tickets.
And it may be currently disabled because of these

But it doesnt matter . injecting EntitManager in any other class also does not work ... so i think its more of a general thing

**Comment by goafabric** [comment]
@liupengpop 
thx 4 your hint .. this actually seems to work ..
so this means i have been doing this all wrong for ages now ?

@snicoll 
liupengpop hint worked .. don't know what is the expected behaviour here
works for me, it's up to you how to deal with the ticket

**Comment by sdeleuze** [comment]
I will try to extract a minimal repro.

**Comment by sdeleuze** [comment]
I think `@Autowired EntityManager entityManager` only works with `@EnableJpaRepositories` and I have not seen the latter in your sample (where `@PersistenceContext EntityManager entityManager` works as expected). As a consequence, I close this issue, if `@Autowired EntityManager entityManager` + `@EnableJpaRepositories` works on the JVM but not on native please comment with a minimal reproducer and we will reopen.
