### ISSUE TITLE
Spring Security OAuth endpoint not available when native app

### ISSUE THREAD

**Issue by mraible** [spring-projects-experimental/spring-native#1375]
I'm updating my JHipster examples to use Spring Native 0.11.0. I've found that when I have Spring Security OAuth integrated, it works fine in JVM mode, but not in native mode. The `http://localhost:8080/oauth2/authorization/oidc` results in a 404 in native mode. Or rather, the forwarding mechanism to this endpoint doesn't work.

Steps to reproduce:

```
git clone -b spring-native-0.11 https://github.com/mraible/spring-native-examples.git
cd spring-native-examples/angular-webflux
# Start Keycloak
docker-compose -f src/main/docker/keycloak.yml up -d
./mvnw -Pwebapp 
```

You should be able to log in at http://localhost:8080. When you click sign-in, it'll redirect you to `http://localhost:8080/oauth2/authorization/oidc`. Login with admin/admin and you'll be redirected back to the app.

Then, package it as a native app:

```
./mvnw package -Pwebapp,native -DskipTests
```

Run it:

```
./target/ngflux
```

Try to log in at `http://localhost:8080` and you'll get a 404.

**Comment by mraible** [comment]
@joshlong and I were able to figure this out with the help of Steve Riesenberg. It was caused by having a `SpaWebFilter` with a `@Component` annotation. We were also manually configuring it in JHipster's `SecurityConfiguration`:

```java
.addFilterAt(new SpaWebFilter(), SecurityWebFiltersOrder.AUTHENTICATION)
```

Removing the `@Component` annotation makes it work the same in JVM and native mode.

**Comment by sdeleuze** [comment]
Thanks for your feedback. As I read [this](https://github.com/mraible/spring-native-examples/commit/993d143506fab88586e66a06f95ff057244592c9#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R242) my understanding of the issue when using `@Component` is that it is on JHipster side, so I will close this issue. Please comment otherwise.
