### ISSUE TITLE
ConditionalyProperties (of Spring Sleuth) resolved during build time

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1380]
So this is more of a question ... but the type question is not available here.
From one of the recent blog posts i understand that @ConditionalProperty is now resolved during build time.
Which is not my favorite behaviour, but en par with with Quarkus does.

This of course yields to the situation that i cannot enable things, during runtime, that where disabled during build.

Not a big deal for my own Configuration classes, i just Replaced the ConditionalProperty by an if condition.

But the problem is now with ConditionalProperties managed by spring like:

spring.sleuth.enabled: false
spring.zipkin.enabled: false

During DEV time i don't have Zipkin available, so i reenable this during deploy time in Kubernetes.

I could just always enable the properties, but this yields to a lot of exceptions when Zipkin/Jaeger is not there.

=> The next best option would, to explictly enabled these properties during the native build.

But I could not find in the documentation where to put these.
Neither near the spring boot maven plugin.
Nor <BP_NATIVE_IMAGE_BUILD_ARGUMENTS> ...

A small advice with a code snippet would be appreciated.

thx

**Comment by sdeleuze** [comment]
Relates to #764, discussing that with the team and will provide a feedback later.
