### ISSUE TITLE
Regression in 0.11.0 - Prometheus Actuator endpoint not registered

### ISSUE THREAD

**Issue by prettymama** [spring-projects-experimental/spring-native#1382]
After updating to 0.11.0 (from 0.10.5), the Prometheus Actuator endpoint ceased to be registered and is not available in native-image. The Health endpoint, for example, is still functional. Seems to be a regression from #423, where it has been fixed.

**Comment by snicoll** [comment]
@prettymama thanks for the report. 0.11 is very different from 0.10.5. Have you made sure that the endpoint is enabled in the configuration that is used at build time. See [this section](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#spring-aot-bean-factory-preparation) in particular.

If that is the case, please share a small sample that reproduces the problem.

**Comment by goafabric** [comment]
@prettymama 
are you sure that it's not working ? 
despite some changes in 0.11 that where already mentioned,
prometheus still works for me as expected with native.

my setup:
- spring boot 2.6.1
- native 11.0
- ...web.expure.include: ""health,prometheus"
- dependency
   <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>

**Comment by prettymama** [comment]
@snicoll, @goafabric thanks to both for your feedback. I played around with it in the meantime and I believe I found the problem: my configuration resides in application.yml and this file is not on the classpath, but it is externalized and located in a directory called config. Normally, the application picks it up on startup (doesn't matter if JVM based or native-image based), however the file is not picked by spring-aot during the build. If I move the config file inside the classpath, it works. Thing is I need the configuration outside tha native-image.

**Comment by goafabric** [comment]
@prettymama could be .. as i mentioned i also encountered some changes, that properties from application.yaml are now resolved during compile time .. the same way that quarkus does it for some ...
i had this change with spring-sleuth 
but i think the spring guys here can explain better

**Comment by prettymama** [comment]
So I ended up splitting my configuration into 2 parts: the crucial ones (basically 3rd party endpoints configuration) are placed externally and the ones needed during the build time (metrics etc.) are in the classpath. That's sufficient enough for me.

@snicoll and @goafabric thanks again for pointing me in the right direction.
