### ISSUE TITLE
Review Spring Security hints for servlet

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1392]
After having a look on a footprint regression between `0.11.0-RC1` and `0.11.0-0`, I am wondering if full public method reflection is needed for `HttpServletRequestWrapper`, `ServletRequestWrapper` and `ServletRequest`. See [related hints](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native-configuration/src/main/java/org/springframework/security/config/annotation/web/configuration/WebMvcSecurityHints.java#L37-L42).

**Comment by eleftherias** [comment]
You are right @sdeleuze, I don't believe those hints are needed anymore. Please see PR #1418.
