### ISSUE TITLE
Find how to avoid "No auto configuration classes found in META-INF/spring.factories" error in IntelliJ IDEA

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1395]
Seems to happen when:
 - Both main and test generated sources/resources/classes are present in Maven projects
 - The app is ran without `-DspringAot=true`

Based on my test with IDEA 2021.3, when I run `CommandLineRunnerApplication` in the `commandlinerunner` sample, `ClassUtils.isPresent("org.springframework.aot.TestContextBootstrapInitializer", null)` return `true`, leading to `AotModeDetector#isRunningAotTests` returning `true` as well and triggering the wrong codepath in `SpringFactoriesLoader#loadFactories`.

Even `ClassUtils.isPresent("org.junit.jupiter.api.Test", null)` return `true` so it seems test and main classpath are mixed. Not sure how yet of the scope of this issue.

**Comment by snicoll** [comment]
If the test classpath is present when running a main app, this is a bug that should be reported to Jetbrains.

**Comment by sdeleuze** [comment]
I can't reproduce anymore, I updated IDEA in the meantime, so maybe that was indeed just an IDEA bug.

**Comment by sdeleuze** [comment]
I continue to happen in IDEA, that's really and IDEA bug, but I have find a nice way to avoid it.
