### ISSUE TITLE
Is there a more detailed document for Native Hints？

### ISSUE THREAD

**Issue by AngryApe** [spring-projects-experimental/spring-native#1409]
I need to build a standalone native image for windows user(.exe), so I add an embedded version postgresql [dependency](https://github.com/yandex-qatools/postgresql-embedded), but the image throw an Exception and start failed. I wanna add some Native Hints annotation to support `embedded postgresql`, the Spring Native document about Hints is too simple, I can't get enough information about how should I config the Hints. So, as the title said, is there a more detailed document for Native Hints？

**Comment by sdeleuze** [comment]
Native hints mostly share the same semantics than GraalVM native configuration, so you will find more details when clicking in the related links at the beginning of https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints. They point to the related GraalVM native configuration documentation which is not as complete as I would wish, but for now this is what we have.

Crafting native hints can be hard, we are collaborating with the GraalVM team to provide a dedicated repository and easier way to add support for JVM libraries, we will share more about that in a few weeks/months.
