### ISSUE TITLE
Document that beans defined in a profile aren't picked at runtime unless the profile is enabled when AOT runs

### ISSUE THREAD

**Issue by jamesward** [spring-projects-experimental/spring-native#1411]
If I have:
```kotlin
@Component
@Profile("init")
class InitCommand : CommandLineRunner {
    override fun run(vararg args: String?) {
        println("run")
    }
}
```

It works as expected when the profile is `init` on the JVM but does not run as a Spring Native executable.

Reproducible project: https://github.com/jamesward/spring-native-cli

**Comment by snicoll** [comment]
@jamesward the profile must be enabled at build time so that AOT pre-process the context at build time. We could make that more clear in the doc that mentions the environment and conditions already.

**Comment by jamesward** [comment]
Ah. That makes sense. So do I just set the enabled profiles in my AOT Gradle task?

**Comment by jamesward** [comment]
It appears I can do:
```
tasks.withType<org.springframework.aot.gradle.tasks.GenerateAotSources> {
    systemProperty("spring.profiles.active", "init")
}
```

**Comment by snicoll** [comment]
IMO, using profiles with Spring Native doesn't make much sense at this point. Once the profile is enabled at build time, it will unconditionally be enabled at runtime as well (since the context was pre-processed for that particular arrangement). That makes it quite useless.

If you have an app and want to keep the flexibility the JVM has to offer, then you could configure the build plugin (we should make that easier, see #764). If you don't then stop using profiles or enabling them in `application.properties` directly could be more straightforward.

**Comment by jamesward** [comment]
Haha - I just discovered that. :)

I was using profiles for conditional behavior (if there is an `init` arg, run a command line app to init the db schema, otherwise start the web server).  And you are right that in the world of AOT, this won't work.  I've switched to using properties instead.  Thanks for your help!

**Comment by jamesward** [comment]
It appears that `@ConditionalOnProperty` has the same behavior as `@Profile` (it depends on the property as set during AOT).  So I'm still trying to find a way to do what I need.

**Comment by jamesward** [comment]
I ended up doing a runtime check:
```
@Component
class InitDB : CommandLineRunner {
    override fun run(vararg args: String?) {
        if (args.contains("init")) {
            // do it
        }
    }
}
```

**Comment by sdeleuze** [comment]
Related to #764.

**Comment by snicoll** [comment]
@jamesward irrespective of Spring Native, the use case you've described is best implemented using the `CommandLineRunner` you've shared (prefer `ApplicationRunner` as it provides a higher-level contract for arguments).
