### ISSUE TITLE
Class com.ecwid.consul.v1.kv.model.GetValue is instantiated reflectively but was never registered

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-native#1430]
Hi

We have Spring Boot application that uses Spring Cloud Config Consul. We added Spring Native plugin (for Gradle) and managed to build GraalVM native image however when we run the application we get the following exception:

Caused by: java.lang.IllegalArgumentException: Class com.ecwid.consul.v1.kv.model.GetValue is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
	at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.hubErrorStub(SubstrateAllocationSnippets.java:258)
	at sun.misc.Unsafe.allocateInstance(Unsafe.java:864)
	... 43 common frames omitted

JDK: 17.0.1
GraalVM: 21.3.0
Spring Boot: 2.6.2
Spring Native: 0.11.1
Spring Cloud: 2021.0.0

**Comment by sergey-morenets** [comment]
Can be resolved by this explicit configuration:

```
@Configuration
@TypeHint(types = GetValue.class, access = {TypeAccess.PUBLIC_CONSTRUCTORS, TypeAccess.PUBLIC_METHODS, TypeAccess.PUBLIC_FIELDS,
		TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_FIELDS, TypeAccess.DECLARED_METHODS})
public class AotConfig {
}

```

**Comment by sdeleuze** [comment]
@OlgaMaciaszek Should we include that in Spring Cloud hints from your POV?

**Comment by OlgaMaciaszek** [comment]
@sergey-morenets thanks for reporting this. Veryfying.

**Comment by sdeleuze** [comment]
Closing due to lack of feedback.

**Comment by OlgaMaciaszek** [comment]
@sergey-morenets, @sdeleuze after further analysis, I was able to reproduce this.

**Comment by OlgaMaciaszek** [comment]
Will add the necessary hints.
