### ISSUE TITLE
@SerializationHint declaration is not taken into account

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-native#1435]
Hi

We tried to use @SerializationHint annotation in our project:

```
public record Person(String name, String sirName) 
		implements Serializable {
}

@Configuration
@SerializationHint(types = Person.class)
public class AotConfig {
}

```
However when we execute goal _mvn spring-aot:generate_ **serialization-config.json** file is not created and Person type is not included anywhere in target\generated-sources\spring-aot\src\main\resources\META-INF\native-image\org.springframework.aot\spring-aot\ folder.

Spring Native: 0.11.1
Spring AOT plugin 0.11.1
Spring Boot: 2.6.2
GraalVM: 21.3.0

**Comment by ttddyy** [comment]
I think this commit(https://github.com/spring-projects-experimental/spring-native/commit/98c58db43323272595215543ae8ad2c31b572ad9) and associated gh-593 would explain the background.

**Comment by sergey-morenets** [comment]
Thank you for the explanation, @aclement 
However would be more convenient to compile the code automatically if someone execute mvn spring-aot:generate?

**Comment by sdeleuze** [comment]
I think this is a Maven limitation we can't really change.

@bclozel Could you please confirm?

**Comment by bclozel** [comment]
Yes, as @ttddyy said, this is explained in https://github.com/spring-projects-experimental/spring-native/issues/593#issuecomment-802653446

I think we can close this issue as there's nothing we can do about this. The goal should not be called manually in the first place.
