### ISSUE TITLE
HOWTO add arguments as System variable to command line in generated image

### ISSUE THREAD

**Issue by neoludo** [spring-projects-experimental/spring-native#1438]
Hi,

I didn't find in documentation the way to add arguments to the process launched in generated dockerized native image.

Thanks in advance for your help
Ludovic

**Comment by sdeleuze** [comment]
@dmikusa-pivotal Is it supported? If not should an issue be created in https://github.com/paketo-buildpacks/native-image or somewhere else?

**Comment by dmikusa-pivotal** [comment]
I believe you'd want these instructions: https://buildpacks.io/docs/app-developer-guide/run-an-app/#default-process-type-with-additional-arguments
