### ISSUE TITLE
cloud-function-aws what should the aws handler class name/method name be

### ISSUE THREAD

**Issue by johnlongo** [spring-projects-experimental/spring-native#1445]
I'm new to spring native. When I upload the zip that's produced by the build script to aws what class/method name should I supply in the aws lambda console. I know this a newbe question so let me say thank you in advance for any help.

currently I have org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest, but when I run a test it tells me the class was not found.

![image](https://user-images.githubusercontent.com/23619505/149134334-2d84be83-c3ed-4cf0-a6ad-d924f682214a.png)

![image](https://user-images.githubusercontent.com/23619505/149134551-1e024738-698a-490a-909c-76c2402cad28.png)

**Comment by sdeleuze** [comment]
See https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws#deploy-and-test.
