### ISSUE TITLE
Proxy when mvn spring-boot:build-image

### ISSUE THREAD

**Issue by chatchaisi** [spring-projects-experimental/spring-native#1450]
My server under proxy. After run command "MVN spring-boot:build-image" I got time out. 
But My labtop not in proxy can use command normally.

Please help me slove this. Thank you

I alerady set proxy in docker user/.docker/config.json

[INFO]     [creator]       BellSoft Liberica NIK 11.0.13: Contributing to layer
[INFO]     [creator]         Downloading from https://download.bell-sw.com/vm/21.3.0/bellsoft-liberica-vm-core-openjdk11-21.3.0-linux-amd64.tar.gz
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency native-image-svm
[INFO]     [creator]     unable to download https://download.bell-sw.com/vm/21.3.0/bellsoft-liberica-vm-core-openjdk11-21.3.0-linux-amd64.tar.gz
[INFO]     [creator]     unable to request https://download.bell-sw.com/vm/21.3.0/bellsoft-liberica-vm-core-openjdk11-21.3.0-linux-amd64.tar.gz
[INFO]     [creator]     Get "https://download.bell-sw.com/vm/21.3.0/bellsoft-liberica-vm-core-openjdk11-21.3.0-linux-amd64.tar.gz": dial tcp 104.18.0.179:443: connect: connection timed out
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:58 min
[INFO] Finished at: 2022-01-14T15:38:37+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.6.2:build-image (default-cli) on project demo: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.6.2:build-image failed: Builder lifecycle 'creator' failed with status code 145 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by sdeleuze** [comment]
Probably related to proxy configuration described in https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.examples.builder-configuration and not related to Spring Native itself.

**Comment by chatchaisi** [comment]
> Probably related to proxy configuration described in https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.examples.builder-configuration and not related to Spring Native itself.

Thank you.
