### ISSUE TITLE
Update environment handling in "AotSpringBootConfigContextLoader"

### ISSUE THREAD

**Issue by ttddyy** [spring-projects-experimental/spring-native#1453]
These commits in Boot (by @philwebb) impact the `Environment` handlings in `AotSpringBootConfigContextLoader`.

- spring-projects/spring-boot#29404
- spring-projects/spring-boot#29405
- clean up commit: https://github.com/spring-projects/spring-boot/commit/9c481952d8081827ef04511154b27afbc454b0c4

**Comment by sdeleuze** [comment]
Thanks for your feedback @ttddyy, closing this one since no immediate actionable item and no milestone created for a Spring Boot 2.7 baseline yet so we will do an extensive review when we will upgrade as pointed out by @snicoll.
