### ISSUE TITLE
SimpleMongoRepository - No suitable constructor found

### ISSUE THREAD

**Issue by bitbaggi** [spring-projects-experimental/spring-native#1457]
Hey everyone,

i have an default spring boot native project.

**This is my build.gradle:** (Have to attach it as txt because github not wants .gradle files)
[build.txt](https://github.com/spring-projects-experimental/spring-native/files/7882254/build.txt)

I have only one dataRepository for my dto Person.
Person.java
```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Person {
    public String firstName;
    public String lastName;
}
```
PersonRepository.java
```
public interface PersonRepository extends MongoRepository<Person, String> {
}
```

When i start the service in IntelliJ, all things seems good, service is starte, swagger and endpoints are reachable...

But when i build the service with gradle bootBuildImage and starts it with my local docker, there an exception occures.

`
No suitable constructor found on class org.springframework.data.mongodb.repository.support.SimpleMongoRepository to match the given arguments: org.springframework.data.mongodb.repository.support.MappingMongoEntityInformation, org.springframework.data.mongodb.core.MongoTemplate. Make sure you implement a constructor taking these
`

Did i anyting wrong?, or is there a bug with mongoTemplate?

**Comment by snicoll** [comment]
@bitbaggi it is very hard to say. We don't need your build file but rather a small sample we can run ourselves. You can share it with us by attaching a zip to this issue or sharing a link to a GitHub repo.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
