### ISSUE TITLE
Mutli-module maven project

### ISSUE THREAD

**Issue by thahgr** [spring-projects-experimental/spring-native#1471]
Hi, 

I have a multi-module maven project, one parent three modules, only one of them has a main class annotated with @SpringBootApplication. 

I am following the guide https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-buildpacks
I have been able to build correctly with mvn spring-boot:build-image but it creates a separate image for each module. The same with jars, one jar for each module.

How can i proceed to pack everything into one image? 

Thanks

**Comment by bclozel** [comment]
You can take a look at the [multi-modules samples](https://github.com/spring-projects-experimental/spring-native/tree/main/samples/multi-modules). Just like any Spring Boot project, the Spring Boot plugin and the native plugin should only be applied on the module that builds the actual application. Other modules should only apply the dependency management.

**Comment by thahgr** [comment]
ok thanks
