### ISSUE TITLE
Extend the Spring Native reference with a sample Dockerfile for native images built with Native Build Tools

### ISSUE THREAD

**Issue by haroldlbrown** [spring-projects-experimental/spring-native#1477]
There is an [official guide for how to containerize a Spring Boot application](https://spring.io/guides/gs/spring-boot-docker/).

It would be nice if there was a guide in the [Spring Native reference](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#overview) for how to write an appropriate `Dockerfile` when Native Build Tools are used.

When the [Getting started with Buildpacks section](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-buildpacks) is followed, one ends up with a functioning OCI image.
When the [Getting started with Native Build Tools](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-build-tools) section is followed, one ends up only with a GraalVM Native Image binary.
It would be nice if both sections finish with an OCI image.

**Comment by sdeleuze** [comment]
Hi thanks for this proposal, but for now on Spring Native side, we prefer to focus on more critical tasks.

**Comment by rafaribe** [comment]
Would be awesome if someone could provide an example, I've gave it a shot but didn't work so far.
