### ISSUE TITLE
Support for minikube or docker daemon alternative?

### ISSUE THREAD

**Issue by colin-riddell** [spring-projects-experimental/spring-native#1479]
Apologies if this is not the correct place to ask this question.

With many teams moving away from docker entirely due to the recent changes to docker desktop - will spring-native support a container runtime other than docker? If not - are there any recommended ways of working around this to use a non-docker container runtime?

Thanks

**Comment by scottfrederick** [comment]
Spring Native uses the Spring Boot build plugins for building Docker images. Spring Boot supports using minikube with the [Maven](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.docker-daemon) or [Gradle](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#build-image.docker-daemon) plugin. Other Docker-compatible daemons might work in the same way.

**Comment by sdeleuze** [comment]
Thanks for your feedback @scottfrederick.
