### ISSUE TITLE
Refine logback support

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#1505]
I've been trying to get logback to behave using the workaround guides. I couldn't get the custom configurator to be found at all, so I tried the option to supply the xml file from outside of the image when you launch it.

However, when I tried to do that I get a stack trace that complains about the file I'm supplying from outside:

```
./server/target/server -Dlogging.config=logback-spring.xml

Caused by: ch.qos.logback.core.LogbackException: Logback XML configuration is not supported yet, see https://github.com/spring-projects-experimental/spring-native/issues/625 (detected file: file:/Users/aclement/gits/project/logback-spring.xml)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:46)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:191)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:165)
	... 22 more
```

(Note here I added to the message text in the substitution so it would tell me which XML file it was having trouble with). I had to turn off the substitution in order for this mechanism to work and when I did turn it off, it did work (externally supplied logback config).

I wonder if the substitution could be looking at that property to determine whether it should fail. (if the URL doesn't end with the value of `System.getProperty("logging.config")` or something) because just 'turning it off' perhaps fails too extreme.

(We could perhaps do with a sample that shows how to really use the external configurator solution)

**Comment by aclement** [comment]
I've removed the substitution that is producing this message. Maybe it needs re-adding but it needs some work and it preventing my app from getting anywhere. Without the substitution my app will accept external logback configuration via `-Dlogging.config=logback-spring.xml` *OR* logback configuration is working fine if the `logback-spring.xml` is inside the project. Perhaps it is the simplicity of the config in my situation, but it does just work (obviously with the setting in the build file that ensures we don't remove XML support). This is the logback config:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml" />
    <include resource="org/springframework/boot/logging/logback/file-appender.xml" />
    <root level="DEBUG">
        <appender-ref ref="FILE" />
    </root>
</configuration>%
```

**Comment by sdeleuze** [comment]
Embedded `logback-spring.xml` looks like an interesting option, I will experiment and refine that.
