### ISSUE TITLE
Validation does not work while using spring-cloud-function and kotlin

### ISSUE THREAD

**Issue by FalkWoldmann6232** [spring-projects-experimental/spring-native#1508]
I am trying to deploy a native spring cloud function while using Kotlin as a lambda.

My function looks like this:
```
@Component
class NameUppercaser(private val validator: Validator) : Consumer<String> {
    override fun accept(inputS: String) {

        val mapper = jacksonObjectMapper().registerModule(JavaTimeModule()).enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

        val snsEvent = mapper.readValue<SNSEvent>(inputS)

        snsEvent.records.forEach { record ->
            val event = mapper.readValue<Message>(record.sns.message)
            val violations = validator.validate(event)
            println(violations) // == []



        }
    }
}

data class SNSEvent(
    @JsonProperty("Records")
    val records: List<Record>,
)

data class Record(
    @JsonProperty("Sns")
    val sns: SNS,
)

data class SNS(
    @JsonProperty("Message")
    val message: String,
)

data class Message(
    @JsonProperty("data")
    @get:Valid
    val data: TestEventData
    )


data class TestEventData(
    @get:Pattern(regexp = "[0-9a-f]{1,100}")
    @JsonProperty("eventId")
    val eventId: String,
)
```

When sending an invalid eventId, the list of violations will still be empty. The following message will be logged: `ocalVariableTableParameterNameDiscoverer : Cannot find '.class' file for class [class java.lang.Object] - unable to determine constructor/method parameter names`.

I added the following native hints: `@TypeHint(types = [SNSEvent::class, Record::class, SNS::class, Message::class, TestEventData::class, Valid::class, Pattern::class, Min::class, Max::class, Object::class])`.

I am using spring native 0.11.3-SNAPSHOT, spring boot 2.6.4-SNAPSHOT with spring-boot-starter-validation, spring-cloud-function-aws 3.2.3-SNAPSHOT, kotlin 1.6.10 and I am building with gradle.

**Comment by sdeleuze** [comment]
@FalkWoldmann6232 Could you please try with `access = [TypeAccess.RESOURCE]`?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by FalkWoldmann6232** [comment]
Alright, we will test it with the TypeAccess

**Comment by FalkWoldmann6232** [comment]
I added ```@TypeHint(
    types = [SNSEvent::class, Record::class, SNS::class, Message::class, TestEventData::class, Valid::class, Pattern::class, Object::class],
    access = [TypeAccess.RESOURCE]
)```

but now I receive the following error message:
```com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.example.demo.SNSEvent` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)```

**Comment by sdeleuze** [comment]
Try `@TypeHint( types = [SNSEvent::class, Record::class, SNS::class, Message::class, TestEventData::class, Valid::class, Pattern::class, Object::class], access = [TypeAccess.RESOURCE, TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.PUBLIC_METHODS] )`.

**Comment by FalkWoldmann6232** [comment]
I get the following error ```java.lang.IllegalStateException: Method [registerNatives] was discovered in the .class file but cannot be resolved in the class object [...] Caused by: java.lang.NoSuchMethodException: java.lang.Object.registerNatives()```

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by FalkWoldmann6232** [comment]
The validation now works after I added `TypeAccess.DECLARED_METHODS`. Thank you for the support!
