### ISSUE TITLE
Spring security method missing hint

### ISSUE THREAD

**Issue by benoit-laplante** [spring-projects-experimental/spring-native#1518]
MethodSecurityExpressionRoot typehint DELCLARED_METHODS and DECLARED_FIELDS are missing to expose properties fieldObject and returnObject in spel expression like

`
@PostFilter("hasPermission(filterObject.id, 'POJO', read)")
    List<POJO> listAll();
`

**Comment by sdeleuze** [comment]
@eleftherias Do you think those should be configured out of the box?

**Comment by eleftherias** [comment]
@sdeleuze Yes, I do think they should be configured out of the box.
I can update the `GlobalMethodSecurityHints` and add an example of this issue to one of the samples.
