### ISSUE TITLE
Unable to read Enum values from dependencies

### ISSUE THREAD

**Issue by atyamlalithya** [spring-projects-experimental/spring-native#1526]
Spring native is not adding Enum getter setter methods to reflect-config.json when referred from a dependency project unless you specify a hint in the main project.

Attaching a zip to replicate the issue. In this example my demo project gets the model from the dependency project and when i try to save a User object which has Enum Model, i am getting the below exception
```
  Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `com.example.dependency.model.EmployeeDetails$ModelEnum` from String "wfh": not one of the values accepted for Enum class: [WFH, OFFICE]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.example.dependency.model.EmployeeDetails$ModelEnum` from String "wfh": not one of the values accepted for Enum class: [WFH, OFFICE]<EOL> at [Source: (PushbackInputStream); line: 3, column: 13] (through reference chain: com.example.demo.model.User["model"])]
```

Example request: http://localhost:8080/addUser
```
{
    "id" : "3",
    "model":"workFromHome"
}
```

My enum
```
 public static enum ModelEnum {
    WFH("wfh"),
    OFFICE("office");

    private String value;

    private ModelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return this.value;
    }

    public String toString() {
      return String.valueOf(this.value);
    }

    @JsonCreator
    public static EmployeeDetails.ModelEnum fromValue(String value) {
      EmployeeDetails.ModelEnum[] var1 = values();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
        EmployeeDetails.ModelEnum b = var1[var3];
        if (b.value.equals(value)) {
          return b;
        }
      }

      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
```

Demo : 
[IdeaProjects.zip](https://github.com/spring-projects-experimental/spring-native/files/8200620/IdeaProjects.zip)

Note: Project works as expected when i run as a regular Spring boot application

**Comment by atyamlalithya** [comment]
Hi, Could anyone please look into this.

**Comment by bclozel** [comment]
While we can add reflection hints automatically by looking at controller handlers and other Spring API, this is way more involved: a Controller handler returns a `List<User>`, with `User` being an entity that `extends EmployeeDetails`, and `EmployeeDetails` (itself defined in a dependency) having an enum attribute which is itself annotated with a `@JsonCreator` method.

That's quite removed from the original intent, and [using `@TypeHint`](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_annotated_hints) here would make perfect sense. I'll close this issue in favor of #1152, where we might figure out new ways to address this.

**Comment by atyamlalithya** [comment]
Thanks @bclozel
