### ISSUE TITLE
error while loading shared libraries: libfreetype.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ojaynico** [spring-projects-experimental/spring-native#1540]
I get the error above while trying to run a compiled native file on Ubuntu.

**Comment by sdeleuze** [comment]
Please provide a repro project.

**Comment by ojaynico** [comment]
I have extracted a project from one of my services that throws the error.

https://github.com/ojaynico/quiz-service

**Comment by sdeleuze** [comment]
I can't reproduce on my OS (Archlinux), I guess your Ubuntu installation just miss this library which is needed for some native apps, so I would advise to install it in your system. I am closing this issue since I don't see any actionable item on our side.
