### ISSUE TITLE
Tomcat ParsingError HttpServlet.service()->FrameWorkServlet.doOptions()

### ISSUE THREAD

**Issue by enderwsp** [spring-projects-experimental/spring-native#1557]
env
graalvm 21.3.1-jdk8
springboot 2.5.11-same to spring.start.io
jdk 1.8
springcloud 2020.0.5
spring-native 0.10.6
native-buildtools 0.9.4

created from spring.start.io

include tomcat eureka bootstrap

key error msg

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.web.servlet.FrameworkServlet.doOptions(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)

Parsing context:
   at org.springframework.web.servlet.FrameworkServlet.doOptions(FrameworkServlet.java:944)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
   at com.oracle.svm.core.reflect.ReflectionAccessorHolder.WsFilter_doFilter_f23728104f2f98d3170efe99f12da6cfdbf2aa23(generated:0)

NullPointerException
      at com.oracle.svm.hosted.snippets.ReflectionPlugins.lambda$null$4(ReflectionPlugins.java:385)
```

what can i do for fix it

**Comment by enderwsp** [comment]
exe command 
:
mvn clean  -Pnative -DskipTests package

**Comment by enderwsp** [comment]
> If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

I upload to https://github.com/enderwsp/spring-native-graalvm

springboot 2.4.9 & springcloud 2020.0.3 ,
also
will get same error

i set many args

in <configuration>
  <buildArgs>
    <buildArg>

so, i want get more details when compiled failed 

maybe some of those is not avalibe

**Comment by mhalbritter** [comment]
Your sample uses Spring Boot 2.4.9, which is [no longer supported](https://spring.io/projects/spring-boot#support). Please update it to a supported version of Spring Boot, and make sure that your sample runs in non-AOT mode.

**Comment by enderwsp** [comment]
> Your sample uses Spring Boot 2.4.9, which is [no longer supported](https://spring.io/projects/spring-boot#support) (if you don't have commercial support). Please update it to a supported version of Spring Boot, and make sure that your sample runs in non-AOT mode.

u can change 2

springboot 2.5.11
springcloud 2020.0.5

&

recomplie
the error will be printed

**Comment by mhalbritter** [comment]
The error message sounds like a bug in the GraalVM compiler. Can you try to recompile it with the latest `spring-native` (11.3), the latest `native-build-tools` (0.9.11) and with the newest available GraalVM (22.0.0.2)?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
