### ISSUE TITLE
native app read files from the path (under resources [or in packaged jar..]) 

### ISSUE THREAD

**Issue by enderwsp** [spring-projects-experimental/spring-native#1558]
i have read content from  https://www.graalvm.org/21.3/reference-manual/native-image/Resources/

but,i cannot find any example for native app to read files from the path

project tree:

src
--main
----java
------
--resources
----myjsonfiles
------one.json
------two.json

when execute follow :

path=class.getClassloader().getResource("myjsonfiles")
//i get URL(Protocol:resource)

Scanner s = new Scanner(new BufferedReader(new InputStreamReader(this.getClass().getResourceAsStream(path))));

cannnot get fileList （such as:["myjsonfiles/one.json","myjsonfiles/two.json"]）

**Comment by mhalbritter** [comment]
Spring Native automatically includes the files you put in `src/main/resources` into the native image. You can find pointers to your resource files in `target/classes/META-INF/native-image/org.springframework.aot/spring-aot/resource-config.json` (if you're using maven). If you think this is not the case in your project, please provide a minimal, yet complete sample (something that we can unzip or git clone, build, and deploy) which we can use to reproduce the issue.

**Comment by enderwsp** [comment]
> Spring Native automatically includes the files you put in `src/main/resources` into the native image. You can find pointers to your resource files in `target/classes/META-INF/native-image/org.springframework.aot/spring-aot/resource-config.json` (if you're using maven). If you think this is not the case in your project, please provide a minimal, yet complete sample (something that we can unzip or git clone, build, and deploy) which we can use to reproduce the issue.
> 
> Listing files via `getResourceAsStream("<name of the folder>")` doesn't work in native-image.

so，is there any solution , for   Listing files via `getResourceAsStream("<name of the folder>")` doesn't work in native-image?

or

it is not supported just now?

can i make a resolver ,so i can  generate filepath-list  in the folder, from java code to native image

**Comment by mhalbritter** [comment]
I don't know of any workaround to get this working. Please contact the [GraalVM team](https://www.graalvm.org/community/) if you have further questions. The issue tracker should be for issues only.
