### ISSUE TITLE
Native-tests are broken with GraalVM 22.1

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects-experimental/spring-native#1561]
Running for example the tests in `commandlinerunner` via `mvn test -Pnative`

## Working version:

```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)
```

[Working output](https://github.com/spring-projects-experimental/spring-native/files/8380971/22.0.txt)

## Broken version (built from https://github.com/oracle/graal/commit/3eb1d111ab25565acbbc015128a2c787656e2675):

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM 22.1.0-dev (build 17.0.3+4-jvmci-22.1-b02)
OpenJDK 64-Bit Server VM GraalVM 22.1.0-dev (build 17.0.3+4-jvmci-22.1-b02, mixed mode, sharing)
```

[Broken output](https://github.com/spring-projects-experimental/spring-native/files/8380984/22.1.txt)

Main problem seems to be

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.mockito.plugins.PluginSwitch] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
```

**Comment by sdeleuze** [comment]
Could you try to see if we can exclude it via `MockitoExcludeFilter`?

**Comment by mhalbritter** [comment]
https://github.com/spring-projects-experimental/spring-native/pull/1562 fixes this issue by using `IgnoredFactoriesCodeContributor` to ignore `MockitoTestExecutionListener` and `ResetMocksTestExecutionListener` when generating AOT code.
