### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by ebremer** [spring-projects-experimental/spring-native#1567]
Using Spring Boot 2.6.4 and Maven 3.8.5, I tried to compile a large project but got the following error:

Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.11.3:generate (default-cli) on project Halcyon: Build failed during Spring AOT code generation: Could not exec java: Cannot run program "C:\bin\graalvm\bin\java.exe" (in directory "D:\projects\lagrproject\target"): CreateProcess error=206, The filename or extension is too long -> [Help 1]

I've gotten this error before without using spring-aot-maven-plugin, but I worked around this by setting the property:
longClasspath=true, but this setting doesn't seem to work when using spring-aot-maven-plugin.

**Comment by mhalbritter** [comment]
Looks like a bug with the limited commandline length on windows. Do you know which process starting failed? Can you switch on logging and provide a log file? Thanks!

**Comment by sdeleuze** [comment]
Couldbe due to https://github.com/graalvm/native-build-tools/pull/212, please try with NBT 0.9.11. Could you share more about `longClasspath=true`?

**Comment by ebremer** [comment]
The  longClasspath=true option I use traces from here:
https://www.mojohaus.org/exec-maven-plugin/exec-mojo.html

**Comment by mhalbritter** [comment]
Here's a similiar issue on spring-boot side: https://github.com/spring-projects/spring-boot/issues/17766

**Comment by sdeleuze** [comment]
cc @bclozel who worked on the plugin in case he could have some context/ideas to share.

**Comment by mhalbritter** [comment]
I think I have a working solution. Passing the arguments as an argfile, which is supported as of Java 9, seems like a good idea.

**Comment by mhalbritter** [comment]
See https://github.com/spring-projects-experimental/spring-native/pull/1585
