### ISSUE TITLE
Help webjars locator to find assets in /META-INF/resources/webjars

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-native#157]
The webjars locator is really nice, and is configured automatically in Spring Boot, but it doesn't work in a native image because there is no directory traversal on the classpath (same problem with `@ComponentScan`).  Maybe we can fix this in a similar way to `@ComponentScan` - the paths it scans are well defined and easy to discover. If we scan them at build time we can probably use a substitution at runtime to pick the right location, instead of trying to scan and failing. (See also https://github.com/oracle/graal/issues/1108.)

**Comment by sdeleuze** [comment]
We could maybe use a similar build time transformation than the one described in #374.

**Comment by sdeleuze** [comment]
See https://github.com/spring-projects/spring-framework/issues/27619.
