### ISSUE TITLE
Spring Data fails with "IllegalArgumentException: Not a managed type"

### ISSUE THREAD

**Issue by Twometer** [spring-projects-experimental/spring-native#1581]
I have a simple repository like this:
```kotlin
@Profile("!test")
@Repository
interface BookingRepository : JpaRepository<Booking, UUID> 
```

And I have a simple test function (Spring Cloud Functions) like this:
```kotlin
@Bean
    fun helloWorld(
            bookingRepo: BookingRepository,
    ): Function<String, String> {
        bookingRepo.findAll()
        return Function { it }
    }
```

This works flawlessly in regular Spring, in my JVM-based integration tests, everywhere. But the native image always fails with an exception:

```
Error creating bean with name 'helloWorld': Unsatisfied dependency expressed through method 'helloWorld' parameter 0; nested exception is

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookingRepository': Invocation of init method failed; nested exception is

java.lang.IllegalArgumentException: Not a managed type: class com.xx.xx.model.Booking]
```

I've annotated my application with `EntityScan` and `EnableJpaRepositories`, but still the same error

I'm running on GraalVM 21.2.0

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by Twometer** [comment]
I was trying to get the official samples to work in order to provide a MVE, but the build keeps failing, I'll post when I have an example repo.

**Comment by Twometer** [comment]
@mhalbritter Okay, it took me a while to get it running but this is a MVE that breaks with this error: https://github.com/Twometer/spring-native-data-bug-mve

Configuration
- Spring Boot, Spring Data with H2 Database, Spring Cloud Function, Spring Native
- Spring configuration generated by the agent
- GraalVM 21.2.0

**Comment by mhalbritter** [comment]
Switching the mode from `native-agent` to `agent` seems to do the trick:

old:

```
springAot {
	mode.set(org.springframework.aot.gradle.dsl.AotMode.NATIVE_AGENT)
}
```

new:

```
springAot {
	mode.set(org.springframework.aot.gradle.dsl.AotMode.NATIVE)
}
```

**Comment by Twometer** [comment]
@mhalbritter Thanks. Which GraalVM version did you use with this, because if I do this it will fail with `Unknown attribute 'condition'`. Also, if I switch to `NATIVE` mode, won't it ignore my native-agent generated files?

**Comment by mhalbritter** [comment]
I used the latest available 22.1 graal-dev build and updated the spring-native version to `0.11.4`.

When using `NATIVE` mode, it generates additional metadata on top of your own metadata. Your own metadata is not ignored.

**Comment by Twometer** [comment]
I did all that now, and the Graal compiler crashes with a null pointer exception, how did you get it to build?

**Comment by mhalbritter** [comment]
I used [this version of graal](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220411_0809) and this `build.gradle.kts` with `./gradlew nativeCompile` on a Linux aarch64 machine:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

plugins {
	id("org.springframework.boot") version "2.6.6"
	id("io.spring.dependency-management") version "1.0.11.RELEASE"
	kotlin("jvm") version "1.6.10"
	kotlin("plugin.spring") version "1.6.10"
	kotlin("plugin.jpa") version "1.6.10"
	id("org.springframework.experimental.aot") version "0.11.4"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
	maven { url = uri("https://repo.spring.io/release") }
	mavenCentral()
}

extra["springCloudVersion"] = "2021.0.1"

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.springframework.cloud:spring-cloud-function-web")
	runtimeOnly("com.h2database:h2")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

springAot {
	mode.set(org.springframework.aot.gradle.dsl.AotMode.NATIVE)
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
	}
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "11"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<BootBuildImage> {
	builder = "paketobuildpacks/builder:tiny"
	environment = mapOf("BP_NATIVE_IMAGE" to "true")
}
```

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0-dev (build 17.0.3+5-jvmci-22.1-b04)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0-dev (build 17.0.3+5-jvmci-22.1-b04, mixed mode, sharing)
```

If you run into GraalVM compiler crashes, please report to the GraalVM team.

**Comment by Twometer** [comment]
I will try it out, thanks for your support!

**Comment by Twometer** [comment]
I finally got it working, thanks again ❤️
