### ISSUE TITLE
Upgrade to Spring Cloud 2021.0.3

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1606]

**Comment by sdeleuze** [comment]
@OlgaMaciaszek When you are back, please have a look to Spring Cloud Function sample, they seems to be broken with Spring Cloud 2021.0.2.

**Comment by OlgaMaciaszek** [comment]
@olegz takes care of the Spring Cloud Function native integration.

**Comment by OlgaMaciaszek** [comment]
@sdeleuze I have reverted the changes that made the issue apparent from Spring Cloud Config. It will be available within Spring Cloud `2021.0.3`. However, the issue of registering beans within the Bootstrap context should be addressed in AOT. I understand this is not going to be addressed within spring-native backlog, so I'm going to create an issue for it in Framework.
