### ISSUE TITLE
Jsr250 is not supported

### ISSUE THREAD

**Issue by senpure** [spring-projects-experimental/spring-native#1608]
In native mode @javax.annotation.Resource   injection failure.
org.springframework.aot.context.bootstrap.generator.bean.descriptor.InjectionPointsSupplier support @Autowired, @Value and jsr330 why not support jsr250?

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
