### ISSUE TITLE
Is there any way to load properties file from module library

### ISSUE THREAD

**Issue by tuyendev** [spring-projects-experimental/spring-native#1617]
I actually don't know it's a bug or feature question. Here is my situtation

I created a customized module following the **Spring style** (with _spring.factories_) and build as a library. I have some custom properties files in my module which already loaded by @PropertySource.
After that, I put the custom library to my main app and everything works fine if I build a jar file. But it can't work if I try to build a native image.
**My question is did spring support to load custom properties file in library ?**

**Comment by bclozel** [comment]
If your library is loading a property file on its own and this behavior is not automatically picked up during the native image compilation, you'll need to declare a resource hint in your library to let GraalVM know about this. You can use [@ResourceHint](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_annotated_hints) or provide [a JSON configuration file in your library JAR](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_manual_hints).

**Comment by tuyendev** [comment]
Thank you so much, I'll try now
