### ISSUE TITLE
Failed compiling on Windows: Unsupported OptionOrigin

### ISSUE THREAD

**Issue by ccarv** [spring-projects-experimental/spring-native#1622]
I used the [Spring Initializr](https://start.spring.io/) to generate a Spring Native project. Outside of the Spring Native dependencies, I included the Spring Cloud Streams dependency. I have not changed anything thus far and I am unable to successfully compile this on Windows 11.

I have Visual Studio 2022 installed, which includes the Windows SDK. I've configured my environment variables to point to the GraalVM directory.

Java:
```
PS D:\Work\GitLab\windows-agent-graalvm> java -version                              
java version "11.0.15" 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)
```

Maven:
```
PS D:\Work\GitLab\windows-agent-graalvm> mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: D:\Program Files\Apache\apache-maven-3.8.4
Java version: 11.0.15, vendor: GraalVM Community, runtime: C:\Program Files\Java\graalvm-ce-java11-22.1.0
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

JAVA_HOME:
```
PS D:\Work\GitLab\windows-agent-graalvm> echo $Env:JAVA_HOME
C:\Program Files\Java\graalvm-ce-java11-22.1.0
```

GRAALVM_HOME:
```
PS D:\Work\GitLab\windows-agent-graalvm> echo $Env:GRAALVM_HOME
C:\Program Files\Java\graalvm-ce-java11-22.1.0
```

I'm using the `x64 Native Tools Command Prompt for VS 2022` and running the following command:

`mvn -Pnative -DskipTests=true clean package`

This results in the following:
```
[WARNING] jar:file:///D:/Work/GitLab/windows-agent-graalvm/target/winagent-0.0.1-SNAPSHOT.jar!/META-INF/native-image/org.springframework.aot/spring-aot/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] Executing: C:\Program Files\Java\graalvm-ce-java11-22.1.0\bin\native-image.cmd @C:\Users\ccarv\AppData\Local\Temp\native-image14468276230591231109args
Fatal error: Unsupported OptionOrigin: C:\Users\ccarv\AppData\Local\Temp\native-image14468276230591231109args

Current timestamp: 1653486431268

Printing Instructions (ip=0x00007ff678e14ec0):
  0x00007ff678e14ea0: 0x00 0x41 0xc7 0x87 0xfc 0x00 0x00 0x00 0xfe 0xfe 0xfe 0x7e 0x48 0x8b 0x54 0x24
  0x00007ff678e14eb0: 0x20 0x4c 0x8b 0x44 0x24 0x10 0x4c 0x8b 0x4c 0x24 0x18 0xe8 0x80 0xfc 0xff 0xff
  0x00007ff678e14ec0: 0x90 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc
  0x00007ff678e14ed0: 0x48 0x83 0xec 0x28 0x48 0x89 0x54 0x24 0x20 0x49 0x3b 0x67 0x08 0x0f 0x86 0x66

Top of stack (sp=0x000000a27f17f3a0):
  0x000000a27f17f3a0: 0x00000000c0001000 0x00007ff67902b725
  0x000000a27f17f3b0: 0x000001ac6bb9e968 0x000001ac6b100000
  0x000000a27f17f3c0: 0x00007ff678e37724 0x00007ff678e84784
  0x000000a27f17f3d0: 0x0000000000000002 0x00007ff678e37724
  0x000000a27f17f3e0: 0x0000000000000002 0x000000000000010c
  0x000000a27f17f3f0: 0x000001ac6bb9cd90 0x000001ac6bb9ce40
  0x000000a27f17f400: 0x000001ac6bb9e8f8 0x000001ac6bb98b90
  0x000000a27f17f410: 0x0000000000000000 0x00007ff678e8be51
  0x000000a27f17f420: 0x00000000c0001000 0x00007ff67902923a
  0x000000a27f17f430: 0x00000000000012a7 0x00007ff678da5118
  0x000000a27f17f440: 0x000000006bb9cd90 0x00007ff67902e552
  0x000000a27f17f450: 0x000001ac6b615da8 0x0000000000000010
  0x000000a27f17f460: 0x000001ac6bb9b835 0x000001ac6bb9cdd0
  0x000000a27f17f470: 0x000001ac6b3ee7e8 0x000001ac6bb9cdb0
  0x000000a27f17f480: 0x000001ac6bb011c0 0x0000000100000000
  0x000000a27f17f490: 0x000000020000003a 0x00007ff678e9c226
  0x000000a27f17f4a0: 0x00000000c0001000 0x000001ac6bb9cc60
  0x000000a27f17f4b0: 0x000001ac6bb159f0 0x000001ac6bb9a590
  0x000000a27f17f4c0: 0x000001ac6bb9a590 0x0000001000001295
  0x000000a27f17f4d0: 0x000001ac6bb99100 0x000012a77924c403
  0x000000a27f17f4e0: 0x00000000c0001000 0x00007ff678e89619
  0x000000a27f17f4f0: 0x000001ac6b6ff5f8 0x000001ac6bb9a530
  0x000000a27f17f500: 0x000001ac6b3f3788 0x000001ac6bb9cd68
  0x000000a27f17f510: 0x000001ac6b100000 0x000001ac6bb15a48
  0x000000a27f17f520: 0x000001ac6bb02ec8 0x000001ac6bb15680
  0x000000a27f17f530: 0x000001ac6bb98f00 0x00007ff67902923a
  0x000000a27f17f540: 0x000001ac6bb9a510 0x00007ff678ea20a5
  0x000000a27f17f550: 0x000012a6000012a5 0x00007ff678e97498
  0x000000a27f17f560: 0x000001ac6bb99100 0x000001ac6b88e318
  0x000000a27f17f570: 0x000012a700000000 0x000001ac6b3f3788
  0x000000a27f17f580: 0x00000000002f3788 0x000001ac6bb9cc60
  0x000000a27f17f590: 0x000001ac6bb159f0 0x000001ac6bb15438

Top frame info:
  TotalFrameSize in CodeInfoTable 48

Threads:
  0x000001ac6ad4d200 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x000001ac6b66e5f8, daemon, stack(0x000000a27f700000,0x000000a27f800000)
  0x000001ac6ad44e00 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "main" - 0x000001ac6b66e550, stack(0x000000a27f080000,0x000000a27f180000)

VM thread locals for the failing thread 0x000001ac6ad44e00:
  0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes)
    0x000001ac6ad44e00: 0x000001ac6b4f9010
  8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)
  16 (4 bytes): Safepoint.safepointRequested = (int) 2147372751 (0x7ffe4ecf)
  20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)
  24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes)
    0x000001ac6ad44e18: 0x000001ac6bb00000 0x000001ac6bc00000
    0x000001ac6ad44e28: 0x000001ac6bb9e988 0x0000000000000000
  56 (8 bytes): PlatformThreads.currentThread = (Object) java.lang.Thread (0x000001ac6b66e550)
  64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 0 (0x0000000000000000)
  72 (8 bytes): AccessControlContextStack = (Object) java.util.ArrayDeque (0x000001ac6bb187a8)
  80 (8 bytes): ExceptionUnwind.currentException = (Object) null
  88 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  96 (8 bytes): IsolatedCompileClient.currentClient = (Object) null
  104 (8 bytes): IsolatedCompileContext.currentContext = (Object) null
  112 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x000001ac6bb01478)
  120 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null
  128 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  136 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  144 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null
  152 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null
  160 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes)
    0x000001ac6ad44ea0: 0x0000000000000000
  168 (8 bytes): ThreadLocalAllocation.allocatedBytes = (Word) 0 (0x0000000000000000)
  176 (8 bytes): VMThreads.IsolateTL = (Word) 1840042213376 (0x000001ac6b100000)
  184 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 212 (0x00000000000000d4)
  192 (8 bytes): VMThreads.OSThreadIdTL = (Word) 7984 (0x0000000000001f30)
  200 (8 bytes): VMThreads.StackBase = (Word) 697916981248 (0x000000a27f180000)
  208 (8 bytes): VMThreads.StackEnd = (Word) 697915932672 (0x000000a27f080000)
  216 (8 bytes): VMThreads.StartedByCurrentIsolate = (bytes)
    0x000001ac6ad44ed8: 0x0000000000000000
  224 (8 bytes): VMThreads.nextTL = (Word) 0 (0x0000000000000000)
  232 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 1840038301136 (0x000001ac6ad44dd0)
  240 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)
  244 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)
  248 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)
  252 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)
  256 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)
  260 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)

No VMOperation in progress

The 15 most recent VM operation status changes (oldest first):

Counters:

Java frame anchors for the failing thread 0x000001ac6ad44e00:
  No anchors

Stacktrace for the failing thread 0x000001ac6ad44e00:
  SP 0x000000a27f17f3a0 IP 0x00007ff678e14ec0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:116)
  SP 0x000000a27f17f3a0 IP 0x00007ff678e14ec0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:109)
  SP 0x000000a27f17f3d0 IP 0x00007ff678e84784  [image code] com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:65)
  SP 0x000000a27f17f3e0 IP 0x00007ff678e37724  [image code] com.oracle.svm.core.option.OptionOrigin.from(OptionOrigin.java:79)
  SP 0x000000a27f17f420 IP 0x00007ff678e8be51  [image code] com.oracle.svm.driver.APIOptionHandler.translateOption(APIOptionHandler.java:299)
  SP 0x000000a27f17f4f0 IP 0x00007ff678e89619  [image code] com.oracle.svm.driver.APIOptionHandler.consume(APIOptionHandler.java:276)
  SP 0x000000a27f17f5b0 IP 0x00007ff678eab4ce  [image code] com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1463)
  SP 0x000000a27f17f5f0 IP 0x00007ff678e9379c  [image code] com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:324)
  SP 0x000000a27f17f690 IP 0x00007ff678eab4ce  [image code] com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1463)
  SP 0x000000a27f17f6d0 IP 0x00007ff678ec84f2  [image code] com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1718)
  SP 0x000000a27f17f730 IP 0x00007ff678eb4311  [image code] com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:936)
  SP 0x000000a27f17f810 IP 0x00007ff678eafc39  [image code] com.oracle.svm.driver.NativeImage.build(NativeImage.java:1380)
  SP 0x000000a27f17f850 IP 0x00007ff678ec581b  [image code] com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1350)
  SP 0x000000a27f17f8b0 IP 0x00007ff678ec5093  [image code] com.oracle.svm.driver.NativeImage.main(NativeImage.java:1337)
  SP 0x000000a27f17f8d0 IP 0x00007ff678da492e  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
  SP 0x000000a27f17f8d0 IP 0x00007ff678da492e  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:185)
  SP 0x000000a27f17f8f0 IP 0x00007ff678de20db  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(IsolateEnterStub.java:0)

VM mutexes:
  mutex "thread" is unlocked.
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  mutex "referencePendingList" is unlocked.

Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x000001ac6b100000
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 0
  Complete collections: 0

Native image heap boundaries:
  ReadOnly Primitives: 0x000001ac6b201028 - 0x000001ac6b37dc08
  ReadOnly References: 0x000001ac6b37dc08 - 0x000001ac6b4f87c8
  ReadOnly Relocatables: 0x000001ac6b4f9000 - 0x000001ac6b592460
  Writable Primitives: 0x000001ac6b593000 - 0x000001ac6b61e0e0
  Writable References: 0x000001ac6b61e0e0 - 0x000001ac6b88f458
  Writable Huge: 0x000001ac6b900030 - 0x000001ac6b923ac0
  ReadOnly Huge: 0x000001ac6b924030 - 0x000001ac6ba814f8

Heap:
  Young generation:
    Eden:
      edenSpace:
        aligned: 0/0 unaligned: 0/0
    Survivors:
      Survivor-1 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-1 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 To:
        aligned: 0/0 unaligned: 0/0
  Old generation:
    oldFromSpace:
      aligned: 0/0 unaligned: 0/0
    oldToSpace:
      aligned: 0/0 unaligned: 0/0

  Unused:
    aligned: 0/0

Fatal error: Unsupported OptionOrigin: C:\Users\ccarv\AppData\Local\Temp\native-image14468276230591231109args
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.579 s
[INFO] Finished at: 2022-05-25T09:47:11-04:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "default" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.11:build (build-native) on project winagent: Execution of C:\Program Files\Java\graalvm-ce-java11-22.1.0\bin\native-image.cmd @C:\Users\ccarv\AppData\Local\Temp\native-image14468276230591231109args returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by kazuki43zoo** [comment]
probably, this issue belong https://github.com/oracle/graal/issues/4502.

**Comment by WindBruce** [comment]
I use GraalVM 22.2.0（dev version）,this error still happens. Here is the logs.

`PS D:\WorkSpace-DEVS\codeGen> mvn -Pnative -DskipTests=true clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.wd.nat:code >---------------------------
[INFO] Building code test 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ code ---
[INFO] Deleting D:\WorkSpace-DEVS\codeGen\target
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ code ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ code ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to D:\WorkSpace-DEVS\codeGen\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ code ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory D:\WorkSpace-DEVS\codeGen\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ code ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to D:\WorkSpace-DEVS\codeGen\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ code ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- native-maven-plugin:0.9.11:test (test-native) @ code ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO]
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ code ---
[INFO] Building jar: D:\WorkSpace-DEVS\codeGen\target\code-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.7.0:repackage (repackage) @ code ---
[INFO] Replacing main artifact with repackaged archive
[INFO]
[INFO] --- native-maven-plugin:0.9.11:build (build-native) @ code ---
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-starter/2.7.0/spring-boot-starter-2.7.0.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot/2.7.0/spring-boot-2.7.0.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-context:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-context/5.3.20/spring-context-5.3.20.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-autoconfigure:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-autoconfigure/2.7.0/spring-boot-autoconfigure-2.7.0.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-logging:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-starter-logging/2.7.0/spring-boot-starter-logging-2.7.0.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-classic:jar:1.2.11:compile (file:///D:/DevPrograms/MavenRespository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-core:jar:1.2.11:compile (file:///D:/DevPrograms/MavenRespository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar)
[INFO] ImageClasspath Entry: org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile (file:///D:/DevPrograms/MavenRespository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar)
[INFO] ImageClasspath Entry: org.apache.logging.log4j:log4j-api:jar:2.17.2:compile (file:///D:/DevPrograms/MavenRespository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar)
[INFO] ImageClasspath Entry: org.slf4j:jul-to-slf4j:jar:1.7.36:compile (file:///D:/DevPrograms/MavenRespository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar)
[INFO] ImageClasspath Entry: jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile (file:///D:/DevPrograms/MavenRespository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-core:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-core/5.3.20/spring-core-5.3.20.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-jcl:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-jcl/5.3.20/spring-jcl-5.3.20.jar)
[INFO] ImageClasspath Entry: org.yaml:snakeyaml:jar:1.30:compile (file:///D:/DevPrograms/MavenRespository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar)
[INFO] ImageClasspath Entry: org.springframework.experimental:spring-native:jar:0.12.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/experimental/spring-native/0.12.0/spring-native-0.12.0.jar)
[INFO] ImageClasspath Entry: org.slf4j:slf4j-api:jar:1.7.36:compile (file:///D:/DevPrograms/MavenRespository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-web:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-starter-web/2.7.0/spring-boot-starter-web-2.7.0.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-json:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-starter-json/2.7.0/spring-boot-starter-json-2.7.0.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-databind:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/core/jackson-databind/2.13.3/jackson-databind-2.13.3.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-annotations:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/core/jackson-annotations/2.13.3/jackson-annotations-2.13.3.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-core:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/core/jackson-core/2.13.3/jackson-core-2.13.3.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.3/jackson-datatype-jdk8-2.13.3.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.3/jackson-datatype-jsr310-2.13.3.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.3:compile (file:///D:/DevPrograms/MavenRespository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.3/jackson-module-parameter-names-2.13.3.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.0:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/boot/spring-boot-starter-tomcat/2.7.0/spring-boot-starter-tomcat-2.7.0.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.63:compile (file:///D:/DevPrograms/MavenRespository/org/apache/tomcat/embed/tomcat-embed-core/9.0.63/tomcat-embed-core-9.0.63.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.63:compile (file:///D:/DevPrograms/MavenRespository/org/apache/tomcat/embed/tomcat-embed-el/9.0.63/tomcat-embed-el-9.0.63.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.63:compile (file:///D:/DevPrograms/MavenRespository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.63/tomcat-embed-websocket-9.0.63.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-web:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-web/5.3.20/spring-web-5.3.20.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-beans:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-beans/5.3.20/spring-beans-5.3.20.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-webmvc:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-webmvc/5.3.20/spring-webmvc-5.3.20.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-aop:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-aop/5.3.20/spring-aop-5.3.20.jar)    
[INFO] ImageClasspath Entry: org.springframework:spring-expression:jar:5.3.20:compile (file:///D:/DevPrograms/MavenRespository/org/springframework/spring-expression/5.3.20/spring-expression-5.3.20.jar)
[INFO] ImageClasspath Entry: com.wd.nat:code:jar:0.0.1-SNAPSHOT (file:///D:/WorkSpace-DEVS/codeGen/target/code-0.0.1-SNAPSHOT.jar)
[INFO] Executing: D:\DevPrograms\Java\graalvm-ce-java17-22.2.0-dev\bin\native-image.cmd @C:\Users\wind\AppData\Local\Temp\native-image14427801459238598691args
Error: Please specify class containing the main entry point method. (see --help)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.330 s
[INFO] Finished at: 2022-06-04T01:55:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.11:build (build-native) on project code: Execution of D:\DevPrograms\Java\graalvm-ce-java17-22.2.0-dev\bin\native-image.cmd @C:\Users\wind\AppData\Local\Temp\native-image14427801459238598691args returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS D:\WorkSpace-DEVS\codeGen> 
`

**Comment by mhalbritter** [comment]
Can you please run maven with `-X` to enable debug output?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
