### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [spring-projects-experimental/spring-native#1632]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by linghengqian** [comment]
This kind of problem is hung up on StackOverFlow, not everyone likes Quarkus, a framework that has mandatory Native restrictions on dependencies.😕

**Comment by bclozel** [comment]
This is highly suggestive so we'll leave that exercise to the community. Thanks!
