### ISSUE TITLE
我想使用spring native 和bootstrap.yml

### ISSUE THREAD

**Issue by zhangpan-soft** [spring-projects-experimental/spring-native#1633]
我想在Springcloud种使用native, 但是,如果我引入了bootstrap.yml, mvn clean -Pnative package 执行之后的可执行文件, 启动后发现没有使用bootstrap.yml中的配置. 如果我使用mvn spring-boot:run 它是正常的,可以正常使用. 如果我使用mvn spring-boot:build-image 它好像最后会构建失败, 失败信息是15. 我应该怎么配置才能使mvn clean -Pnative package打包出的可执行文件正常使用bootstrap.yml

**Comment by bclozel** [comment]
Duplicates #1634
