### ISSUE TITLE
`springcloud bootstrap` doesn't work

### ISSUE THREAD

**Issue by zhangpan-soft** [spring-projects-experimental/spring-native#1634]
I want to use spring cloud bootstrap. However, when I use 'mvn clean -Pnative -Dskiptests package', it is successfully built, but the bootstrap is found at runtime YML is not effective. When I use 'mvn spring-boot: run', it runs correctly and uses bootstrap. When I use 'mvn spring-boot: build-image', the build fails with an error of 134 and 135. What should I do to use bootstrap normally.I think this is very important, because if this problem cannot be solved, the configuration center cannot be used, which means that I will lose the advantage of flexible configuration This is not worth the loss Therefore, I want to solve it

**Comment by mhalbritter** [comment]
Hi. According to the [documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support-spring-cloud), "Spring Cloud Bootstrap is no longer supported.".

**Comment by sdeleuze** [comment]
Notice we are working as part of Spring Boot 3 in collaboration with the Cloud team to provide better compatibility, so thanks for your patience.
