### ISSUE TITLE
Thymeleaf doesn't work without spring-web

### ISSUE THREAD

**Issue by Delorien84** [spring-projects-experimental/spring-native#1640]
Hi,
 when I want to create application without web, I got following exception during AOT compilation. I want to create simple Job application that gather some data from database. I have just following dependencies.

```
implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
```

This setup works for spring native 0.11.X branch, but not with current 0.12.0 version.

To workaround I need to add web dependency to compile application.

```
implementation("org.springframework.boot:spring-boot-starter-web")
```

**Comment by Delorien84** [comment]
Here it is: https://github.com/Delorien84/spring-native-bug-1640. During creating sample project I have notice that the problem is caused by `org.springframework.boot:spring-boot-starter-thymeleaf` dependency.

**Comment by Delorien84** [comment]
@mhalbritter  adding `org.springframework:spring-web` dependencies solve the problem. But in 0.11.x it was not needed.

**Comment by mhalbritter** [comment]
What is the usecase for using Thymeleaf without spring-web? as far as i can see, the auto-configuration for Boot for Thymeleaf only deals with Web + Webflux. Your sample project unfortunately has no code in it which uses Thymeleaf.

**Comment by Delorien84** [comment]
@mhalbritter  Previously I used `id("org.springframework.experimental.aot") version "0.10.5"` and it works (sorry it was not 0.11 :( ). My use case is to query db for data and use Thymeleaf to render html page and send the page via email. Simple reporting application that we execute once per day. I updated the repository to contain all the code we have, sou you have may see our usage of Thymeleaf. Just to sanitize database queries and some name. 

It works without problem with `0.10.5` and with `0.12.0` when I add `spring-web` dependency.

https://github.com/Delorien84/spring-native-bug-1640

**Comment by mhalbritter** [comment]
Which Spring Boot version did you use with `0.10.5`?

**Comment by Delorien84** [comment]
`id("org.springframework.boot") version "2.5.6"`

**Comment by mhalbritter** [comment]
This will be handled with the upcoming Spring Boot 3.0. In the meantime, please include `spring-web` to workaround that issue.
