### ISSUE TITLE
Deserialization issue while using nested list of custom object

### ISSUE THREAD

**Issue by sajinsachidanand** [spring-projects-experimental/spring-native#1641]
public class A<M>  implements X {

private List<M> results;

// default constructor
// getter and setters

}

This model is using with resttemplate.

Added type hint and serialization hint for both classes. 

In AOT enable mode it's deserializing with results. 
If it's image it's always giving empty responses.

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by sajinsachidanand** [comment]
Sure. Please give me sometime.

**Comment by sajinsachidanand** [comment]
It's working fine in trying with a sample app.
Anyway to debug this ? Basically it's running fine in Aot enabled mode. If it's a docker image list of a class is always empty. Reflection hints are generating as expected.

**Comment by sdeleuze** [comment]
Can you try using [Native Build Tools](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-build-tools) not Buildpacks?

**Comment by sajinsachidanand** [comment]
It's failing with different on start of the application:
Caused by: java.lang.NoSuchMethodError: com.xxx.service.impl.PaymentServiceImpl.<init>()

This issue is not showing in docker image.
