### ISSUE TITLE
RabbitMQ Regression with GraalVM 22.1

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1643]
While the implicit upgrade of paketo to GraalVM 22.1 fixed things for JPA.
It on the other hand broke RabbitMQ Hints

While this branch worked flawlessly 2 months ago (it bootstraps the application during build to verify that application start works)
https://github.com/goafabric/event-dispatcher-service/actions/runs/2225017519

A direct copy now breaks:
https://github.com/goafabric/event-dispatcher-service/actions/runs/2507912855

See error below -- the @Queuebinding inside LoggerAdapter brakes.
Upgrading or downgrading spring (native) wont change anything 
The only difference i can spot is graalvm 22.0.1 vs 22.1

I guess the Class LoggerAdapter alone should be enough to cause the behaviour

-- cut ---
com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.amqp.rabbit.annotation.QueueBinding, interface org.springframework.core.annotation.SynthesizedAnnotation] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
[1187](https://github.com/goafabric/event-dispatcher-service/runs/6915346561?check_suite_focus=true#step:6:1188)
2022-06-16 09:09:19.706 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
[1188](https://github.com/goafabric/event-dispatcher-service/runs/6915346561?check_suite_focus=true#step:6:1189)
[1189](https://github.com/goafabric/event-dispatcher-service/runs/6915346561?check_suite_focus=true#step:6:1190)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'loggerAdapter': Initialization of bean failed; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.amqp.rabbit.annotation.QueueBinding, interface org.springframework.core.annotation.SynthesizedAnnotation] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.

**Comment by goafabric** [comment]
@sdeleuze thank you

**Comment by goafabric** [comment]
With Spring Boot 3.0 M5 it works nearly out of the Box.
Just a hint for RabbitHealthIndicator is missing

`
static class ApplicationRuntimeHints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            registerReflection(RabbitHealthIndicator.class, hints);
        }

        private void registerReflection(Class clazz, RuntimeHints hints) {
            Arrays.stream(clazz.getDeclaredConstructors()).forEach(
                    r -> hints.reflection().registerConstructor(r, ExecutableMode.INVOKE));
            Arrays.stream(clazz.getDeclaredMethods()).forEach(
                    r -> hints.reflection().registerMethod(r, ExecutableMode.INVOKE));
        }

    }
`

**Comment by wilkinsona** [comment]
Thanks, @goafabric. I think we've fixed that for RC1: https://github.com/spring-projects/spring-boot/issues/32541.

**Comment by goafabric** [comment]
@wilkinsona cool thank you
