### ISSUE TITLE
Kotlin: Native reflection config missing kotlin.internal.jdk8.JDK8PlatformImplementations

### ISSUE THREAD

**Issue by Tonne-TM** [spring-projects-experimental/spring-native#1646]
My native compiled image throws the following exception when launching a coroutine:
```
2022-06-17 13:37:15.783 ERROR 34232 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for kotlin.internal.jdk8.JDK8PlatformImplementations.<init>() is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.
```
### Minimal project to reproduce:
- [Spring Initializer Project](https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.7.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native,webflux)
- Minimal code: 
```kotlin
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
...

@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
	runApplication<DemoApplication>(*args)
}

@Component
class Starter : ApplicationRunner {

	private val logger = LoggerFactory.getLogger(javaClass)

	override fun run(args: ApplicationArguments?) = runBlocking<Unit> {
		launch(Dispatchers.Default) {
			logger.info("log smth out of coroutine")
		}
	}
}

```
- Build using `./gradlew nativeCompile`

**->** When I remove `launch(Dispatchers.Default)` it is working fine in native image

#### Setup
- GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
- Mac M1  (macOS 12.2.1)

**Comment by sdeleuze** [comment]
Seems unrelated to Spring Native and we are unlikely adding entries for `kotlin.internal.*` classes (since they are internal), so I would advise to create a non Spring repro with native image and submit a Kotlin issue asking if this reflection invocation could be avoided.

**Comment by Tonne-TM** [comment]
The issue will be investigated under this already existing Kotlin ticket:
https://youtrack.jetbrains.com/issue/KT-51579

Short term solution (which I grabbed from the official Ktor GraalVM example), add the following reflection config under `/src/main/resources/META-INF/native-image/reflect-config.json`

```json
[
  {
    "name": "kotlin.reflect.jvm.internal.ReflectionFactoryImpl",
    "allDeclaredConstructors":true
  },
  {
    "name": "kotlin.KotlinVersion",
    "allPublicMethods": true,
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  },
  {
    "name": "kotlin.KotlinVersion[]"
  },
  {
    "name": "kotlin.KotlinVersion$Companion"
  },
  {
    "name": "kotlin.KotlinVersion$Companion[]"
  },
  {
    "name": "kotlin.internal.jdk8.JDK8PlatformImplementations",
    "allPublicMethods": true,
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  }
]
```

**Comment by sdeleuze** [comment]
Thanks for the update.
