### ISSUE TITLE
Spring-Native conflict with spring.main.log-startup-info property in WSL

### ISSUE THREAD

**Issue by LtVaios** [spring-projects-experimental/spring-native#1652]
Although the property is set to: _**false**_ **_(spring.main.log-startup-info=false)_** in my application.properties and even if you print it out it, spring still says it is set to false, the native-image logs of my app print out the spring startup-info like it is set to _true._ The process I am following is:

> mvn clean

> mvn -Pnative -DskipTests package

> Run the native-image of my app in my WSL

Versions:

- Java 17
- spring-boot-starter-parent: 2.7.0
- spring-aot-maven-plugin: 0.12.0
- native-maven-plugin: 0.9.11
- WSL running: Ubuntu 20.04.4 LTS

**PS:** _If it has any meaning to the issue, I also tried doing the same with a very simple spring app too and this issue seems to persist._

**Comment by sdeleuze** [comment]
Please provide a reproducer to allow us to have a deeper look.

**Comment by LtVaios** [comment]
> Please provide a reproducer to allow us to have a deeper look.

- WSL running: Ubuntu 20.04.4 LTS

This app is as simple as it gets and also it includes an _Application Ready Listener_ which logs the property's value and it appears false. Although the property is false the spring-startup-info-logs still appear after starting the spring app. You can find it in:

 https://github.com/LtVaios/Spring-Rest-Service-Sample

**Comment by LtVaios** [comment]
Are there any updates on this issue?

**Comment by sdeleuze** [comment]
I can reproduce the issue, this is likely a side effect of the `SpringApplication` substitution defined [here](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-native/src/main/java/org/springframework/nativex/substitutions/boot/Target_SpringApplication.java) even if I was not able to identify exactly where this behavior come from.

But I tested this with Spring Boot 3 snapshots via https://github.com/spring-projects/spring-aot-smoke-tests which is not using anymore this substitution and it works as expected.

As we move most our efforts on Spring Boot 3 and upcoming milestone likely to provide a better native support than Spring Native itself, I will close this issue and recommend using Spring Boot 3 when available.
