### ISSUE TITLE
Enhancement - Where is the RegisterForReflection class level annotation?

### ISSUE THREAD

**Issue by srunnoe** [spring-projects-experimental/spring-native#1671]
Team,

While I do appreciate the annotation support that has been provided, it would be so much easier to denote at the class level as to whether or not it requires reflection at compile time. The beauty of annotated meta data is that you can reference it inline at the class level instead of having to cross reference between a configuration centric class and associated POJO that requires reflection. 

I see that quarkus has this feature and for good reason, please add to Spring Native. 
https://javadoc.io/doc/io.quarkus/quarkus-core/latest/io/quarkus/runtime/annotations/RegisterForReflection.html

**Comment by sdeleuze** [comment]
As we work on Spring Framework 6 and Spring Boot 3 builtin native support, Spring Native is in maintenance mode. If you want us to evaluate such annotation, please create a dedicated issue on Spring Framework project.
