### ISSUE TITLE
Add reflection hints for beans registered via Kotlin BeanDefinitionDsl

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects-experimental/spring-native#1680]
As of version `0.12.1` such bean definitions requires manual type hists:

```kotlin
val coroutinesInitializer: ApplicationContextInitializer<GenericApplicationContext> = beans {
    bean<ApplicationCoroutineScope>(destroyMethodName = "stop")
}
```

Workaround:

```kotlin
@TypeHint(
    types = [
        ApplicationCoroutineScope::class,
    ],
    typeNames = [
        "kotlin.internal.jdk8.JDK8PlatformImplementations",
    ],
    access = [TypeAccess.DECLARED_METHODS, TypeAccess.DECLARED_CONSTRUCTORS]
)
```

**Comment by mhalbritter** [comment]
Yes, this is not supported and won't be supported. Spring Boot 3 / Spring Framework 6 should find those beans IIRC. @sdeleuze what do you think?

**Comment by sdeleuze** [comment]
Yeah worth to check using latest Spring Framework 6 and Spring Boot 3 snapshots and raise issues if needed.

**Comment by vladimirfx** [comment]
This project is discontinued and development is continued in Spring Boot 3/ Framework 6?

**Comment by mhalbritter** [comment]
No, it's not discontinued. Spring Native is in minimal maintenance mode. We are currently investing our development time in AOT/native support in Spring Boot 3/Framework 6. But if there are serious issues in Spring Native, they will get fixed.
