### ISSUE TITLE
PathMatchingResourcePatternResolver failed to find resources by mask like `classpath:/db/migration/*.sql`

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects-experimental/spring-native#1681]
Resources are correctly included in the image and direct paths like `classpath:db/migration/V1__initial.sql` work as expected.

Usage code: 
https://github.com/nkonev/r2dbc-migrate/blob/master/r2dbc-migrate-resource-reader-spring/src/main/java/name/nkonev/r2dbc/migrate/reader/SpringResourceReader.java

**Comment by mhalbritter** [comment]
This is a known limitation of native-image. Classpath resources can't be enumerated in a native-image, see https://github.com/oracle/graal/issues/1108.

**Comment by mhalbritter** [comment]
For Spring Boot 3, we have to see how Flyway can be supported. One idea is to enumerate the files at build time, create an index file, and use that index file when loading flyway migrations on native image runtime.

**Comment by vladimirfx** [comment]
> For Spring Boot 3, we have to see how Flyway can be supported. One idea is to enumerate the files at build time, create an index file, and use that index file when loading flyway migrations on native image runtime.

I can file the PR with similar approach to R2DBC migration. Is there any ticket for Flyway to subscribe on?

**Comment by mhalbritter** [comment]
Yes, this one: https://github.com/spring-projects/spring-boot/issues/31999
