### ISSUE TITLE
Gradle AOT plugin removes generated sources that don't belong to it

### ISSUE THREAD

**Issue by edudar** [spring-projects-experimental/spring-native#1704]
I've been trying to figure out why my IDE does not recognize QueryDSL's Q classes. I see class files compiled from supposedly generated sources but no source files.

I found this issue [#623](https://github.com/spring-projects-experimental/spring-native/issues/623) where the fix was to take everything in "generated" and remove it recursively. That seems to be quite an overstep by the AOT plugin as it removes sources generated by other tools.

I'd suggest removing sources that belong to the AOT plugin only, such as starting with `aot` like `aotMain` and `aotTest`

To verify that, I created an empty dir `build/generated/testDir`, started the build, and my dir was gone.

**Comment by sdeleuze** [comment]
Sounds legit but as we focus on Spring Boot 3 native support, we prefer to use our bandwidth on this upcoming non-experimental support. I would suggest to double check that Spring Boot 3 snapshots provide the right behavior, you can create such project on https://start.spring.io/ and run for example `mvn -Pnative package`, should work out of the box with GraalVM 22.2 `native-image` installed locally.
