### ISSUE TITLE
Compilation fails with @EnableCaching annotation

### ISSUE THREAD

**Issue by agrancaric** [spring-projects-experimental/spring-native#1714]
Hello, I've seen there is an issue to introduce initial caching support (https://github.com/spring-projects-experimental/spring-native/issues/465) but I don't see this problem mentioned there so I am opening a new issue. When adding `spring-boot-cache-starter` and ehcache (didn't try other implementations) the task bootBuildImage fails with the following error:

`/Users/agrancaric/Projects/tmp/spring-native-cache-example/build/generated/runtimeSources/aotMain/org/springframework/cache/annotation/ContextBootstrapInitializer.java:24: error: cannot find symbol
              .invoke(beanFactory, (attributes) -> bean.setConfigurers(attributes.get(0)));
                                                       ^
  symbol:   method setConfigurers(Object)
  location: variable bean of type ProxyJCacheConfiguration
`

Version info: 'GraalVM 22.2.0 Java 11 CE'
Java version info: '11.0.16.1+1-LTS'

The project for reproducing the issue is here:

[spring-native-cache-example.zip](https://github.com/spring-projects-experimental/spring-native/files/9546743/spring-native-cache-example.zip)

**Comment by sdeleuze** [comment]
Caching on native is supported on Spring Boot 3 snapshots and related milestone, it will shortly take the relay of Spring Native experimental project.

I suggest you add a comment on https://github.com/spring-projects/spring-aot-smoke-tests/issues/40 asking for a `cache-ehache` sample.
