### ISSUE TITLE
spring-native version support consulting

### ISSUE THREAD

**Issue by mchgood** [spring-projects-experimental/spring-native#1717]
I found that some discussions in the issue mentioned that Spring Boot3 can solve the problem. As far as I know, the spring native project is currently an experimental version. In later versions, the minimum supported version of spring native is Spring Boot3?
for example：
[Compilation fails with @EnableCaching annotation ](https://github.com/spring-projects-experimental/spring-native/issues/1714#issuecomment-1246237539)
[Problem when using aspect with annotation pointcut](https://github.com/spring-projects-experimental/spring-native/issues/1712#issuecomment-1246240854)

**Comment by sdeleuze** [comment]
Spring Boot 3 will provide official native support out of the box that will replace Spring Native + Spring Boot 2.x with better compatibility.
