### ISSUE TITLE
Add Java 19 Support in AOT plugin

### ISSUE THREAD

**Issue by SentryMan** [spring-projects-experimental/spring-native#1723]
So I was planning to use the GraalVM dev build with JDK 19. but it seems the AOT plugin fails with this error 
 ```
←[31m←[1mjava.lang.IllegalArgumentException: Unsupported class file major version 63←[21m←[39m←[0m
←[3m    at sbg.asm.ClassReader.<init>(ClassReader.java:199)←[23m←[0m
←[3m    at sbg.asm.ClassReader.<init>(ClassReader.java:180)←[23m←[0m
←[3m    at sbg.asm.ClassReader.<init>(ClassReader.java:166)←[23m←[0m
←[3m    at org.springframework.nativex.type.TypeSystem.findType(TypeSystem.java:290)←[23m←[0m
```
To replicate, clone this guy https://github.com/SentryMan/Manga-Spring-Backend/tree/jdk19 then run a mvn clean package

**Comment by snicoll** [comment]
Thanks for the report but Spring Native is no longer maintained so we won't add Java 19 support to it. Please give that a try with the latest Spring Boot milestone and create an issue in Spring Framework if that still occurs. To get started check https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5
