### ISSUE TITLE
upgrade "cloud-function-* examples to spring boot 3.x deps and embedded native compilation support

### ISSUE THREAD

**Issue by cforce** [spring-projects-experimental/spring-native#1726]
Please upgrade "spring cloud function" based (serverless) examples to use latest spring boot 3 (graal) embedded native profile to  support Graal based native executable e.g for lambda with much improved startup times

https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws
https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-cloudevent
https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-netty

Or even better move those examples updated to the "spring cloud function" repo 

https://github.com/spring-cloud/spring-cloud-function/issues/938

**Comment by sdeleuze** [comment]
For that you should use directly Spring Boot 3 native support, see https://www.youtube.com/watch?v=TS4DpYSmfXk and https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5. Spring Boot 3 RC1 will be released tomorrow.
