### ISSUE TITLE
springci/spring-native:java11-0.12.x docker image doesn't run on new Mac M1

### ISSUE THREAD

**Issue by bittsi-app** [spring-projects-experimental/spring-native#1727]
Hi,

I need to build a Spring Cloud Function with AWS Custom Runtime project on M1 Mac using springci/spring-native:java11-0.12.x docker image as you mentioned in the [README.md], but the spring-native:java11-0.12.x docker image does not run on my M1 Mac.
Any suggestion on how can I resolve it?

Thank you!

**Comment by sdeleuze** [comment]
I am not on Mac, but looks like a general problem of running x86 Docker image on M1 which I guess is widely documented like [here](https://erica.works/docker-on-mac-m1/). https://www.graalvm.org/22.0/docs/getting-started/container-images/ can maybe help as well.
