### ISSUE TITLE
Issue with Spring Cloud Function 

### ISSUE THREAD

**Issue by paologazzola** [spring-projects-experimental/spring-native#1730]
Hi All,
I found this issue during the repackaging of my native app.

My environment is:
- jdk17
- maven 3.8.6
- graalVM 17

My Spring Boot project is
- maven/java
- spring boot version 2.7.5
- java 17
- dependencies:
  - Spring reactive web
  - Function
  - GraalVM Native Support

If I launch the command
`mvn -Pnative package`
I get this error during che analysis phase:
```
ERROR io.netty.handler.ssl.BouncyCastleAlpnSslUtils - Unable to initialize BouncyCastleAlpnSslUtils.
java.lang.ClassNotFoundException: org.bouncycastle.jsse.BCSSLEngine
```
My app is not able to be packaged and published. The error is generated by the Spring Cloud Function dependency.
I tried:
- exclude netty and put jetty;
- change JDK/GraalVM version;
- go back to previus version of spring boot/cloud.
with no success.

Is this a bug, or am I doing something wrong?

Thanks a lot!

**Comment by sdeleuze** [comment]
As the native support moves on Spring Boot 3 side, please test with Spring Boot 3 snapshots using https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.0.0-SNAPSHOT&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native,cloud-function by building the native application with `mvn -Pnative native:compile`, and if it fails create an issue on https://github.com/spring-cloud/spring-cloud-function/issues with a repro.
