### ISSUE TITLE
Not a managed type: class com.example.demo.domain.User Spring Boot

### ISSUE THREAD

**Issue by aidatynybekkyzy** [spring-projects-experimental/spring-native#1734]
I have an error: Not a managed type: class com.example.demo.domain.User 
Tried : @EntityScan ("com.example.demo.*")

Here's me project Not a managed type: class com.example.demo.domain.User 
i spent all day to solve(

**Comment by mhalbritter** [comment]
Hello,

Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details. 

Could you migrate your project to Spring Boot 3 and check if the native support in there solves your problem? If not, please report it on the Spring Boot issue tracker. Thanks a lot!
