### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Builder class `com.demo.Test$Builder` does not have build method (name: 'build')

### ISSUE THREAD

**Issue by dilipdhankecha2530** [spring-projects-experimental/spring-native#1735]
We face this issue while creating native build and may be this is because of jackson-databind dependency.

`@JsonDeserialize(
        builder = Catalog.Builder.class
)`
May be because of above one we face this issue.

**Comment by mhalbritter** [comment]
Hello,

Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details. 

Could you migrate your project to Spring Boot 3 and check if the native support in there solves your problem? If not, please report it on the Spring Boot issue tracker. Thanks a lot!
