### ISSUE TITLE
i use Visual Studio Community to build spring-boot:2.7 failure

### ISSUE THREAD

**Issue by huiji121** [spring-projects-experimental/spring-native#1741]
<img width="744" alt="WeChat685f06314f5b0d18104ab347ebee72c9" src="https://user-images.githubusercontent.com/24616352/209309808-1e0e8af6-75b5-429d-9077-461d89e53077.png">

**Comment by huiji121** [comment]
How can I solve this problem

**Comment by huiji121** [comment]
springboot:2.7.7
aot:0.12.1

**Comment by wangliang181230** [comment]
Downgrading springboot to version 2.7.5

**Comment by huiji121** [comment]
think you

**Comment by sdeleuze** [comment]
Duplicate of #1740.
