### ISSUE TITLE
spring native 0.12.0 was supported spring-data-elasticsearch?

### ISSUE THREAD

**Issue by Sanshimemeda** [spring-projects-experimental/spring-native#1748]

**Comment by mhalbritter** [comment]
I don't quite understand. Is there something which is not working?

**Comment by Sanshimemeda** [comment]
I want to convert my jar project into a native project, which uses elasticsearch and uses @Configuration to configure ElasticsearchRestTemplate

**Comment by Sanshimemeda** [comment]
When I package my project with nativeCompile and run the native image, it prompts that the bean of elasticsearchTemplate cannot be found

**Comment by mhalbritter** [comment]
Ah, thanks for the explanation. However:

Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.

**Comment by Sanshimemeda** [comment]
ok! thank you very much!
