### ISSUE TITLE
Ensure that sample web apps have endpoints and corresponding tests

### ISSUE THREAD

**Issue by sbrannen** [spring-projects-experimental/spring-native#177]
In order to ensure that web applications in `spring-graalvm-native-samples` are testable and properly tested (at least with a simple in-container smoke test), we should do the following.

1. Ensure that each web app has at least one web endpoint.
2. Ensure that an in-container integration test is in place.

An "in-container integration test" is a test class annotated with `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)` -- instead of simply `@SpringBootTest` -- with at least one `@Test` method that connects to and validates the response from an endpoint via  `TestRestTemplate` or `WebTestClient`.

Launching the embedded container (e.g., Tomcat) also ensures that the type of `ApplicationContext` used in the integration test is the same as the one used when the application is launched within a native image, which helps the GraalVM native image JVM agent to better analyze what will be needed in the compiled native image.

For example, `springmvc-tomcat` already fulfills requirement # 1 due to the existence of the [`Controller`](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-samples/springmvc-tomcat/src/main/java/com/example/tomcat/Controller.java); however, [`AppContextStartupTest`](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-samples/springmvc-tomcat/src/test/java/com/example/tomcat/test/AppContextStartupTest.java) does not fulfill requirement # 2 since it does not start the embedded Tomcat container or test the `Controller` endpoint over HTTP.

**Comment by sdeleuze** [comment]
@sbrannen Any chance you could take care of it?

**Comment by sbrannen** [comment]
I'll see if I can fit this in next week.

**Comment by sdeleuze** [comment]
Let's move that on to 0.9.1 which will have a focus on tests.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
