### ISSUE TITLE
Provide a dev-oriented image usable with Paketo Buildpacks

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#227]
As a follow-up of #165, It should be possible to build dev-oriented images with Paketo buildpacks in order to allow end-users to open a shell, debug with GDB (see related #154 issue), etc. In practice, it should replace [`run-dev-container.sh`](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/run-dev-container.sh) while keeping a great dev experience.

It should probably be a new implementation of `io.buildpacks.stacks.bionic` with some mixins to be designed with the help of @nebhale.

**Comment by nebhale** [comment]
Post SpringOne, reach out to me and we can design this experience.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
