### ISSUE TITLE
Spring cloud. No access hint found for import selector for ImportAutoConfigurationImportSelector

### ISSUE THREAD

**Issue by mostafacs** [spring-projects-experimental/spring-native#239]
Hello,

I have microservices implemented with spring cloud and I got this error when trying to build Graal-VM native image : 

`
        Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: No access hint found for import selector: 
        org.springframework.boot.autoconfigure.ImportAutoConfigurationImportSelector
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)`

spring cloud dependencies:

` 

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement> `

`

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>`

Spring Boot parent:
`

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
    </parent>`

I'm using this build options.

```<profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.nativeimage</groupId>
                        <artifactId>native-image-maven-plugin</artifactId>
                        <version>20.1.0</version>
                        <configuration>
                            <buildArgs>-J-Xmx4G -H:+TraceClassInitialization -H:+ReportExceptionStackTraces
                                -Dspring.graal.remove-unused-autoconfig=true -Dspring.graal.remove-yaml-support=true
                            </buildArgs>
                            <imageName>${project.artifactId}</imageName>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
   </profiles>```

**Comment by aclement** [comment]
Please be aware we have done limited testing of Spring Cloud applications at this time. There is a hint for ImportAutoConfiguationImportSelector, I can see it here:
```
@NativeImageHint(trigger=ImportAutoConfigurationImportSelector.class, typeInfos={
		@TypeInfo(types= { 
				ImportAutoConfiguration.class }, typeNames = {
				"org.springframework.boot.autoconfigure.test.ImportAutoConfiguration" 
			})},modes= {Mode.REFLECTION,Mode.AGENT}
)
```
Are you using an up to date spring-graalvm-native dependency? I wonder if you are using an older version that didn't include this hint.  If so, did you follow the troubleshooting guide to turn down the error to a warning to try and progress? see the option in this section: https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-docs/src/main/asciidoc/troubleshooting.adoc#no-access-hint-found-for-import-selector-xxx

(If you do try with the latest Spring-GraalVM-Native you will need to upgrade to Boot 2.4.0-M2)

**Comment by sdeleuze** [comment]
Closing this one due to the lack of feedback.
