### ISSUE TITLE
Add support for Undertow and Jetty

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#249]
On both Spring MVC and WebFlux.

**Comment by onexuan** [comment]
Will the new progress now?

**Comment by sdeleuze** [comment]
This is now tracked by related Spring Boot 3 issues in https://github.com/spring-projects/spring-aot-smoke-tests/issues/50 and https://github.com/spring-projects/spring-aot-smoke-tests/issues/58, as a consequence I close this issue.
