### ISSUE TITLE
Make petclinic working in functional mode

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#258]
Including with Spring MVC annotation infra if possible. cc @aclement @dsyer

**Comment by sdeleuze** [comment]
@dsyer Should we close that one?

**Comment by dsyer** [comment]
Your call. It’s not working with `@MVC` yet.

**Comment by sdeleuze** [comment]
Does not make sense anymore due to #347, this issue is superseded by #386.
