### ISSUE TITLE
spring-cloud-alibaba And org.springframework.cloud 

### ISSUE THREAD

**Issue by mpv945** [spring-projects-experimental/spring-native#334]
When can we support it

**Comment by mpv945** [comment]
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.cloud.netflix.ribbon.RibbonAutoConfiguration.loadBalancedRetryPolicyFactory(org.springframework.cloud.netflix.ribbon.SpringClientFactory) 
Parsing context:
	parsing com.oracle.svm.reflect.RibbonAutoConfiguration_loadBalancedRetryPolicyFactory_0c3c944c7cf77230fa6ef221bb48839eea50c051_3642.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:498)

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
