### ISSUE TITLE
Turn the GraalVM feature into a pure build time transformation generating JSON configs

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#344]
As part for this issue we should also:
 - Begin to make GraalVM specific codepath isolated to prepare Project leyden support
 - Find a good package since `native` that would have been idea is a Java reserved keyword

This change will improve debugability and should should use this opportunity to improve unit test coverage.

**Comment by aclement** [comment]
This is in good shape. I refactored the feature to separate the 'analysis' that computes the configuration from its GraalVM interactions. The GraalVM feature is loosely coupled to the analysis engine and the analysis engine has a collector framework on the backend. There is a default collector that just accumulates computed configuration in java collections, but optionally you can plug in a GraalVM connector that passes that to GraalVM native image.

So the same analysis engine is now used by the feature and by the build time configuration contributor. There is more refactoring to do but this initial work is behaving for a number of samples.
