### ISSUE TITLE
Generate a programmatic version of spring.factories at build time

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#345]
We should replace the hardcoded [SpringBootFactories](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-substitutions/src/main/java/org/springframework/boot/SpringBootFactories.java) by a version that will be generated at build time by scanning the `spring.factories` in the classpath.

As described in https://github.com/spring-projects/spring-boot/issues/23985#issuecomment-720140728 we should ensure this is someting automatic and maintainable so there may be challenges for `ConfigDataLocationResolver`, `EnvironmentPostProcessorsFactory`, etc.

It should be possible to plug it to `SpringFactoriesLoader` via a substitution.

**Comment by bclozel** [comment]
Fixed with 5f94fd4674d15a151
