### ISSUE TITLE
Introduce the build time transformation infrastructure

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#346]
We should introduce a build time transformation infrastructure to `spring-graalvm-native` that will materialize for the user as Maven and Gradle plugins (without the need for a dependency on external projects like `spring-init`).

This infra will be used for a wide range of build time optimizations, for example::
 - Automatically set optimization flags #225
 - Remove the need for class resources #341
 - Turn the GraalVM feature into a pure build time transformation generating JSON configs #344
 - Generate a programmatic version of spring.factories at build time #345

A starting point with the Maven plugin has been created by @dsyer [here](https://github.com/dsyer/spring-graalvm-native/tree/proxyBeanMethods) with some insights shared by @aclement about how to improve it:
> I thought we’d be closer to those if the subclasses you generated implemented BeanFactoryAware (and so had a setBeanFactory method) and then called that from the overridden @ Bean methods to check if a bean already existed - that’s what those CGLIB proxies do.

The target should probably be at some point inclusion in Spring Framework and seamless usage by Spring Boot Maven and Gradle plugins.

**Comment by sdeleuze** [comment]
@christophstrobl Do you want to create a dedicated issue to incubate Spring Data build time transformations you are experimenting on, like I did for the issues mentioned in this issue? The idea would be to plug them intro Spring Data with substitutions for now.

**Comment by christophstrobl** [comment]
@sdeleuze Not right away.
For the time being tend to stick to the SpringDataComponentProcessor and continue our investigation in a dedicated project under Spring Experimental. Generated/provided entity metadata is a use case, not limited to GraalVM native images, that might turn out to be beneficial in everyday projects.

**Comment by sdeleuze** [comment]
@christophstrobl OK, feel free to integrate this experimental Spring Data project here with a dedicated issue/PR when you feel it is ready.

**Comment by bclozel** [comment]
The first version of the build time infrastructure was introduced in 5f94fd4674. We're refining this arrangement with other issues.
