### ISSUE TITLE
Check why Java 11 sometimes has a bigger footprint than Java 8

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#363]
Follow-up of #350.

**Comment by sdeleuze** [comment]
I did a detailed diff between Java 8 and Java 11 on `webmvc-tomcat` and most differences seems just due to a richer API, inclusion of `jdk.internal.org.objectweb.asm.*`. The difference is likely amplified by our usage of reflection on configuration file, so #386 could reduce the pain.

`org.jcp.xml.dsig.internal.dom.ApacheTransform` seems also to trigger the loading of a bunch of XML classes, point raised to the GraalVM team.

**Comment by aclement** [comment]
Yes, in looking at diffs, ApacheTransform and ApacheCanonicalizer stick out as things in 11 builds that aren't in 8. commandlinerunner shows over 1000 extra 'things' in an 11 built image. It is almost as if there is some XML file somewhere in 11 that isn't in 8 that pulls in the infrastructure to load it.

**Comment by sdeleuze** [comment]
After a detailed analysis with the GraalVM team, it seems the related work need to happen on GraalVM side, see https://github.com/oracle/graal/issues/3162 and https://github.com/oracle/graal/issues/3163 related issues.
