### ISSUE TITLE
Automatically configure resources from src/main/resources

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-native#374]
hi

i have some resources in classpath (database sql schema, assets, ....) so native image created with success but when launch it exceptions appear (resources not found) however when try to execute fat jar its work fine 

i use spring boot 2.4.0 (kofu), graal maven plugin 20.3, graalvm 20.3.0 (based on java 8)

**Comment by sdeleuze** [comment]
@aclement @bclozel @dsyer What about adding a build time transformation that create the right GraalVM resource config that includes by default project `src/main/resources/**`?

**Comment by halimpuckjava** [comment]
@sdeleuze 

its good idea

**Comment by halimpuckjava** [comment]
@sdeleuze 

i hope to fix this issue in next version of spring native image (0.9.0)

**Comment by sdeleuze** [comment]
Yeah I think that's a simple one that would bring a lot of added value.

**Comment by sdeleuze** [comment]
Warning from @aclement : risk of shipping indirectly resources in JARs with similar path. I am not sure yet this is a blocking issue. That said do we have ways to avoid this? Not sure.

**Comment by AndersClausen** [comment]
Hi @sdeleuze @aclement I've got a bit of a different setup to @halimpuckjava however I've got a similar problem that a public/private key-pair in the src/main/resources folder aren't loaded at runtime.

I use spring boot 2.4.1, spring-graalvm-native 0.9.0-SNAPSHOT and create my native image by running `mvn spring-boot:build-image` (spring-boot-maven-plugin).

This is how we're currently loading those files from the classpath
`IOUtils.toByteArray(new ClassPathResource(filename).getInputStream());`
Is that alright or do we need to do it differently?

Really appreciate your opinion on this. Cheers

**Comment by dsyer** [comment]
This issue is unresolved so you would have to configure the resource access yourself (in `META-INF/native-image/resource-config.json`). There are some examples in the samples in this project.

**Comment by AndersClausen** [comment]
Thanks @dsyer, your reply is much appreciated!

**Comment by aclement** [comment]
A first pass of this is now implemented *for the build time infrastructure mode*, not for the feature mode.

**Comment by sdeleuze** [comment]
I think that's fine since we are to keep only the build time infrastructure mode for 0.9.0.
