### ISSUE TITLE
Fix @ConstructorBinding on non nested class

### ISSUE THREAD

**Issue by fer-marino** [spring-projects-experimental/spring-native#382]
Hi everybody,
I have the following application: https://github.com/fer-marino/spring-native-issue

It is a spring boot 2.4 kotlin application that is supposed to be used from command line. It uses an application.yml file located in the classpath and mapped to data classes via the @ConfigurationProperty annotation. This works fine on the JVM but it doesn't with graal native. The application compiles fine but when it start, it fails with a classic error saying it can't bind yml file to object properties. 

```***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target [Bindable@25f04156 type = java.util.List<org.eumetsat.coda.maintenance.configuration.CodaInstance>, value = 'none', annotations = array<Annotation>[[empty]]] failed:

    Property: coda.instances[0].description
    Value: OFL Primary Backend
    Origin: class path resource [application.yml] - 7:18
    Reason: The elements [....] were left unbound```

**Comment by sdeleuze** [comment]
I can reproduce it with 0.8.4, maybe a `@ConstructorBinding` support related issue?

**Comment by fer-marino** [comment]
it is a possibility, as that annotation relies on reflection to infer the constructor to bind to. Unfortunately I have no experience with graal and I don't know how to proceed. 
After a quick check anyway I can tell you that I see support for `@ConstructorBinding` annotation in this project, but I don't see support for `org.springframework.core.KotlinDetector` which is used here. Maybe this is kotlin specific?

**Comment by jimbethancourt** [comment]
I'm running into a similar problem with a Java application and nested yaml properties.  I can work around it to some extent, but it's not always the easiest to figure out how.

**Comment by sdeleuze** [comment]
@jimbethancourt Could you please provide some details on the workaround you are using?

**Comment by jimbethancourt** [comment]
Hi @sdeleuze,
You bet - I'll put something together tonight. 

Thanks,
Jim

**Comment by jimbethancourt** [comment]
Hi @sdeleuze 
I didn't have an opportunity to put something together tonight - I'll try to put something together very soon.

Short and sweet version is that I need to
1) Specify the top level prefix in the @ConfigurationProperties(prefix = "my.properties") for a parent class
2) Specify nested prefixes in the @ConfigurationProperties(prefix = "my.properties.that-are-nested") for a child class
3) Declare the child class as a member of the parent class, and then inject it.

Without Spring Native, the child object is created without issues.  With Spring Native, I need to use a hierarchical approach.

Thanks,
Jim

**Comment by sdeleuze** [comment]
This bug happens because only nested types are registered automatically, not the one returned by the getter.

**Comment by sdeleuze** [comment]
@aclement I can reproduce it with the following modified `boot-features` sample and have crafted a draft fix for it (it fixed the issue) by adding configuration for return types instead of nested types, see https://github.com/sdeleuze/spring-native/commit/non-nested-configuration-properties. Could you provide me some guidance and/or take it from there?

Notice that with the log I added I see that a lot (all?) properties are processed, whatever we use them or not. So I see reflection entries for properties like `ArtemisProperties`. I have the feeling that we don't filter out the `@EnableConfigurationProperties` on excluded auto-configurations. Should I create an issue for that, and if yes, for which version?

**Comment by jimbethancourt** [comment]
@sdeleuze and @aclement do you need the sample I mentioned?  I apologise for not getting it to you yet.

**Comment by sdeleuze** [comment]
@jimbethancourt No need for the repro thanks.

**Comment by sdeleuze** [comment]
I will discuss with @bclozel tomorrow to try to define a reasonable and reliable implementation strategy.

**Comment by fer-marino** [comment]
sorry but my project still not run, even with the latest 0.9.1 version and spring boot 2.4.4. New error anyway: 

`java.lang.ClassNotFoundException: java.util.List
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60) ~[na:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:281) ~[na:na]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType(KDeclarationContainerImpl.kt:267) ~[na:na]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadParameterTypes(KDeclarationContainerImpl.kt:258) ~[na:na]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findConstructorBySignature(KDeclarationContainerImpl.kt:229) ~[na:na]
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:67) ~[na:na]
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:36) ~[na:na]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62) ~[na:na]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[na:na]
        at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt) ~[na:na]
        at kotlin.reflect.jvm.ReflectJvmMapping.getJavaConstructor(ReflectJvmMapping.kt:71) ~[na:na]
        at org.springframework.beans.BeanUtils$KotlinDelegate.findPrimaryConstructor(BeanUtils.java:827) ~[na:na]
`

**Comment by sdeleuze** [comment]
@aclement Do you think we should reopen this issue?

**Comment by aaronriekenberg** [comment]
I had the same issue as @fer-marino .  For me putting:

```
  {
    "name": "java.util.List"
  },
```

into `refect-config.json` solved this issue.

**Comment by aclement** [comment]
I've tweaked the configuration properties processing a little and the case I could recreate as failing is now working.

**Comment by AndreKoepke** [comment]
Same problem here with Spring 3.0.0, java-properties and gradle. I didn't found an option to set a "refect-config.json".

https://github.com/AndreKoepke/home-system/blob/9d35fc9c6e5fc6d7234ee871134902246c61e695/src/main/java/ch/akop/homesystem/config/properties/HomeSystemProperties.java#L35

Can I fix that without refactoring all configs classes?
