### ISSUE TITLE
Reduce the need for reflection by using functional configuration

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#386]
Leveraging @dsyer work on https://github.com/spring-projects-experimental/spring-init. The scope is not to be 100% reflection-less but rather to limit the amount of reflection to lower the footprint and increase the compatibility. Reflection will typically remain for `@Controller` etc.

**Comment by sdeleuze** [comment]
See related https://github.com/spring-projects/spring-framework/issues/18353#issuecomment-769078694 comment.

**Comment by SentryMan** [comment]
So I'm a bit confused, will Spring-Init be merged with the AOT Plugin, or remain separate? I notice it hasn't been updated in a while.

**Comment by dsyer** [comment]
Many of the ideas in Spring Init have been incorporated into the AOT plugin. It's not clear that Spring Init is adding very much at this point, so I suppose the answer is "we don't know". It might be slightly faster in a regular JVM still, but that's without doing much optimization of the AOT generated code. If you are actually using Spring Init and would like to provide feedback, no decision has been made, so go ahead.

**Comment by SentryMan** [comment]
I'm trying to make my spring app run with native image with AOT, but I'm seeing a leak somewhere when I don't use the Init Plugin to create functional bean registrations.

**Comment by sdeleuze** [comment]
The first bits have been introduced in https://github.com/spring-projects-experimental/spring-native/tree/0.11.x with the AOT generation of a `ContextBootstrap` which looks like that:

```
public class ContextBootstrap implements ApplicationContextInitializer<GenericApplicationContext> {
  public void initialize(GenericApplicationContext context) {
    context.registerBean("commandlinerunnerApplication", CommandlinerunnerApplication.class, CommandlinerunnerApplication::new);
    context.registerBean("CLR", CLR.class, CLR::new);
    org.springframework.boot.autoconfigure.ContextBootstrap.registerBasePackages(context);
    context.registerBean("org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration", PropertyPlaceholderAutoConfiguration.class, PropertyPlaceholderAutoConfiguration::new);
    context.registerBean("propertySourcesPlaceholderConfigurer", PropertySourcesPlaceholderConfigurer.class, () -> PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer());
    org.springframework.boot.autoconfigure.aop.ContextBootstrap.registerClassProxyingConfiguration(context);
    org.springframework.boot.autoconfigure.aop.ContextBootstrap.registerForceAutoProxyCreatorToUseClassProxying(context);
    context.registerBean("org.springframework.boot.autoconfigure.aop.AopAutoConfiguration", AopAutoConfiguration.class, AopAutoConfiguration::new);
    // ...
  }
}
```
I will create more fine grained issues to track our progresses.

**Comment by sdeleuze** [comment]
Let's close this one as the base mechanism is now used and continue with more 0.11 fine grained issues as we migrate other samples.
