### ISSUE TITLE
com.sun.proxy.$Proxy cannot be cast with latest version 

### ISSUE THREAD

**Issue by VuDo98** [spring-projects-experimental/spring-native#394]
Reopen of ticket #331 

Hi @sdeleuze I am still seeing this error with the same previous one with spring graalvm 0.8.3, graalvm 20.3, and spring cloud deps 2020.0.0-SNAPSHOT follow the example in samples. Log `build with agent + test.txt` is attached. I am not sure if I can reproduce this on a minimal because I tried to run a minimal config on the discovery client sample but it gave me error like log `discoveryclient sample error.txt`. I am not sure how to reopen this ticket as well since I don't have permission

update:
I ran it with agent + SpringBootTest and get the error as log 1.
If I commented the test class, it build successfully but I get the same error at startup.
I also tried cloud dep Hoxton.SR9 with the agent but apprently the spring boot test in there use old cloud context so agent weren't able to introspect class `org.springframework.cloud.context.properties.ConfigurationPropertiesBeans` and `org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata`

[build with agent + test.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611820/log.1.txt)
[build with agent successful but startup failed log.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611856/startup.log.txt)

[discoveryclient sample error.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611821/log.2.txt)
[discoveryclient.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611829/discoveryclient.zip)

[Hoxton.SR9 log.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5612773/Hoxton.SR9.log.txt)

**Comment by sdeleuze** [comment]
Potentially related to the fact we force JDK proxies in all circumstances as pointed out by @aclement.

**Comment by VuDo98** [comment]
Ok I wait till the beta for this issue to be fixed. Thank you

**Comment by sdeleuze** [comment]
Should be fixed by #355.
