### ISSUE TITLE
Dev Environment best practices

### ISSUE THREAD

**Issue by bnau** [spring-projects-experimental/spring-native#418]
Hi everyone,

I don't know if it's the right place to ask this question. 

I have tested some of the samples with the three suggested ways (building an image from Maven/Gradle, running build.sh, running run-dev-container.sh). Everything works perfectly! 

However, when I edit a single line of code, a complete rebuild will be triggered, which can be an issue in a development context as the process is quite long. Am I missing a configuration or is it a normal behaviour? Or maybe is it usual to develop with the traditional JDK and use native images for the releases?

**Comment by aclement** [comment]
It is normal that native-image takes a long time - more RAM will speed it up, more optimized config will speed it up - the latter of which I think we are gradually working on in this project, but it isn't going to get you down to build times of a few seconds.

You are trading off instant startup of the deployable artifact for costly build times. Right now you are correct that you might only do the native-image build for your final release artifact. Of course that doesn't verify that your artifact works perfectly (was their missing native image config perhaps?) so we are working on a better story about running your tests against the artifact.  There *are* potential improvements coming up to improve build times - for example you can imagine it storing the analysis of certain classpath jars so it doesn't repeat it every time, but that is some way off I think.

This is why where we've integrated the native-image step into a sample (via the native-image maven plugin or via buildpacks) it is optional and you have to ask for it, it doesn't happen on just your average `mvn clean package` build.

**Comment by bnau** [comment]
Thanks a lot for your answer! I wanted to be sure that there were no better alternative.

Anyway, switching between traditional Java and native image for development is a reasonable option.
