### ISSUE TITLE
Actuator prometheus endpoint not get registered

### ISSUE THREAD

**Issue by dbuos** [spring-projects-experimental/spring-native#423]
When I build the app with the "io.micrometer:micrometer-registry-prometheus" dependency, this is supposed to enable prometheus scrapping endpoint, (when I run the jar in JVM it is).

But when I run the binary generated by graalvm native-image feature the prometheus endpoint is not registered and not available.

**Comment by sdeleuze** [comment]
@aclement Could you please have a look to this one when you have some time?

**Comment by aclement** [comment]
Sorting out the exact configuration to make it work is a long job.  But I have confirmed it works fine if you use the agent to collect the full configuration and build with that.

**Comment by sdeleuze** [comment]
Let's move that one to 0.9.1.

**Comment by sdeleuze** [comment]
Ok we can probably add that hint in 0.9.2 then, thanks for the exploratory work.

**Comment by GregoireW** [comment]
I also added heath endpoint and info endpoint. Both are not discovered by default. 

I had to add

```json
  {
    "name":"org.springframework.boot.actuate.health.HealthEndpoint",
    "allDeclaredFields":true,
    "allDeclaredMethods":true
  },
  {
    "name":"org.springframework.boot.actuate.info.InfoEndpoint",
    "allDeclaredFields":true,
    "allDeclaredMethods":true
  }
```

**Comment by prettymama** [comment]
Seems that metrics endpoint works only with this configuration
```
{
  "name":"org.springframework.boot.actuate.metrics.MetricsEndpoint",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
},
{
  "name":"org.springframework.boot.actuate.metrics.MetricsEndpoint$MetricResponse",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
},
{
  "name":"org.springframework.boot.actuate.metrics.MetricsEndpoint$Sample",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
},
{
  "name":"org.springframework.boot.actuate.metrics.MetricsEndpoint$AvailableTag",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
},
{
  "name":"org.springframework.boot.actuate.metrics.MetricsEndpoint$ListNamesResponse",
  "allDeclaredFields":true,
  "allDeclaredMethods":true
}
```

**Comment by aclement** [comment]
@GregoireW:
Thanks for trimming down that config. I've added a hint for the `PrometheusScrapeEndpoint` and upgraded the `actuator-webmvc` sample to verify it is reachable.
I've also added a hint for the info endpoint and upgraded `actuator-webmvc` sample.
I did not add a hint for the health endpoint, that's already covered, not quite sure why you had to add it? Let's deal with that in another bug if still a problem. (The `actuator-webmvc` hits the health endpoint in its testing)

@prettymama
I've also added those to the metrics endpoint hints we already had (and expanded `actuator-webmvc` to test it).

Now with all these changes I am verifying the endpoints are reachable, not verifying all potential data is available for the endpoints. Please raise new issues for further data within these that looks to be missing.

**Comment by GregoireW** [comment]
@aclement Out of curiosity, what did you add (and where) to have those hint ? there is no `reflect-config.json` in spring aot but in the end there is a generated file. (too lazy to check that today)

anyway I checked, Not sure why I put the health endpoint. It was working from the start.

I check quickly and 0.9.2-SNAPSHOT fixes the issue. Thank you
