### ISSUE TITLE
r2dbc-mariadb issues

### ISSUE THREAD

**Issue by grekier** [spring-projects-experimental/spring-native#439]
Hi.

Not sure if it is the right place to add this but it shows up only on native image build so...

There is an issue I have been facing when trying to build an image with r2dbc-mariadb: It didn't build at all.

When digging a bit, it seems to be related to XML classes that shouldn't have been created at build time. This seems to come from logback. 
Updating to r2dbc-mariadb version 1.0.0 (and not using the one from the bom which is 0.8.4-rc removed this error). 
It seems that the older version has a logback-test.xml file in the root of the jar that I suspect is the problem here. However, I didn't dig deeper since updating resolved the issue.

Though I'd post it here so someone having the same issue might find it and update of the dependency might be picked up.

**Comment by grekier** [comment]
I've had some authentication issues as well using the driver with native build that I haven't been able to figure out. However, switching to 
```
<dependency>
    <groupId>dev.miku</groupId>
    <artifactId>r2dbc-mysql</artifactId>
</dependency>
```
works fine

**Comment by sdeleuze** [comment]
Please create a new issue with a proper repro project if there is still a relate dissue.
