### ISSUE TITLE
Is Infinispan supported with Spring GraalVM?

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#443]
I was just wondering if Infinispan is meant to be supported by Spring GraalVM, as it is supported in Quarkus (https://infinispan.org/blog/tags/graalvm/)

**Comment by sdeleuze** [comment]
Not yet, but worth [to ask them](https://issues.jboss.org/browse/ISPN) when 0.9.0 will be released since they maintain Spring Boot integration.

**Comment by khaeghar** [comment]
https://issues.redhat.com/browse/ISPN-12621

I'll add here the thread open in the redhat Jira.

Thanks for the info!
