### ISSUE TITLE
Runtime error when upgrading to Spring Boot 2.4.2

### ISSUE THREAD

**Issue by AndersClausen** [spring-projects-experimental/spring-native#446]
Hi

I'm running spring-graalvm-native 0.9.0-SNAPSHOT, Spring Boot 2.4.2 and java 11.0.9 AdoptOpenJDK.
mvn spring-boot:build-image completes successfully and when I run the docker image I get the error below.

```/workspace/com.shipment.security.AuthApplication: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory```

I'm not sure if this is a spring-graalvm-native issue or a spring boot one - it does look to me that it could be a buildpack issue, so please let me know if I should raise it with spring boot instead. Cheers

**Comment by sdeleuze** [comment]
Yeah sorry for that breakage, we are aware of that and are working on a fix that will be available shortly on buildpack side, see https://github.com/spring-projects-experimental/spring-native/issues/432#issuecomment-760997377 related comment. I will close this issue when it will be fixed.

**Comment by AndersClausen** [comment]
Please don't be sorry, I'm just happy that it's a known problem :-) Thanks for taking the time to confirm it though 👍🏻

**Comment by sdeleuze** [comment]
This is now fixed.
