### ISSUE TITLE
The dependencies of some of the beans in the application context form a cycle

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#449]
Hi,

the problem I have is the following:

I do an injection of a bean in a service impl class:

```
...
@Autowired
ConnOp opImpl;
...
```
Then I have two dependencies with two definitions of that bean:

Dependency 1:  dependency1.config.AutoConfig

```java
@Bean
@Conditional(...)
public ConnOp myAppConn(){
   return new ConnSwitch();
}
```

Dependency 2:  dependency2.config.AutoConfiguration

```java
@Autowired
  @Bean
  @ConditionalOnMissingBean
  public ConnOp ConnectOperations(...) {
    return (ConnOp)new ConnTemplate(...);
  }
```

The class runs perfectly in a JVM environment, but when I run the native compiled version of the service, the following error appears:

```
**************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   myEntityService (field dependency1.ConnOp dependency2.ConnOp)
┌─────┐
|  dependency1.config.AutoConfig
↑     ↓
|  dependency2.autoconfigure.AutoConfiguration
└─────┘

```

Is it possible that due to the nature of GraalVM and ahead-of-time compilation both beans are initialized at the same time and therefore creating that cycle? Or am I missing something?

I'm sorry for asking this but my expertise here it's limited and it's the first time I deal with something like this :sweat:

**Comment by sdeleuze** [comment]
I don't think GraalVM native images should change something at that level, but a difference is that bean dependencies are supported only with parameter injection, see [this link](https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.5/spring-graalvm-native-docs-0.8.5.zip!/reference/index.html#_limitations) for more details.

We also have a mechanism that should detect unsupported patterns and throw an error, so the case you see is not expected to happen I think.

Could you please share a repro project to allow us to see exactly what happens?

**Comment by sdeleuze** [comment]
Closing this one due to the lack of feedback.
