### ISSUE TITLE
Examples Project (webmvc-tomcat) compile.sh  works well on linux， wondering how to compile single exe on windows

### ISSUE THREAD

**Issue by pubxun** [spring-projects-experimental/spring-native#452]
I tried to simply use 

~~~
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community>native-image -jar mysql-mate-panel-1.0.0.jar
~~~

It fall back to a need JDK exe ， I Wondering how to compile  “examples Project webmvc-tomcat” to a  single exe on windows

Thank you

**Comment by sdeleuze** [comment]
This will be documented in the next version, you can check https://github.com/spring-projects-experimental/spring-native/commit/87fa2811d2228f4b05f745ddcf95391b6c94894f for now.
