### ISSUE TITLE
build time infrastructure problem with running tests

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#456]
The `vanilla-thymeleaf` sample has the necessary profile in the pom to create a native-image using build time infrastructure. However it currently fails running the tests (before the image is constructed):

```mvn -Pbti-native clean package```

```
java.lang.NullPointerException
	at hello.ApplicationTests.homePage(ApplicationTests.java:34)
```

If you skip tests, it will build the image ok:

```mvn -DskipTests -Pbti-native clean package```

**Comment by bclozel** [comment]
Is this about the `webflux-thymeleaf` sample?

Right now the JVM version works fine, but the native image throws:

```
➜  webflux-thymeleaf git:(master) ✗ ./target/webflux-thymeleaf
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:284)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at hello.Application.main(Application.java:10)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1260)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:460)
	... 7 more
```

I'm not sure why this is the case since we're generating the same code as in other samples (which are fine):

```
    factories.add(ApplicationContextInitializer.class, () -> org.springframework.boot.autoconfigure._FactoryProvider.sharedMetadataReaderFactoryContextInitializer());
```

```
package org.springframework.boot.autoconfigure;

public abstract class _FactoryProvider {
  public static SharedMetadataReaderFactoryContextInitializer sharedMetadataReaderFactoryContextInitializer(
      ) {
    return new SharedMetadataReaderFactoryContextInitializer();
  }
}
```

The `ApplicationContextInitializer.class` instances are accessed and instantiated via reflection, should we generate reflection data no matter what?

**Comment by aclement** [comment]
Things seem to have shifted with the recent changes. Digging into it - yes I meant `webflux-thymeleaf`, sorry I was using the original name :) 

Feature mode native-image works fine. bti-native doesn't work. But not with the error you show:
```
curl -s localhost:8080/greeting
{"timestamp":"2021-02-01T18:22:27.547+00:00","path":"/greeting","status":404,"error":"Not Found","message":null,"requestId":"c2755e96-1"}%
``` 
which smells of configuration issue. So that's progress and I can work on fixing this.

For your error, I'm not sure why you got that. If createSpringFactoriesInstances is on the stack and doing a forName() - doesn't that suggest it hasn't got the generated code on the classpath (either the replacement class for factory loading not first on the classpath or the substitution not kicking in), hmm.

**Comment by bclozel** [comment]
I was testing that on a local branch, so I might have broken something then. I'll keep digging into this and other related issues.

**Comment by aclement** [comment]
I was just trying some other samples, no longer seeing NPE in tests but a new similar kind of thing when I run the apps. I wonder if there is now one common problem - the one I describe in https://github.com/spring-projects-experimental/spring-native/issues/457

**Comment by bclozel** [comment]
I guess you're right.
With 775644bbbb01e3cd6280083d97aa8d7d11c0331e, I've moved the build-time infrastructure to the pre-package phase (meaning tests aren't running with the generated code for now) - I'm working on calling the infrastructure in the "process-test-classes" specifically for tests. I guess we can close this issue once that last part is done. I'll keep working on #457 as well.

**Comment by aclement** [comment]
Just a random bit of thinking. I had an idea for running tests with a generated spring factories and yet avoiding including the test infrastructure in the image. You could generate the StaticSpringFactories for the full (app+test classpath) but within it have something aware of the difference (maybe?):
```
class StaticSpringFactories {
...
   doStuff() {
     ...
     factory.register()
     factory.register()
     if (!IN_NATIVE_IMAGE) {
        factory.registerATestThing()
     }
   }
}
So the test stuff in the generated classes is all discarded when the image is constructed. Although I suppose I'm not sure if native-image will recognize it doesn't need the test classpath entries, hmm. Obviously you'd need to be able to identify which are test things and which are not, maybe that makes it difficult.

I think it is valuable running tests with generated code to verify that code is OK.

**Comment by aclement** [comment]
I've fixed the `webflux-thymeleaf` sample. The remaining problem was that it didn't use the spring-content-indexer so no components are found. Fixing the pom made the sample behave.
