### ISSUE TITLE
Read and expose fields via ClassDescriptor.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-native#464]
Provide ``FieldDescriptor``s for fields belonging to the class described by `ClassDescriptor`.

The exposed information should cover:
- name
- type
- signature
- annotations
- access level
- access methods (get/set/is/wither)

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
