### ISSUE TITLE
Switch to bti by default and remove the feature module

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#466]
@aclement Please ping me when all sample are supported with bti, I can take care of the refactoring that will enable it by default, clarify the dependency required or not (hints, substitution) etc.

**Comment by aclement** [comment]
Samples and which are moved to new infrastructure:
- [x] commandlinerunner
- [x] webflux-netty
- [x] webmvc-tomcat
- [x] jdbc-tx
- [x] webflux-thymeleaf
- [x] security
- [ ] batch
- [ ] actuator-webmvc
- [ ] actuator-webflux
- [ ] boot-features
- [ ] hibernate
- [ ] petclinic-jdbc
- [ ] data-jpa
- [ ] data-mongodb
- [ ] validator
- [ ] logger 
- [ ] cloud
- [ ] cloud-config
- [ ] cloud-discovery
- [ ] cloud-function-aws
- [ ] cloud-function-netty
- [ ] cloud-function-netty-fun
- [ ] data-elasticsearch
- [ ] data-mongodb-reactive
- [ ] data-neo4j
- [ ] data-r2dbc
- [ ] data-redis
- [ ] features
- [ ] grpc
- [ ] kafka
- [ ] rsocket
- [ ] scheduling-tasks
- [ ] wavefront
- [ ] webclient
- [ ] webmvc-kotlin
- [ ] websocket

**Comment by sdeleuze** [comment]
We will migrate the Gradle samples as part of #453.
