### ISSUE TITLE
Apache LogFactory initialize at build-time issue

### ISSUE THREAD

**Issue by sendev1** [spring-projects-experimental/spring-native#468]
Hi @sdeleuze.I hope you can help me here.  I see that similar issue has been discussed here 
https://github.com/spring-projects-experimental/spring-native/issues/434. But I am not sure if mine is same or different hence I created new issue.

 I am using spring-native:0.9.0-SNAPSHOT and I ran into this issue.

```
[project:8153]     analysis:  26,798.81 ms,  3.93 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. org.springframework.context.annotation.ConfigurationClassEnhancer caused initialization of this class with the following trace:
        at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:136)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.<clinit>(ConfigurationClassEnhancer.java:87)
```

does it mean that the fix for #434  is not available in snapshot yet? or does it mean that the issue that I am facing is different than the #434 issue? Thanks in advance.

**Comment by sdeleuze** [comment]
[It should](https://github.com/spring-projects-experimental/spring-native/blob/58367867479ad734b22db26b02546e8e15b4e39f/spring-native-configuration/src/main/java/LoggingInitHints.java#L22), please provide a repro to allow us to check why it does not work.

**Comment by sendev1** [comment]
I found that one of the transitive gradle dependency is pulling the apache commons.logging 1.2 in my actual project. I created simple spring boot project and added commons.logging into dependency and added log statement into spring boot main method and native image works fine. I am not able to reproduce this issue in sample spring boot app. 

Steps I did to reproduce this issue

1. Created new spring boot app from spring initializer
2. added following gradle dependencies 
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'commons-logging:commons-logging:1.2'
    implementation "org.springframework.experimental:spring-native:0.9.0-SNAPSHOT"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```
3. Added log entry in spring boot main app
```
package com.example.logging.demo;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

	private static final Log logger = LogFactory.getLog(DemoApplication.class);

	public static void main(String[] args) {

		logger.info("added new log");
		SpringApplication.run(DemoApplication.class, args);
	}
}
```
5. Created native image using compile.sh found from spring native samples.
6. The native image was successfully built and ran as well. Unable to reproduce this issue. Not sure what else I should try to reproduce.

**Comment by sdeleuze** [comment]
I followed those steps using buildpack instead of `compile.sh`, and it works as expected so maybe something is wrong in the script you copied.
