### ISSUE TITLE
Add Spring integration support

### ISSUE THREAD

**Issue by Crazyjavahacking** [spring-projects-experimental/spring-native#469]
I was wondering is Spring integration is supported or what is the current status of it?

**Comment by sdeleuze** [comment]
No, it is not listed on https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-docs/src/main/asciidoc/support.adoc so it is not supported for now.

**Comment by artembilan** [comment]
Here is the work to be done in Spring Integration project: https://github.com/spring-projects/spring-integration/issues/3502.

Once that one is committed and this project is ready to consume Spring Boot `2.5` as based line, I'll come back here with some possible additional work, e.g. fix that list in Docs that it is supported as first step 😉 .

Will add some sample, hints and everything we would need to confirm that Spring Integration is supported in Spring Native already.
