### ISSUE TITLE
Add generated sources to IDE automatically

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#474]
We should ensure that both Maven and Gradle plugin do what's necessary to add generated sources to the IDE context.

We should also check how the feedback loop works when developers change sources and if the build-time infrastructure can be triggered automatically.

**Comment by dsyer** [comment]
I think you just need to call `project.addCompileSourceRoot()` (for `.java` sources) and `project.add{Test}Resource()` (for resources like properties files). As long as the plugin has a `<lifecycleMappingMetadata/>` in its `META-INF/m2e/lifecycle-mapping-metadata.xml` then the IDE will read the result off the project.

**Comment by sdeleuze** [comment]
I tried to add `project.addCompileSourceRoot()` and other related calls but I then get `cannot find symbol` and `duplicate class` errors. It may be due to the 2 step compilation that could mean we can't really use those classical API. To be discussed with Brian.

**Comment by sdeleuze** [comment]
I made a try with [this commit](https://github.com/spring-projects-experimental/spring-native/commit/edc26826872550a5add6f3a2f370a09c8093cd87), not sure if I did it right or not. IDEA is not configuring the source directory automatically.

**Comment by sdeleuze** [comment]
Generated source directories are now recognized automatically on both Eclipse and IDEA.
