### ISSUE TITLE
Oauth2 related classes not found in spring boot 2.4.1

### ISSUE THREAD

**Issue by rakotkar** [spring-projects-experimental/spring-native#475]
Are below classes removed in spring security by spring boot 2.4.1

import org.springframework.security.oauth2.common.OAuth2AccessToken 
import org.springframework.security.oauth2.provider.OAuth2Authentication 
import org.springframework.security.oauth2.provider.OAuth2Request
import org.springframework.security.oauth2.provider.token.AuthorizationServerTokenServices 
import org.springframework.security.oauth2.provider.token.TokenStore

they can neither be found in

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
nor in

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
Where can we find these if using spring boot 2.4.1 ?

**Comment by sdeleuze** [comment]
Is your question related to the native support ?

**Comment by rakotkar** [comment]
I am getting compilation errors in my code as these are missing

**Comment by rakotkar** [comment]
kindly suggest the replacements of these in latest spring security starters , that I have mentioned in the question

**Comment by eleftherias** [comment]
@rakotkar It looks like you are migrating from the legacy Spring Security OAuth project.
Please note that project is now [deprecated](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth) and users should the core Spring Security project.
The Spring Security team provides an [OAuth2 migration guide](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) that can help you with your migration.
