### ISSUE TITLE
Initialization hints are not taken in account when a trigger is specified

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#478]
Can be seen on `TomcatHints` for example.

**Comment by sdeleuze** [comment]
I tried to specify various init hints for classes in the classpath with a `Tomcat.class` trigger (also in the classpath), and they were not present in the generated `native-image.properties`. Without a trigger attribute it was taken in account as expected.

**Comment by aclement** [comment]
I also modified the data structures used - reducing `native-image.properties` for webmvc-tomcat (as an example) from 23k to 6k

**Comment by sdeleuze** [comment]
I finished to add proper triggers on other hints with 3aa1decdd1e02dc0a456bd81be298d9d6924b3dd.
