### ISSUE TITLE
Consider removing -Dspring.native.debug.verify if no longer being actively used

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#486]
The option should probably be removed, or if we really do not want, be renamed to `spring.native.debug.verify` and documented.

**Comment by aclement** [comment]
I've renamed it for now. I feel like I've used it a bit recently to dig into some things. Will look at removing when things get rewritten again as we migrate to the proper spring type system (I'll keep this bug as a reminder for 0.9.1)

**Comment by sdeleuze** [comment]
@aclement Should we remove it or keep it for 0.11?

**Comment by aclement** [comment]
@sdeleuze How does 0.11.x plan to handle the problem of inter bean method calls in configuration classes? (when they should ideally be using parameter injection) Is it going to check for it and warn the user? With aot proxies not currently automatically extended to cover configuration (which we could do), this problem can still happen can't it? I don't like not warning users about this problem as it may cause them unexpected issues.

**Comment by sdeleuze** [comment]
Good question, @snicoll do you know how 0.11.x handles (or not) inter bean method calls in configuration classes?

**Comment by aclement** [comment]
we could trigger the aot class proxy code for configuration classes that have this need and just used the generated proxy name in the further AOT code generation...

**Comment by sdeleuze** [comment]
We could indeed but likely not for 0.11, maybe create a backlog related issue? Also we will need to take care it works with the new AOT arrangement.

I had a discussion with Stéphane and the new AOT mechanism does not change the rules of the game.

For now I think we can keep current mechanism as it is.
