### ISSUE TITLE
Review Maven plugin logging

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#491]
It seems also that `System.out.println` are not working anymore in `ConfigOptions` after the switch to bti, so we should maybe use a logger to get the relevant output like for `System.out.println("Spring Native operating in "+MODE+" mode");`.

**Comment by aclement** [comment]
All the existing verbose logging with spring.native.verbose was converted to proper Java logging. I'll change the remaining few sysouts under this bug. You can turn on verbose mode by using the standard maven `-X` option which turns on debug logging for a run (you will see everything that previously came out in verbose mode).

**Comment by sdeleuze** [comment]
I reopen it to review logging once #484 will be fixed since I can't see logs for example `Spring Native operating in ... mode` which was displayed without having to set `spring.native.verbose`. I think we should avoid requiring having to set `-X`, `-e` should be enough.

**Comment by sdeleuze** [comment]
With 78f792c42cf24e33184e6d147750fb105d824885 it seems to work properly, I have configured `Spring Native operating in ... mode` to logged at info level.
