### ISSUE TITLE
cloud-function-aws triggered by SQSEvent

### ISSUE THREAD

**Issue by paulks** [spring-projects-experimental/spring-native#497]
Hi, 
I was following the sample of cloud-function-aws.
build & run successfully. Performance was unbelievable good. (even with JPA & Postgres) 

I want to run my cloud-function with a SQS trigger, using SQSEvent.

Without spring-native:  i've been using "SpringBootRequestHandler" 
(which is now deprecated in favor of individual implementations of invokers)
and SQSEvent worked fine.

When running using spring native and SQSEvent - im getting:
"BeanFactoryAwareFunctionRegistry : Failed to convert output"

The handler in AWS Lambda console was set to the name of function.

Is there a way to run spring-cloud-function-aws with spring-native and SQSEvent?

Thanks

**Comment by sdeleuze** [comment]
I guess you need to add native configuration for `SQSEvent`, if you are using `0.9.0-SNAPSHOT`, this can be done with `@NativeHints` annotation, see [an example here](https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-samples/webclient/src/main/java/com/example/webclient/WebClientApplication.java#L8).

Check the detailed log error for more details about what should be configured.

**Comment by paulks** [comment]
Got it. Thank you. I've been using the latest tag `0.8.5`
Also was not aware of `@NativeHint`
