### ISSUE TITLE
Custom annotation used by @ControllerAdvice not detected (ClassNotFoundException)

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#498]
Java 11, Spring Boot 2.4.3 w/Spring MVC, Spring GraalVM Native 0.9.0-SNAPSHOT

I have a custom annotation defined as below:

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface AddNotificationsToModel {

}
```

This is then referenced by a @ControllerAdvice like so:

```
@ControllerAdvice(annotations = { AddNotificationsToModel.class })
@RequiredArgsConstructor
public class NavControllerAdvice {
```

The image builds correctly. At runtime however I get the following:

```
ERROR [main] [] o.s.b.SpringApplication: Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.ecv.webapp.Application]; nested exception is java.lang.IllegalArgumentException: Could not find class [com.ecv.webapp.utils.AddNotificationsToModel]
...
Caused by: java.lang.ClassNotFoundException: com.ecv.webapp.utils.AddNotificationsToModel
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1260)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324)
        ... 28 more
```

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
