### ISSUE TITLE
Clarify whether projects should inherit from Spring Boot POM or Spring Native POM

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#503]
I'm trying to convert an existing Spring Boot 2.4.3 project to native.

Should I be using the native POM:
```
 <parent>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-native-parent</artifactId>
        <version>0.9.0-SNAPSHOT</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

...or the regular Spring Boot one?
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.3</version>
        <relativePath/>
    </parent>
```

The 0.9.0 docs say to use the latter - but then it looks like the AOT plugin won't receive all the necessary configuration (unless I'm missing something on how Maven works?)

**Comment by leccelecce** [comment]
Possibly related: I get "DataSize was unintentionally initialized at build time" during build using 0.9.0-SNAPSHOT, regardless of which of the above I use. The docs state "You have probably tried to compile a Spring Boot application to native without the spring-native dependency and Spring AOT plugin." but I've tried every combination of in/out I can.

**Comment by sdeleuze** [comment]
Yeah I plan to clarify that.

For using the regular Spring Boot parent, did you follow all the steps described in https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-docs/src/main/asciidoc/getting-started-buildpacks.adoc or https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-docs/src/main/asciidoc/getting-started-native-image.adoc (`spring-native` dependency and `spring-aot-maven-plugin`?

**Comment by leccelecce** [comment]
Excerpts from my pom.xml (I have tried using both Spring Boot 2.4.3 parent and spring-native-parent):

```
	<parent>
		<groupId>org.springframework.experimental</groupId>
		<artifactId>spring-native-parent</artifactId>
		<version>0.9.0-SNAPSHOT</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```
```

	<dependencies>

		<!-- Spring GraalVM support -->
		<dependency>
			<groupId>org.springframework.experimental</groupId>
			<artifactId>spring-native</artifactId>
			<version>0.9.0-SNAPSHOT</version>
		</dependency>

...(various Spring Boot starters, Hibernate, Postgresql etc)...

```
	<build>
		<plugins>

			<plugin>
				<groupId>org.springframework.experimental</groupId>
				<artifactId>spring-aot-maven-plugin</artifactId>
				<configuration>
					<removeYamlSupport>true</removeYamlSupport>
					<removeSpelSupport>true</removeSpelSupport>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<builder>paketobuildpacks/builder:tiny</builder>
						<env>
							<BP_BOOT_NATIVE_IMAGE>true</BP_BOOT_NATIVE_IMAGE>
							<BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>

								--trace-class-initialization=org.springframework.util.unit.DataSize

								-Dlog4j2.disable.jmx=true

								--enable-http
								--enable-https

								--initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl
								--initialize-at-build-time=com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator
								--initialize-at-build-time=com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl
...
```

**Comment by sdeleuze** [comment]
Documentation fixed, and the parent pom in not published anymore.
