### ISSUE TITLE
sporadic error about boot version for cloud config server

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#508]
This happens sometimes for me, but not necessarily all the time (bizarre). On starting it I get:

```
Description:

Your project setup is incompatible with our requirements due to following reasons:

- Spring Boot [0.0.1-SNAPSHOT] is not compatible with this Spring Cloud release train
```

The version number is bogus, however it is being computed is not right, but I don't understand why it doesn't fail every time.

**Comment by aclement** [comment]
I initially thought due to not including `META-INF/MANIFEST.MF` but I've still seen it happen with that in place. It is this code in Spring Boot:

```
String implementationVersion = SpringBootVersion.class.getPackage().getImplementationVersion();
```
(from `SpringBootVersion.determineSpringBootVersion`)

Sometimes it will return `2.4.3` (which is correct in my context) but sometimes it will return `0.0.1-SNAPSHOT`. It doesn't change on multiple runs of the same executable, it changes on different builds of the same project (so you either have a reliably broken or reliably working executable).

I wasn't totally sure where the rogue version was coming from so I changed the version of the project I was building to `0.0.1-BANANAS` and indeed after a few builds the implementation version above was `0.0.1-BANANAS` rather than `2.4.3`

**Comment by sdeleuze** [comment]
I am not sure why that happens, but let see if https://github.com/spring-projects-experimental/spring-native/commit/366a08aaa6951767eba82d1b11b0b5455c3e4b25 which switches the related code path to buildtime, fix it.

**Comment by aclement** [comment]
Sebastiens commit https://github.com/spring-projects-experimental/spring-native/commit/366a08aaa6951767eba82d1b11b0b5455c3e4b25 which pushes it to build time seems to help (and build time is the right time to compute this). After 10 builds I've not seen a failure, when before it was 30-50% of the time. I still think there is an issue lurking on the GraalVM side.

**Comment by sdeleuze** [comment]
Yeah, I will create a related issue tomorrow.

**Comment by aclement** [comment]
A few more builds later, still got the issue, even with the build time change in.  Some of those 10 builds I did before were with Java8 GraalVM - I was testing a hypothesis that we know Java11 GraalVM has unpredictable loading behaviour around some elements, did that also apply here.  I'll say I haven't seen the issue on 8 with or without the substitution but here I am seeing it again on 11 with master.

**Comment by sdeleuze** [comment]
I made another try with 5ca7a3546605e39a8aa71a1d3ec418dc9bd29349 please reopen if that's still happen.
