### ISSUE TITLE
Allow to use directly @TypeHint (and others) without @NativeHint

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#512]
When no trigger is useful (for example in user provided configuration), it would be very useful.

**Comment by sdeleuze** [comment]
@aclement I think you will be more efficient than me on that one.

**Comment by sdeleuze** [comment]
Sample to update are `webclient`, `webflux-kotlin` and `webflux-thymeleaf`.

**Comment by aclement** [comment]
All supported, tweaked those samples.
