### ISSUE TITLE
Add a Spring Boot failure analyzer

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#515]
In `NativeListener` throw a dedicated exception type and add a Spring Boot failure analyzer to print a nice looking error message with a link to Spring AOP plugins and IDE docs.

**Comment by snicoll** [comment]
Perhaps we could structure the documentation in such a way to you only need one link? It would have an overview with dedicated links for Maven, Gradle, and the supported IDEs. 

That way you can avoid that the failure analysis has to mention build systems and or IDE. It can rather explain why the application failed to start (The aot plugin didn't ran) with a single link to help users figure things out.

**Comment by sdeleuze** [comment]
Yes I am already modifying the documentation to follow that principle.
