### ISSUE TITLE
Add devtools support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#532]
See https://github.com/spring-projects-experimental/spring-native/issues/528#issuecomment-787487897

**Comment by Ortega-Dan** [comment]
I just want to subscribe to this issue, but doing it by asking a question.
First of all, thanks all for this awesome project ! This is really awesome for the Java ecosystem.
Second, the question ... no pressure, but just to be able to do some planning, is there any estimated time for this feature ?
What is missing ? or what can be done to help with this ?

**Comment by Haarolean** [comment]
I'm gonna post this here to let others who google this stuff will know a workaround:

`Could not generate spring.factories source code: Devtools is not supported yet, please remove the related dependency for now.`
Let's assume you're building an image for prod and not planning running it locally with devtools.
You could do this:

Create 2 maven profiles, one for prod (native image), the other one for local debug
```
<profiles>
    <profile>
        <id>native</id>
        <dependencies>
            <dependency>
                <groupId>org.springframework.experimental</groupId>
                <artifactId>spring-native</artifactId>
                <version>${spring-native.version}</version>
            </dependency>
        </dependencies>
    </profile>
    <profile>
        <id>local</id>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-devtools</artifactId>
                <scope>runtime</scope>
                <optional>true</optional>
            </dependency>
        </dependencies>
    </profile>
</profiles>
```
Now you can activate one of the profiles for different purposes. 
Also you can add this to activate one of the profiles by default:
```
<profile>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
</profile>
```

**Comment by jamesward** [comment]
This is closed but I'm still seeing the following in the `generateAot` task:
```
Caused by: java.lang.IllegalStateException: Devtools is not supported yet, please remove the related dependency for now.
```

**Comment by sdeleuze** [comment]
Good catch, I have created #1419 related issue.
