### ISSUE TITLE
Incorrect handling of @RequestHeader annotation's value attribute

### ISSUE THREAD

**Issue by fpoyer** [spring-projects-experimental/spring-native#542]
**Summary:**
the "value" attribute of the RequestHeader annotation for Controller method parameter is not correctly handled.

**Steps to reproduce:**
Follow the "tutorial" from the reference documentation (https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.5/spring-graalvm-native-docs-0.8.5.zip!/reference/index.html#getting-started-buildpacks).
Add the following methods to the `GreetingController` class.
```java
	@GetMapping("/name")
	public Greeting name(@RequestHeader(name="Header-Name") String headerName) {
		return new Greeting(counter.incrementAndGet(), "Received header with name = " + headerName);
	}
	@GetMapping("/value")
	public Greeting value(@RequestHeader(value="Header-Name") String headerName) {
		return new Greeting(counter.incrementAndGet(), "Received header with value = " + headerName);
	}
	@GetMapping("/default")
	public Greeting defaultValue(@RequestHeader("Header-Name") String headerName) {
		return new Greeting(counter.incrementAndGet(), "Received header with default = " + headerName);
	}
```

Build the native image and run it.
Test the image with the following:
```shell
    curl -H "Header-Name:123" localhost:8080/name
    curl -H "Header-Name:456" localhost:8080/value
    curl -H "Header-Name:789" localhost:8080/default
```

**Expected:**
Same result as would be obtained from the JAR, when run using `./gradlew bootRun`:
```shell
{"id":1,"content":"Received header with name = 123"}
{"id":2,"content":"Received header with value = 456"}
{"id":3,"content":"Received header with default = 789"}
```

**Actual:**
Only the method using the `name` attribute works the same:
```shell
{"id":1,"content":"Received header with name = 123"}
{"timestamp":"2021-03-02T10:31:55.751+00:00","status":400,"error":"Bad Request","message":"","path":"/value"}
{"timestamp":"2021-03-02T10:31:59.462+00:00","status":400,"error":"Bad Request","message":"","path":"/default"}
```

Log on server side: 
```
2021-03-02 10:31:55.748  WARN 1 --- [nio-8080-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MissingRequestHeaderException: Missing request header 'headerName' for method parameter of type String]
2021-03-02 10:31:59.461  WARN 1 --- [nio-8080-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MissingRequestHeaderException: Missing request header 'headerName' for method parameter of type String]
```
Note 1 : the "expected" header is now `headerName` (the method parameter name, instead of the value of the "value" attribute)
Note 2 : if changing the command to:
```shell
    curl -H "headerName:456" localhost:8080/value
```
then the result is the expected:
```
{"id":2,"content":"Received header with value = 456"}
```
meaning the header based routing is done correctly, it is only the header name "extraction" that fails.

**Comment by aclement** [comment]
I added those endpoints to the `webmvc-tomcat` sample in 0.8.5 and it failed as described. I then added them to the `webmvc-tomcat` sample in 0.9.1 and it worked. So I believe this is fixed. I think due to commit https://github.com/spring-projects-experimental/spring-native/commit/5062901aa5cd07595b1f09f139d274afcce10af5 that added reflective access for `RequestHeader.class`

**Comment by fpoyer** [comment]
Cool! Do we have an ETA for 9.1 already ?

Also: I think `Optional<Whatever>` as a return parameter for an endpoint has some problems. Do you want me to open another issue?

**Comment by aclement** [comment]
9.1 is imminent.

I'm surprised about that `Optional<Whatever>` - please open another issue, yep. Specific example of `Whatever` might be useful so I use the same POJO structure for it as you are having trouble with.
