### ISSUE TITLE
Natively built Spring Cloud Config Server returns empty values to Config Client for all properties.

### ISSUE THREAD

**Issue by benwilcock** [spring-projects-experimental/spring-native#556]
## Problem

Non-natively built Spring Cloud Config Clients cannot obtain configuration values from a natively-built Spring Cloud Config Server. The values returned from the native Config Server have zero data (empty). However, if the same Config Server is built in a regular way, the properties returned do contain valid values. The screenshots below provide some evidence. 

## Result

Non-native config-clients connected to native config-servers fail to obtain properties and may fail to start as a result depending on their configuration. Notice that `curl` based request-responses are not affected by this issue. This may result in false positives when testing.

## Expectation

Spring Cloud Config Clients (both native and non-native) should be able to retrieve and apply configuration from a Spring Cloud Config Server (native or non-native) correctly.

## Software Versions:
Java 11 (Bellsoft openjdk version "11.0.10" 2021-01-19 LTS)
Spring Boot 2.4.3
Spring Boot Actuator 2.4.3
Spring Cloud 2020.0.1
Spring Native 0.9.0-SNAPSHOT (March 4th 2021)
Spring AOT 0.9.0-SNAPSHOT
(Packeto Tiny or Regular Buildpack) GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)
Docker version 20.10.5, build 55c4c88

## Technique

The native image is built using the `spring-boot:build-image` method.  A "native" profile inside the config-server's `pom.xml` controls the configuration for this process. To build a native image, use the command `../mvnw package -DskipTests=true -P native spring-boot:build-image`. To build a regular image, use the command `../mvnw package -DskipTests=true spring-boot:build-image`.

To run the native config-server in docker use the command `docker run -ePORT=8888 -p8888:8888 -eGIT_CONFIG_URI=https://github.com/benwilcock/spring-petclinic-microservices-config benwilcock/spring-petclinic-config-server-native:2.4.3`. To run the non-native image in docker use the command `docker run -ePORT=8888 -p8888:8888 -eGIT_CONFIG_URI=https://github.com/benwilcock/spring-petclinic-microservices-config benwilcock/spring-petclinic-config-server:2.4.3`. Ready made docker images for these containers have been uploaded to docker hub.

## Project Files

* [Spring Petclinic Microservices, Spring Cloud Kubernetes branch.](https://github.com/benwilcock/spring-petclinic-microservices/tree/spring-cloud-kubernetes-discovery)
* [Spring Petclinic Microservices Config](https://github.com/benwilcock/spring-petclinic-microservices-config)
* Ready-built docker images are [available on Docker Hub](https://hub.docker.com/u/benwilcock).

## Screenshots

In the following screenshot taken while debugging `ConfigServerConfigDataLoader`, all values of properties returned from the **natively built** config server are zero / null.
![Screenshot-20210304103809-1569x1171](https://user-images.githubusercontent.com/5331092/109952522-d5fe7200-7cd6-11eb-988d-b02f0c287c4a.png)

In the following screenshot taken while debugging `ConfigServerConfigDataLoader`, all values of properties returned from the **regularly built** config server are zero / null.
![Screenshot-20210304103713-1551x1232](https://user-images.githubusercontent.com/5331092/109952525-d7c83580-7cd6-11eb-8544-c8e11ea4e8cf.png)

## Other Important Information

Curl request-response data taken from the natively-built server tells a different story. All the values have properties when using `curl`. Tests based on curl may give a false-positive result.
[native-config-response.txt](https://github.com/spring-projects-experimental/spring-native/files/6082962/native-config-response.txt)

Issue report requested by @spencergibb @sdeleuze

**Comment by sdeleuze** [comment]
I think we need to solve that in order to be able to claim Cloud Config support.

**Comment by sdeleuze** [comment]
@spencergibb Lack of binding usually is caused by the lack of binded classes in the reflection configuration.

Another thing to check is if that works when adding the config generated by the [tracing agent](https://docs.spring.io/spring-native/docs/0.9.0-SNAPSHOT/reference/#tracing-agent) and bisect the reflection config to find the missing entry.

**Comment by spencergibb** [comment]
Based on @benwilcock's statement that a curl request of the native config server returns proper values, that means it's an issue with config client.

BTW @benwilcock we will make no attempt to make eureka server native, only the client.

**Comment by spencergibb** [comment]
I may know why curl may behave differently. The default content type is `application/json` for backwards compatibility, but there is a custom content type for newer clients `application/vnd.spring-cloud.config-server.v2+json`

**Comment by spencergibb** [comment]
My suspicion was correct, plain `application/json` works, the custom content type does not.

**Comment by benwilcock** [comment]
> Based on @benwilcock's statement that a curl request of the native config server returns proper values, that means it's an issue with config client.
> 
> BTW @benwilcock we will make no attempt to make eureka server native, only the client.

TBH I wasn't expecting eureka-server support at all based on our earlier conversations, so I was surprised when it turned up in the SNAPSHOT documentation as 'supported.' I see that's now been changed. :thumbsup:
