### ISSUE TITLE
Index application components during AOT generation

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#572]
Currently the `spring-context-indexer` is in charge of that, but given the limitations seen in #551, we should really make that a proper AOT feature and not depend on the indexer annotation processor anymore.

With this feature, we should try and limit the classpath space we're scanning for components and maybe use the application information.

**Comment by aclement** [comment]
As written in #551, we already have a generator... 
https://github.com/spring-projects-experimental/spring-native/blob/2c63c45cc3d70d3dbb480d844d9c81dcdac168c2/spring-aot/src/main/java/org/springframework/aot/nativex/ConfigurationContributor.java#L55
But I can imagine it possibly misbehaving in multi module setups.
