### ISSUE TITLE
Document spring-context-indexer requirement

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#573]
As seen in #551, the Spring Context Indexer is automatically added to the main application module, but in case of a multi-module setup, the AOT process is missing critical information about beans.

We should document this limitation now and later reconsider this in #572

**Comment by sdeleuze** [comment]
Let's check if that's still relevant now that we have 413afe5b0967c802ed07c47be9768e8e9ad0124e.
