### ISSUE TITLE
Netty Natives are missing

### ISSUE THREAD

**Issue by MarcelCoding** [spring-projects-experimental/spring-native#574]
When I run 
```java
System.out.println(Epoll.isAvailable());
System.out.println(OpenSsl.isAvailable());
```
outside the native image, both values are `true`. However, inside the native image, both values are `false`.

OpenSSL is not as important as Epoll.

Epoll: `'io.netty:netty-transport-native-epoll'`
OpenSSL: `'io.netty:netty-tcnative-boringssl-static'`

PS: If I compile with the OpenSSL native in the classpath, the build will fail.

**Comment by sdeleuze** [comment]
Probably misconfiguration on Netty native configuration side, please create a related issue on https://github.com/netty/netty/issues and please share the link with a comment here.

**Comment by MarcelCoding** [comment]
https://github.com/netty/netty/issues/11088
