### ISSUE TITLE
Adding spring-graalvm-native causes autoreload to no longer work

### ISSUE THREAD

**Issue by jamesward** [spring-projects-experimental/spring-native#580]
I added:
```
implementation("org.springframework.experimental:spring-graalvm-native:0.8.5")
```
This causes devtools to mysteriously stop doing the autoreload thing.

**Comment by sdeleuze** [comment]
Yes that's a known issue, I have added a fail fast check in 0.9.0 and we should add devtools support in 0.10.0, see #532 related issue.

**Comment by jamesward** [comment]
Thanks for the quick response!
