### ISSUE TITLE
Failed to Run cloud-function-aws in AWS Lambda

### ISSUE THREAD

**Issue by uzshrestha** [spring-projects-experimental/spring-native#584]
`/var/task/bootstrap: line 5: ./cloud-function-aws: cannot execute binary file`

Hi, not sure what i am doing wrong. I am not able to run the native image in AWS lambda. (My lambda runtime is Custom runtime on Amazon Linux 2 and Handler is foobar) Same image when ran locally it works without issue. 
I am using 
Spring Boot: 2.4.1
spring-graalvm-native: 0.8.5
OpenJDK 64-Bit Server VM GraalVM CE 20.3.1 (build 25.282-b07-jvmci-20.3-b09, mixed mode)

I followed the sample steps and generated the native image cloud-function-aws from branch 0.8.5
Please advise ?

**Comment by uzshrestha** [comment]
I see same issue when i pull Amazon Linux2 image locally
docker run --rm -it -v "$(pwd)/target/native-zip":/var/task amazonlinux bash
```
bash-4.2# ./bootstrap
total 159216
-rwxrwxr-x 1 root root       107 Mar 11 12:21 bootstrap
-rwxrwxr-x 1 root root 163030440 Mar 11 12:30 cloud-function-aws
./bootstrap: line 5: ./cloud-function-aws: cannot execute binary file
```

**Comment by sdeleuze** [comment]
Could you please try with 0.9.0 after reading the [documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/) about how to configure it (check how to configure the Spring AOT build plugins) and send us you feedback?

cc @dsyer @spencergibb

**Comment by dsyer** [comment]
You forgot to `cd /var/task` (also the "native-zip" directory has to be created and populated)?

```
$ mvn clean package -P native-image,native # we should coalesce these into one profile
$ mkdir target/native-zip
$ (cd target/native-zip/; unzip ../*.zip)
$ docker run --rm -it -v "$(pwd)/target/native-zip":/var/task amazonlinux bashbash-4.2# ls
bash-4.2# cd /var/task/
bash-4.2# ./bootstrap
2021-03-12 16:20:37.667  INFO 11 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.4.4-SNAPSHOT)
...
2021-03-12 16:20:37.676  INFO 11 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.02 seconds (JVM running for 0.023)
Started
```

**Comment by uzshrestha** [comment]
Thank you @dsyer @sdeleuze. I will test this out and share the outcome

**Comment by uzshrestha** [comment]
@dsyer @sdeleuze I am still facing same issue. I tested this with 0.9.0 Branch
```
$ ~ % cd /../spring-native/samples/cloud-function-aws
$ cloud-function-aws % docker run --rm -it -v "$(pwd)/target/native-zip":/var/task amazonlinux bash
bash-4.2# cd /var/task/
bash-4.2# ls -ltr
total 57392
-rwxrwxr-x 1 root root      100 Mar  8 03:53 bootstrap
-rwxrwxr-x 1 root root 58762904 Mar 14 22:13 cloud-function-aws
bash-4.2# ./bootstrap
./bootstrap: line 5: ./cloud-function-aws: cannot execute binary file
bash-4.2#

**Comment by dsyer** [comment]
How did you create that “native-zip” directory? It is missing the native image executable isn’t it?

**Comment by uzshrestha** [comment]
@dsyer native image is part of zip.
```
bash-4.2# ls -ltr
total 57392
-rwxrwxr-x 1 root root      100 Mar  8 03:53 bootstrap
-rwxrwxr-x 1 root root 58762904 Mar 14 22:13 cloud-function-aws
```

**Comment by dsyer** [comment]
I don't know then, since it works for me. You haven't really explained how you got the zip file unpacked into that directory. Do you have a mouldy old one lying around maybe?

P.S. there is no "native" image now in master.

**Comment by uzshrestha** [comment]
@dsyer i performed same step that added above, i am doing this in 0.9.0 Branch. Would you happen to know if my anti-virus could be messing up with this executable ?

```
$ mvn clean package -P native-image
$ mkdir target/native-zip
$ (cd target/native-zip/; unzip ../*.zip)
$ docker run --rm -it -v "$(pwd)/target/native-zip":/var/task amazonlinux bash
bash-4.2# cd /var/task/
bash-4.2# ./bootstrap
```

**Comment by dsyer** [comment]
0.9.0 is a tag, so I assume that's what you mean. If you do that you will need the "native" profile as well, right, to build the .zip file. I don't really understand how you could have had a zip file at all without that.

**Comment by uzshrestha** [comment]
@dsyer there was a typo,  i actually did had native profile. so my cmd is
`mvn clean install -P native-image,native`
I worked with my security team and whitelisted the folder, still same issue. between this is company laptop. I guess i should try this in my personal laptop first.

**Comment by uzshrestha** [comment]
![image](https://user-images.githubusercontent.com/16170098/111210202-58bee100-85a3-11eb-8d00-3a8198aabd98.gif)

Hope this helps

**Comment by uzshrestha** [comment]
![image](https://user-images.githubusercontent.com/16170098/111211365-b273db00-85a4-11eb-9e98-506e6894d611.gif)

Hope this helps

**Comment by dsyer** [comment]
Your native image is about 10MB smaller than mine. Maybe there's something different with the environment you are building it in. Wrong OS/system libraries, IDK? What is your OS and how did you set up the environment? Could you try a buildpack instead of the "native-image" profile?

**Comment by dsyer** [comment]
My guess is you are building on the wrong OS or architecture. What is your environment? It's probably radically different from the one in the amazonlinux container.

**Comment by uzshrestha** [comment]
Hi @dsyer i am on mac os `OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"`
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_282, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-lts-java8-20.3.1/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```
Also unfortunately, i wont be able to use buildpack just yet as I'm behind proxy and buildpack doesn't support proxy yet. I have to wait for 2.5.0.M3 spring boot release
https://github.com/spring-projects/spring-boot/issues/22220

Also can you share your graalvm version. I installed graalvm using brew. https://github.com/graalvm/homebrew-tap

**Comment by dsyer** [comment]
That explains the issue then doesn’t it? You can’t build an image on a Mac and then run it on Linux. You need to build the image on the same arch and OS that you run it on. Probably your best option since you have docker working is to build in a container. I use VSCode to do that (there are some .devcontainer config files in some of the samples including this one I think).

**Comment by uzshrestha** [comment]
@dsyer thank you for your support, that does explain my issue, i will try devcontainer and share my result.

**Comment by tehioant** [comment]
Hi ! 
@uzshrestha is there a way to contact you ?
I'd like your input on the devcontainer.

**Comment by akuzni2** [comment]
I'm unable to find a way to build an native-image that is compatible with the lambda runtime. I also have searched through this repo looking for the .devcontainer config files but haven't been able to find them. Would really appreciate some help

**Comment by dsyer** [comment]
We removed the `.devcontainers` from this project because not enough people use them and there is a duplication of effort with the scripts we maintain already here. You could easily create your own, or use the dev container scripts from this project as described in the docs: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#how-to-contribute-using-container-build-env.
