### ISSUE TITLE
Add hint feature for "all nested classes"

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-native#588]
We often find that we need to deserialize (e.g. from JSON) or bind to a class and all its nested classes (e.g. `InstanceInfo` in `spring-cloud-netflix-euraka-client`) and it's tedious and unnecessary to list them all explicitly. It would be nice to have a flag we could set on a hint that would dive into the nested classes.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
