### ISSUE TITLE
Unintentional initialization

### ISSUE THREAD

**Issue by VuDo98** [spring-projects-experimental/spring-native#596]
I got this error while building. Since it belongs to spring i don't think I need any demo here.
`org.springframework.util.unit.DataSize was unintentionally initialized at build time. To see why org.springframework.util.unit.DataSize got initialized use --trace-class-initialization=org.springframework.util.unit.DataSize`

**Comment by sdeleuze** [comment]
[You probably miss configured Spring Native](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_datasize_was_unintentionally_initialized_at_build_time), please double-check the [reference documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/) or try to create a project on [start.spring.io](https://start.spring.io/).
