### ISSUE TITLE
How to generate .zip with Gradle for AWS LAMBDA?

### ISSUE THREAD

**Issue by nnior** [spring-projects-experimental/spring-native#606]
Hi everyone, I am so glad to meet and test spring-native. I have successfully tested with Gradle, but I want to test by uploading it to AWS Lambda. Currently I have seen that there is an example with Maven ([cloud-function-aws](https://github.com/spring-projects-experimental/spring-native/tree/master/samples/cloud-function-aws)), where a zip of the artifact is generated using `mvnw package -P native`.

How to get the same result but using Gradle?

Thank for the project :)

**Comment by sdeleuze** [comment]
Hi, glad you like it. For Gradle, you will likely have to use the [buildpack way](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-buildpacks) not the [Maven native image way](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-image).
