### ISSUE TITLE
sun.rmi.transport.ObjectTable was unintentionally initialized at build time

### ISSUE THREAD

**Issue by symphony-youri** [spring-projects-experimental/spring-native#610]
The build of a very simple example was failing with this error:
```
Error: Classes that should be initialized at run time got initialized during image building:
 sun.rmi.transport.ObjectTable was unintentionally initialized at build time. To see why sun.rmi.transport.ObjectTable got initialized use --trace-class-initialization=sun.rmi.transport.ObjectTable
```

What was puzzling is that the same project had already built once with success. It took me a while to figure out this was caused by `jvisualvm` running on my machine and probably causing the native image build to fail (maybe because it auto discovers Java processes and was causing them to load RMI classes).

This is a not issue (please close it) but I thought creating it could help other people stumbling on this problem.

**Comment by sdeleuze** [comment]
Thanks for raising that, that could be potentially a bug on GraalVM native image side, I will ask to the GraalVM team and provide you a feedback.

**Comment by sdeleuze** [comment]
Could you please create an issue on [GraalVM side](https://github.com/oracle/graal/issues) where you will provide the output you see with `--trace-class-initialization=sun.rmi.transport.ObjectTable` and share a repro project link?

Please share the link to this issue here in order to allow me to bring to it the the attention of the GraalVM team.

**Comment by thurka** [comment]
FYI: As a quick fix, you can run `native-image` with `-J-XX:+DisableAttachMechanism` to disable JMX and Attach API. Attach API is used to enable local JMX connection.
