### ISSUE TITLE
Build Fails on M1 Mac

### ISSUE THREAD

**Issue by aseemsavio** [spring-projects-experimental/spring-native#621]
Hello Team, Thanks for bringing this project out.

I'm on a Mac machine running on the Apple Silicon (M1 chip). The build I triggered using the `mvn spring-boot:build-image` command fails during the build-image stage.

Following are the logs:

[INFO] 
[INFO] --- spring-boot-maven-plugin:2.4.3:build-image (default-cli) @ native ---
[INFO] Building image 'docker.io/library/native:0.0.1-SNAPSHOT'
[INFO] 
[INFO]  > Pulling builder image 'docker.io/paketobuildpacks/builder:tiny' 100%
[INFO]  > Pulled builder image 'paketobuildpacks/builder@sha256:870c2769a65f29c62a0ffe397ae14cc1d61c2e90ebe85f068e8e2fff775c0344'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:tiny-cnb' 100%
[INFO]  > Pulled run image 'paketobuildpacks/run@sha256:30e7b4b0e1de31e763c7b631161a508c0ef710ea44924f65177afad2644312b9'
[INFO]  > Executing lifecycle version v0.10.2
[INFO]  > Using build cache volume 'pack-cache-452943cd6171.build'
[INFO] 
[INFO]  > Running creator
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     ======== Output: paketo-buildpacks/graalvm@6.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/gradle@5.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/leiningen@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/maven@5.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/sbt@5.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/executable-jar@5.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/spring-boot@4.1.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/native-image@4.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/procfile@4.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/environment-variables@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/image-labels@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     err:  paketo-buildpacks/graalvm@6.0.0
[INFO]     [creator]     err:  paketo-buildpacks/gradle@5.0.0
[INFO]     [creator]     err:  paketo-buildpacks/leiningen@3.0.0
[INFO]     [creator]     err:  paketo-buildpacks/maven@5.0.0
[INFO]     [creator]     err:  paketo-buildpacks/sbt@5.0.0
[INFO]     [creator]     err:  paketo-buildpacks/executable-jar@5.0.0
[INFO]     [creator]     err:  paketo-buildpacks/spring-boot@4.1.0
[INFO]     [creator]     err:  paketo-buildpacks/native-image@4.0.0
[INFO]     [creator]     err:  paketo-buildpacks/procfile@4.0.0
[INFO]     [creator]     err:  paketo-buildpacks/environment-variables@3.0.0
[INFO]     [creator]     err:  paketo-buildpacks/image-labels@3.0.0
[INFO]     [creator]     ======== Output: paketo-buildpacks/procfile@4.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/environment-variables@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/image-labels@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     err:  paketo-buildpacks/procfile@4.0.0
[INFO]     [creator]     err:  paketo-buildpacks/environment-variables@3.0.0
[INFO]     [creator]     err:  paketo-buildpacks/image-labels@3.0.0
[INFO]     [creator]     ======== Output: paketo-buildpacks/procfile@4.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/environment-variables@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/image-labels@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     err:  paketo-buildpacks/procfile@4.0.0
[INFO]     [creator]     err:  paketo-buildpacks/environment-variables@3.0.0
[INFO]     [creator]     err:  paketo-buildpacks/image-labels@3.0.0
[INFO]     [creator]     ======== Output: paketo-buildpacks/procfile@4.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/environment-variables@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     ======== Output: paketo-buildpacks/image-labels@3.0.0 ========
[INFO]     [creator]     qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[INFO]     [creator]     err:  paketo-buildpacks/procfile@4.0.0
[INFO]     [creator]     err:  paketo-buildpacks/environment-variables@3.0.0
[INFO]     [creator]     err:  paketo-buildpacks/image-labels@3.0.0
[INFO]     [creator]     ERROR: No buildpack groups passed detection.
[INFO]     [creator]     ERROR: failed to detect: buildpack(s) failed with err

**Comment by sdeleuze** [comment]
Related issue : spring-projects/spring-boot#25619

**Comment by sdeleuze** [comment]
Should be fixed when qemu fix will be released in Docker, see https://github.com/docker/for-mac/issues/5123 for more details.
