### ISSUE TITLE
Improve exception reporting in build plugins

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#622]
It seems that when the AOT generation phase fails (because a dependency is not supported or other reasons), the build plugins don't always properly report the exception cause and developers need to use a `-X` (maven) or `--stacktrace` (gradle) CLI flag to see the root exception.

**Comment by bclozel** [comment]
After checking this, it seems we're already good citizens here.

Maven shows the following:
```
Build failed during Spring AOT test code generation: Could not generate spring.factories source code: Devtools is not supported yet, please remove the related dependency for now. -> [Help 1]
```

Gradle shares less details by default, but this seems in line with other plugins:
```
 * What went wrong:
Execution failed for task ':generateAot'.
> Could not generate spring.factories source code
```

Closing this issue as declined as a result.

**Comment by UkonnRa** [comment]
Using Gradle, this is actually what the problem is. Gradle does not show `Devtools is not supported yet, please remove the related dependency for now` part so lots of time spent on debugging...

**Comment by bclozel** [comment]
Thanks for the feedback @UkonnRa 

We would like to improve this situation. What was your process for finding the root issue here? In your opinion, what would be the typical way of handling this for a Gradle plugin?

**Comment by sdeleuze** [comment]
@UkonnRa Could you please provide us a feedback ?

**Comment by UkonnRa** [comment]
I think it's not an important problem so I have not spent more time on this. The current situation is good enough. Thanks
