### ISSUE TITLE
Fatal error:org.graalvm.compiler.debug.GraalError

### ISSUE THREAD

**Issue by andresflorezp** [spring-projects-experimental/spring-native#624]
**A project was built with spring native and after 51 minutes of construction, the following issue was obtained**
`[INFO]     [creator]     	at method: boolean com.oracle.svm.reflect.PersistentClass_setCustomSQLUpdate_a9db1bc11914a9e5345cd6b455e9d27f3db3f3c4.equals(Object)  [Virtual call from Object Hashtable.get(Object), callTarget boolean Object.equals(Object)]
[INFO]     [creator]     	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1016)
[INFO]     [creator]     	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:947)
[INFO]     [creator]     	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:262)
[INFO]     [creator]     	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[INFO]     [creator]     	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[INFO]     [creator]     	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[INFO]     [creator]     	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[INFO]     [creator]     	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[INFO]     [creator]     	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[INFO]     [creator]     Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1`
![image](https://user-images.githubusercontent.com/23700749/111385569-02bc6d00-8679-11eb-8108-c1dc06357782.png)

**Comment by sdeleuze** [comment]
My guess is that you are on Mac and you did not increase the memory allocated to Docker as documented [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_out_of_memory_error_when_building_the_native_image) and [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_system_requirements).

**Comment by andresflorezp** [comment]
@sdeleuze thank you very much that was the problem, I have another problem when running the image I get a problem with freemaker I don't know if there is still no support for this library, it says that the propertie is not there but it is there. 
![image](https://user-images.githubusercontent.com/23700749/111566988-375d2100-876c-11eb-9aa2-28cec468c71a.png)
**Run Image**
![image](https://user-images.githubusercontent.com/23700749/111567009-404df280-876c-11eb-8ac8-dc88ea680d39.png)

**Comment by andresflorezp** [comment]
Properties
server.port=8034
spring.jpa.open-in-view=false
spring.freemarker.checkTemplateLocation=false
transbank.merchants.file.name=merchants.json
