### ISSUE TITLE
Proxy config not quite right if mixing typeNames and types in proxyhint

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#629]
The order of types when creating a JDK Proxy matters, and it would normally respect the order in a ProxyHint expressed in either types= or typeNames=. But if you mix those and use a combination of typeNames= or types= the ordering is not as easily controllable in the resultant proxy-config.json.

**Comment by sdeleuze** [comment]
Maybe for proxies we should enforce `types` or `typeNames` not both?

**Comment by aclement** [comment]
We could enforce sticking to one or the other but it feels nasty when you have the .class reference but are forced to write it as a string. After sleeping on it I had thought a simple `order=N` attribute in the hint annotation would work too.

**Comment by sdeleuze** [comment]
As discussed, I am more in favor of enforcing and documenting `types` **or** `typeNames`, and raising an error message if both are defined. For `TypeHint` this would have been blocking, but for `ProxyHint` I think this is not common enough to deserve a more complex and not so obvious from a programming model perspective mechanism.

**Comment by aclement** [comment]
There is a predictable ordering but it will be subtle without hiding something in the javadocs that no-one will ever read. I've done the quick thing, we have other battles to fight. You'll get an early failure if mixing the styles in a proxy hint. As a bonus it will even ll tell you which type contained the hint ;)
