### ISSUE TITLE
Using -H:+DashboardAll to export / dissect native image content via GraalVM Dashboard

### ISSUE THREAD

**Issue by chaudharydeepak** [spring-projects-experimental/spring-native#634]

**Comment by chaudharydeepak** [comment]
I am trying to use -H:DashboardDump=dumpfileoversized , -H:+DashboardAll parameter to generate a bgv dump for further analysis via GraalVM Dashboard tool.

pom.xml
```xml
....
<image>
  <builder>paketobuildpacks/builder:tiny</builder>
  <env>
    <BP_BOOT_NATIVE_IMAGE>true</BP_BOOT_NATIVE_IMAGE>
    <BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
      -H:DashboardDump=dumpfileoversized
      -H:+DashboardAll
    </BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
  </env>
</image>
.....
```

In console log output, I see statements as following:
```
[INFO]     [creator]     Printing Dashboard BGV dump header to /layers/paketo-buildpacks_native-image/native-image/dumpfileoversized.bgv
.....
[INFO]     [creator]     Printing Dashboard PointsTo analysis BGV dump to /layers/paketo-buildpacks_native-image/native-image/dumpfileoversized.bgv
.....
[INFO]     [creator]     Print of Dashboard dump output ended.
```

So, it seems the bgv dump file is generated - but I am unable to find in docker image.

Any pointers as to where this bgv/dump might be? Not a urgent issue, but it will be nice to dissect / analyse the dump file to see generated native image from sizing / footprint perspective. More info here about the tool - https://medium.com/graalvm/making-sense-of-native-image-contents-741a688dab4d

Thank you for your help.

**Comment by sdeleuze** [comment]
What happen here is probably that the files are generated in the container that is used to build the native image, not the one created for running your application. I would suggest to use the[ `native-image-maven-plugin`](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-image) instead of Spring Boot buildpacks integration for this kind of need.
