### ISSUE TITLE
Compatibility issues between aspectj and spring-native

### ISSUE THREAD

**Issue by andresflorezp** [spring-projects-experimental/spring-native#649]
**Error when running image with aspectj dependencies**
![image](https://user-images.githubusercontent.com/23700749/112085548-be3d3f80-8b58-11eb-80a7-de373be57c1a.png)

**Comment by chaudharydeepak** [comment]
also, is it possible if these exceptions [ incompatibility around specific spring modules ] can be throw bit earlier in the process? For ex the plugin includes something to check for dependency alignment with native before starting the actual build - that is fail fast?

I know the readme from spring initializer does something similar - may be more for local development not initiated by spring initializer.

**Comment by aclement** [comment]
Couple of things to unpack here.

@andresflorezp the AopHints class isn't complete (see https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-configuration/src/main/java/org/springframework/boot/autoconfigure/aop/AopHints.java ) you'll see it has Around but not before or after. We don't have a lot of tests around this area.  You could test out things by adding your own hints to cover the gaps. I see this code in the `AspectJAnnotation` class:
```
	annotationTypeMap.put(Pointcut.class, AspectJAnnotationType.AtPointcut);
	annotationTypeMap.put(Around.class, AspectJAnnotationType.AtAround);
	annotationTypeMap.put(Before.class, AspectJAnnotationType.AtBefore);
	annotationTypeMap.put(After.class, AspectJAnnotationType.AtAfter);
	annotationTypeMap.put(AfterReturning.class, AspectJAnnotationType.AtAfterReturning);
	annotationTypeMap.put(AfterThrowing.class, AspectJAnnotationType.AtAfterThrowing);
```

So a TypeHint on your spring application class like this:
```
@TypeHint(types={Pointcut.class, Before.class, After.class, AfterReturning.class, AfterThrowing.class}, access=AccessBits.ALL)
```
would alleviate that issue. What will happen after that, I'm not sure, if you are needing generated class proxies to support aop it won't work, but if you just need interface proxies, then it will.  Try it and let me know?


@chaudharydeepak this is a challenge. Basically down at the bytecode level, if we knew enough to tell you it won't work then we know enough to generate the configuration to make it work. Up at the starter level, yes we could warn you in the IDE that 'dependency X might now work' but the challenge at that level is the 'might'. We are at the point now that with Spring Native and sometimes a bit of config collection via the agent, you can build your spring app into a native image, so should we put you off even trying with a perhaps over zealous warning? Its a tricky line to walk. Even the starters we do support, I'm sure we haven't touched every little codepath within them yet, so support won't be perfect.

**Comment by chaudharydeepak** [comment]
@aclement - thank you for the explanation - I also verified the aspect fix including TypeHints and it seems to be working as expected.

**Comment by andresflorezp** [comment]
Good, thank you very much for the help, in code the TypeHints part, and the problems with AspectJ annotations are gone, however, I get the following error 
![image](https://user-images.githubusercontent.com/23700749/112882277-5c1d9680-9092-11eb-8632-db83c0503502.png)

**Comment by hantsy** [comment]
I also encountered the similar issue when I created my spring native example and added Data Auditing feature. @aclement I am not sure the`TypeHint` can fix the Mongo Data Auditing problem.

**Comment by phejl** [comment]
@andresflorezp This might be fixed in https://github.com/spring-projects-experimental/spring-native/issues/841 - at least that was the case for me.
