### ISSUE TITLE
Native app is saving data in Elasticsearch with empty payload 

### ISSUE THREAD

**Issue by ivangfr** [spring-projects-experimental/spring-native#658]
Hi, I've updated this project called [springboot-elasticsearch](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/springboot-elasticsearch) to `spring-boot 2.4.4` and `spring-native 0.9.1`.

I am able to build the native Docker image and run its container normally. However, when I save a `movie` in `Elasticseach`, the payload is saved as empty.

> **Note**: in `master` branch (that uses `spring-boot 2.4.3` and `spring-graalvm-native 0.8.5`) I am able to run `springboot-elasticsearch` successfully.

```
➜ curl -i -X POST "localhost:9117/api/movies" -H "Content-type: application/json" -d '{"imdb": "789", "title": "Resident Evil"}'
HTTP/1.1 201 Created
Content-Type: text/plain;charset=UTF-8
Content-Length: 20

7S3qOngBvTl0cjGNSIp3%

➜ curl "localhost:9200/springboot.movies.native/_search?pretty"
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "springboot.movies.native",
        "_type" : "_doc",
        "_id" : "7S3qOngBvTl0cjGNSIp3",
        "_score" : 1.0,
        "_source" : { }
      }
    ]
  }
}
```

---

### How to reproduce

1. git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git
1. cd graalvm-quarkus-micronaut-springboot
1. git checkout update-version-of-all-frameworks
1. cd elasticsearch
1. docker-compose up -d
1. cd springboot-elasticsearch
1. ./docker-build.sh native
1. docker run --rm --name springboot-elasticsearch-native -p 9117:8080 -e SPRING_PROFILES_ACTIVE=native -e ELASTICSEARCH_HOST=elasticsearch --network elasticsearch_default docker.mycompany.com/springboot-elasticsearch-native:1.0.0
1. curl -i -X POST "localhost:9117/api/movies" -H "Content-type: application/json" -d '{"imdb": "789", "title": "Resident Evil"}'
1. curl "localhost:9200/springboot.movies.native/_search?pretty"

**Comment by sdeleuze** [comment]
Could you please qualify this issue @christophstrobl?

**Comment by christophstrobl** [comment]
Spring Data Elasticsearch is one of the community maintained Spring Data modules. 
@sothawo any hints from your side?

**Comment by sothawo** [comment]
Although the project has the spring-boot-starter-data-elasticsearch dependency defined it does not use any of the Spring Data Elasticsearch classes; no operations/templates, no repositories.

The program uses just an Elasticsearch `RestHighlevelClient` that is set up  by Spring Boot. The mapping from domain classes to Elasticsearch request and response classes is done with _MapStruct_ and _Jackson_. 

I added some more logging to the server:

```java
    public String saveMovie(Movie movie) {
        try {
            log.info("movie: {}", movie);
            String movieAsJsonString = objectMapper.writeValueAsString(movie);
            log.info("movieAsJsonString: {}", movieAsJsonString);
            IndexRequest indexRequest = new IndexRequest(moviesIndex).source(movieAsJsonString, XContentType.JSON);
            log.info("indexRequest: {}", indexRequest.toString());
            IndexResponse indexResponse = client.index(indexRequest, RequestOptions.DEFAULT);
            String id = indexResponse.getId();
            log.info("Document for '{}' {} successfully in ES. The id is: {}", movie, indexResponse.getResult(), id);
            return id;
        } catch (Exception e) {
            String errorMessage = String.format("An exception occurred while indexing '%s'. %s", movie, e.getMessage());
            log.error(errorMessage);
            throw new MovieServiceException(errorMessage, e);
        }
    }
```

output (lines shortened):

```
c.m.s.service.MovieServiceImpl : movie: Movie(imdb=789, title=Resident Evil)
c.m.s.service.MovieServiceImpl : movieAsJsonString: {}
c.m.s.service.MovieServiceImpl : indexRequest: index {[springboot.movies.native][_doc][null], source[{}]}
c.m.s.service.MovieServiceImpl : Document for 'Movie(imdb=789, title=Resident Evil)' CREATED successfully in ES. The id is: OZwOa3gB930uXGdM48--
```

So there is a problem with the ObjectMapper that does not convert the object to a String.

But no problem of Spring Data Elasticsearch.

**Comment by ivangfr** [comment]
@sdeleuze after the perfect analyses from @sothawo (btw, sorry for not realizing that before) and the [response](https://github.com/spring-projects-experimental/spring-native/issues/659#issuecomment-806352459) from @aclement in the issue #649, I was able to fix the empty payload problem in my app, by adding `@TypeHint(types = Movie.class)`.

**Comment by chaudharydeepak** [comment]
> @sdeleuze after the perfect analyses from @sothawo (btw, sorry for not realizing that before) and the [response](https://github.com/spring-projects-experimental/spring-native/issues/659#issuecomment-806352459) from @aclement in the issue #659 , I was able to fix the empty payload problem in my app, by adding `@TypeHint(types = Movie.class)`.

Yeah - I have seen similar behavior wherein by explicitly mentioned the domain object with `@TypeHint` resolves the issue.

**Comment by sdeleuze** [comment]
Indeed for that use case a hint on application side is probably what is required, thanks for the analysis.

**Comment by py1971** [comment]
Is this annotation '@RegisterReflectionForBinding' on SpringBoot 3.0.0 release?
