### ISSUE TITLE
Web Server Still Starts with `CommandLineRunner` and `spring.main.web-application-type=none`

### ISSUE THREAD

**Issue by jamesward** [spring-projects-experimental/spring-native#663]
Pertinent build config:
```
    id("org.springframework.boot") version "2.4.4"
    id("org.springframework.experimental.aot") version "0.9.1"

...

    implementation("org.springframework.boot:spring-boot-starter-webflux")
```

I have a `CommandLineRunner` application like:
```
@SpringBootApplication
class MyCommandLine : CommandLineRunner {

    override fun run(vararg args: String?): Unit = runBlocking {
        println("asdf")
    }
}

fun main(args: Array<String>) {
    runApplication<MyCommandLine>(*args)
}
```

With `spring.main.web-application-type=none` in my `application.properties`.  When I run via the JVM the Netty server does NOT start (as expected).  But when I `bootBuildImage` and run the image, it starts Netty.

**Comment by aclement** [comment]
I hit this a while ago but hadn't dived into the cause. Finally found some time. I've fixed it in the code but if you want to just tweak your app and not pick up a snapshot, just add this hint to your spring boot application class:
```
@TypeHint(types=SpringApplication.class,
	methods = @MethodHint(name="setWebApplicationType",parameterTypes = WebApplicationType.class))
```

**Comment by jamesward** [comment]
Thanks so much for that!
