### ISSUE TITLE
Please support `serialization-config.json`

### ISSUE THREAD

**Issue by joshlong** [spring-projects-experimental/spring-native#668]
A file might look like this: 

```
[
  {
    "name": "my.serializable.DomainType"
  },
  {
    "name": "my.other.serializable.DomainType"
  } 
]
```

These classes are then serializable.

It would be very nice to have the ability to register these entries through a `@*Hint` annotation and through the `NativeConfiguration` and `ComponentProcessor` callback interfaces.

**Comment by aclement** [comment]
that file is a recent thing. can you give me a sample that requires it.

**Comment by joshlong** [comment]
Hi, thanks for your help. 

https://github.com/joshlong/bootiful-graalvm/tree/main/quartz

**Comment by aclement** [comment]
Fixed:
```
@SerializationHint(types=XXX.class)
```
or it can be used in a `TypeHint`. I've pulled your quartz sample in to test it *but* under issue #670 we should push the common Quartz config from the app to QuartzHints.

**Comment by aclement** [comment]
I'm reopening because I want to get the docs done too.

**Comment by aclement** [comment]
Some small docs added in align with the other hint coverage.
