### ISSUE TITLE
Please update the resource pattern config to load all Spring Batch schema SQL DDL instead of just `h2`.

### ISSUE THREAD

**Issue by joshlong** [spring-projects-experimental/spring-native#669]
See this file: 

https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native-configuration/src/main/java/org/springframework/batch/core/configuration/annotation/BatchHints.java#L32

**Comment by sdeleuze** [comment]
@benas @mminella Could I assign this issue to one of you?

**Comment by mminella** [comment]
You can assign it to me.
