### ISSUE TITLE
Please support the Quartz job scheduling engine

### ISSUE THREAD

**Issue by joshlong** [spring-projects-experimental/spring-native#670]
I am prepared to submit a PR (if there's any appetite for it) based [on this sample](https://github.com/joshlong/bootiful-graalvm/tree/3ae4ab26021a1eb808b7177ce5f97e3d183fbbc6/quartz), but I have two reservations. 

first: the example uses `serialization-config.json` which, as far as I can tell, we don't yet support through the various `@*Hint` annotations. Do we include any `.json` files in Spring Native in any other config? could we? 

second: i was having trouble getting field hints ( `writeAccess` and `unsafeAccess`) working for fields on  `java.util.HashMap`. I got it working using my own `reflect-config.json` (which lives next to the above `serialization-config.json`, but I'd love to be told I missed something and it can be made to work with the `@*Hint` annotations. 

thanks for your consideration.

**Comment by aclement** [comment]
You would normally specify a fieldhint within the typehint it is applicable too, otherwise we may not know which type you mean. Although I'll admit we could support a methodhint and a fieldhint if they applied to the type upon which they are located (that'd be a separate issue):
```
@TypeHint(types=HashMap.class, fields=@FieldHint(allowUnsafeAccess = true, name = "loadFactor"))
```

**Comment by aclement** [comment]
Hey @joshlong - your quartz sample is now in, but it still contains manual configuration (reflect-config.json and hints in the application class) - are you able to refine those into more general support for quartz (with appropriate triggers)?

**Comment by joshlong** [comment]
Yah, would love to! I was just about to ask if I could...

**Comment by joshlong** [comment]
Hi, I put together a [PR for your consideration based on the earlier sample](https://github.com/spring-projects-experimental/spring-native/pull/713).

**Comment by sdeleuze** [comment]
@aclement Please update the support doc accordingly if needed (with potential limitations).

**Comment by aclement** [comment]
@joshlong want to do a PR for the docs to indicate spring-boot-starter-quartz is on the support page? https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support-spring-boot - besides mentioning the starter, if there are any limitations around the support you know of (I guess I'm asking how comprehensive is your sample).

**Comment by joshlong** [comment]
the sample is based on a typical example that I think I found in the Spring Boot samples. I don't know what I don't know, however, and would not be surprised if there's some scenario that.I haven't addressed. I'll send a PR.
