### ISSUE TITLE
webmvc-tomcat-agent won't build

### ISSUE THREAD

**Issue by ewolff** [spring-projects-experimental/spring-native#678]
I tried to use the native agent as described in the doc on my own project. That didn't work. I then tried your sample webmvc-tomcat-agent . That did not work either. I am running Windows Subsystem for Linux and Docker Desktop.

**Comment by ewolff** [comment]
Surefire files:
[2021-03-28T16-08-58_409.dumpstream.txt](https://github.com/spring-projects-experimental/spring-native/files/6217463/2021-03-28T16-08-58_409.dumpstream.txt)
[2021-03-28T16-08-58_409-jvmRun1.dumpstream.txt](https://github.com/spring-projects-experimental/spring-native/files/6217464/2021-03-28T16-08-58_409-jvmRun1.dumpstream.txt)

**Comment by ewolff** [comment]
Surefire console output:
wolff@SUPERFAST:~/spring-native/samples/webmvc-tomcat-agent$ mvn spring-boot:build-image
Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/maven-metadata.xml
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/maven-metadata.xml (808 B at 1.1 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/spring-aot-maven-plugin-0.9.2-20210326.185900-19.pom
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/spring-aot-maven-plugin-0.9.2-20210326.185900-19.pom (2.6 kB at 8.9 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-build/0.9.2-SNAPSHOT/maven-metadata.xml
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-build/0.9.2-SNAPSHOT/maven-metadata.xml (630 B at 1.9 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-build/0.9.2-SNAPSHOT/spring-native-build-0.9.2-20210326.185900-19.pom
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-build/0.9.2-SNAPSHOT/spring-native-build-0.9.2-20210326.185900-19.pom (574 B at 2.0 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/spring-aot-maven-plugin-0.9.2-20210326.185900-19.jar
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot-maven-plugin/0.9.2-SNAPSHOT/spring-aot-maven-plugin-0.9.2-20210326.185900-19.jar (21 kB at 60 kB/s)
[INFO]
[INFO] ------------------< com.example:webmvc-tomcat-agent >-------------------
[INFO] Building webmvc-tomcat 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.4.4:build-image (default-cli) > package @ webmvc-tomcat-agent >>>
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/maven-metadata.xml
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/maven-metadata.xml (1.0 kB at 3.3 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/spring-native-0.9.2-20210326.185900-19.pom
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/spring-native-0.9.2-20210326.185900-19.pom (4.1 kB at 14 kB/s)
Downloading from spring-release: https://repo.spring.io/release/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.pom (1.6 kB at 5.3 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/spring-native-0.9.2-20210326.185900-19.jar
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native/0.9.2-SNAPSHOT/spring-native-0.9.2-20210326.185900-19.jar (54 kB at 146 kB/s)
Downloading from spring-release: https://repo.spring.io/release/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.44/tomcat-embed-programmatic-9.0.44.jar (2.2 MB at 3.1 MB/s)
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ webmvc-tomcat-agent ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ webmvc-tomcat-agent ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ webmvc-tomcat-agent ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ webmvc-tomcat-agent ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/test-classes
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (create-native-image-config-folder) @ webmvc-tomcat-agent ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/classes/META-INF/native-image
[INFO] Executed tasks
[INFO]
[INFO] --- spring-aot-maven-plugin:0.9.2-SNAPSHOT:test-generate (test-generate) @ webmvc-tomcat-agent ---
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/maven-metadata.xml
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/maven-metadata.xml (795 B at 2.2 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/spring-aot-0.9.2-20210326.185900-19.pom
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/spring-aot-0.9.2-20210326.185900-19.pom (1.5 kB at 5.2 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/maven-metadata.xml
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/maven-metadata.xml (1.0 kB at 3.1 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/spring-native-configuration-0.9.2-20210326.185900-19.pom
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/spring-native-configuration-0.9.2-20210326.185900-19.pom (16 kB at 56 kB/s)
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/spring-aot-0.9.2-20210326.185900-19.jar
Downloading from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/spring-native-configuration-0.9.2-20210326.185900-19.jar
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-native-configuration/0.9.2-SNAPSHOT/spring-native-configuration-0.9.2-20210326.185900-19.jar (149 kB at 308 kB/s)
Downloaded from spring-snapshot: https://repo.spring.io/snapshot/org/springframework/experimental/spring-aot/0.9.2-SNAPSHOT/spring-aot-0.9.2-20210326.185900-19.jar (467 kB at 484 kB/s)
[INFO] Spring Native operating mode: native-agent
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.data.jpa.repository.support.EntityManagerBeanDefinitionRegistrarPostProcessor it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.security.config.annotation.web.configuration.AutowiredWebSecurityConfigurersIgnoreParents it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: io.netty.channel.socket.nio.NioSocketChannel it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.messaging.handler.annotation.MessageMapping it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.transaction.annotation.Transactional it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: javax.transaction.Transactional it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.transaction.annotation.Propagation it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.web.reactive.socket.server.upgrade.UndertowRequestUpgradeStrategy it will be skipped
[WARNING] Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.web.reactive.socket.server.upgrade.JettyRequestUpgradeStrategy it will be skipped
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 29 source files to /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/test-classes
[INFO] /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/generated-test-sources/spring-aot/src/test/java/org/springframework/aot/StaticSpringFactories.java: /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/generated-test-sources/spring-aot/src/test/java/org/springframework/aot/StaticSpringFactories.java uses or overrides a deprecated API.
[INFO] /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/generated-test-sources/spring-aot/src/test/java/org/springframework/aot/StaticSpringFactories.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/generated-test-sources/spring-aot/src/test/java/org/springframework/core/io/support/SpringFactoriesLoader.java: Some input files use unchecked or unsafe operations.
[INFO] /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/generated-test-sources/spring-aot/src/test/java/org/springframework/core/io/support/SpringFactoriesLoader.java: Recompile with -Xlint:unchecked for details.
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ webmvc-tomcat-agent ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire-reports/2021-03-28T16-08-58_409-jvmRun1.dumpstream
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.229 s
[INFO] Finished at: 2021-03-28T16:08:59+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project webmvc-tomcat-agent: There are test failures.
[ERROR]
[ERROR] Please refer to /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/wolff/spring-native/samples/webmvc-tomcat-agent && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -agentlib:native-image-agent=access-filter-file=src/test/resources/access-filter.json,config-merge-dir=target/classes/META-INF/native-image -jar /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire/surefirebooter15069334491436604647.jar /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire 2021-03-28T16-08-58_409-jvmRun1 surefire7036921072089487731tmp surefire_07032092375073969861tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/wolff/spring-native/samples/webmvc-tomcat-agent && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -agentlib:native-image-agent=access-filter-file=src/test/resources/access-filter.json,config-merge-dir=target/classes/META-INF/native-image -jar /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire/surefirebooter15069334491436604647.jar /home/wolff/spring-native/samples/webmvc-tomcat-agent/target/surefire 2021-03-28T16-08-58_409-jvmRun1 surefire7036921072089487731tmp surefire_07032092375073969861tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:355)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sdeleuze** [comment]
Hi,

Maybe something platform specific since this sample is green on our CI, maybe we can refine our documentation.

Could you please share:
 - What terminal are you using (x64 Native Tools Command Prompt, Powershell, regular one ...) ?
 - Is `commandlinerunner` sample compiling fine?

**Comment by ewolff** [comment]
Thanks for looking into this! 🙂

- I am using Ubuntu on Windows Subsystem for Linux and the Windows Terminal
```
wolff@SUPERFAST:~/spring-native/samples$ uname -a
Linux SUPERFAST 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Yes, the commandlinerunner compiles fine on my machine. 

I was trying to use the native agent on my own project and failed. Without the native agent, it just works. To check whether the problem is specific to my project, I tried the sample and also failed. I agree that this is probably due to my setup. Still I filed the report because builds are probably run on many differnt platforms.

**Comment by sdeleuze** [comment]
Thanks for your feedback, I would advise you to create an issue on https://github.com/oracle/graal/issues since I think we can't really do something on Spring Native side. I would expect WSL + tracing agent to be supported. If you create such issue, please ask them to add the `spring` label in order to identify it as an issue that impact Spring use cases.
