### ISSUE TITLE
spring-boot-starter-thymeleaf: Missing Type Hint?

### ISSUE THREAD

**Issue by ewolff** [spring-projects-experimental/spring-native#679]
To run my Thymeleaf application successfully, I had to add this TypeHint:

```
import org.thymeleaf.engine.IterationStatusVar;
....
@TypeHint(types = { IterationStatusVar.class }, access = AccessBits.ALL)
```
Thymeleaf useses reflection on this class for iteration during template rendering. So I think this TypeHint should be added to the starter.

I am running Spring Native 0.9.1 and spring-boot-starter-thymeleaf 2.4.3

**Comment by sdeleuze** [comment]
Good catch, I have added it and this use case is now checked in the integration test.
