### ISSUE TITLE
AOT plugin doesn't seem to generate reflective metadata to access autowired fields

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-native#682]
Assume the following arrangement:

```java
class SomeAutoConfiguration {

  @Bean SomeComponent someComponent() {
    return new SomeComponent();
  }
}

class SomeComponent {
  @Autowired SomeDependency field;
}
```

Assuming the very top class is a Spring Boot auto-configuration class, declaring a hint for that class will result in the instance produced for `SomeComponent` not having the autowired field initialized. We found that while working on Spring Data REST'S compatibility with Spring Native and we deduced the following: the return types of the methods are included in the GraalVM native configuration with default access setup, i.e. invocation of the types constructor. That leads to Spring Framework not seeing the fields to be autowired and thus returning the instance without wiring the fields, which might then lead to `NullPointerException`s on the code using the fields.

Manually declaring a hint for that class including field access makes the arrangement work. Should the AOT plugin scan the return types for `@Bean` methods and enable field access out of the box if they use field injection?

Here's the complete description from a Slack conversation earlier that day. The concrete problematic case (an implementation class contained in Spring Boot) [has been fixed](spring-projects/spring-boot#25819) in the meantime.

> Spring Data REST exposes a RepositoryRestConfigurer SPI interface, which Spring Boot provides an implementation for (SpringBootRepositoryRestConfigurer) and declares it as @Bean in RepositoryRestMvcAutoConfiguration. That SBRRC uses autowired field injection (:grimacing:) to get access to other components and – because Spring framework guarantees them to be set – accesses those without a null check.
>
> When we now prepare the hints for Spring Data REST to work properly, we of course added the auto-configuration class to the list of hints and that resulted in the instance of SBRRC be handed to the Spring Data REST configuration but without the autowired fields populated.
>
> The reason for that is that apparently, return types of methods are automatically added to the list of types needed at runtime but only for constructor invocation use. I.e. Spring Framework sees the default constructor but not the fields to be autowired and thus hands an incompletely configured instance to downstream code. We could fix this by explicitly including the SBRRC instance into our hints declaring fields to be available for reflection, too.
>
>There are two things I think could / should be improved:
>
> * The implementation class in Boot could rather use constructor injection to avoid the misconfiguration of the instance at runtime. A side effect of this would be less reflection information needed for GraalVM.
> * As an additional safety net to avoid these situations, does it make sense to let the type inspection generally enable field access if it finds @Autowired annotations on fields in factory method return types? I see that generally enabling this for all bean types probably lets the image size explode and might be superfluous for classes not using field injection. I also guess that – assuming APT being used to generate the metadata – it's not that easy to drill down into the structure of a type detected as factory bean method return type, as AFAIK, you only see one type at a time, right?
>
> The reason I think the second point makes sense, too, even if the first solves the problem here, is that I fear that it's quite likely for end user applications to contain such arrangements, too, and it's quite hard to get to the root cause if you see the instances run into NPEs.

**Comment by aclement** [comment]
This is basically the same as this: https://github.com/spring-projects-experimental/spring-native/issues/666

Right now, we aren't diving deep into every single class to see if `Autowired` has been used, its as simple as that. yes, a type hint will fix it. Or adding some kind of indication to the containing class that you are relying on that feature should make it work, so `@Component` perhaps (it is called `SomeComponent` after all ;) ). If there is enough portfolio code using this pattern (I don't personally like...) we can do it automatically.  It's similar to using `@Bean` on a method without indicating that the class may be a provider of beans.  None of it is particular hard to do, seems like enough folks are hitting it we need to tackle it.

**Comment by odrotbohm** [comment]
While I agree with the general sentiment (kill field injection with fire), I think asking for a type to be returned from an `@Bean` method to be annotated with `@Component` is at odds with `@Bean` methods being (promoted as) the alternative to `@Component`. That said, I also agree with the combination of field injection and `@Bean` methods being a bit of a weird combination.

I am not particular passionate about a particular solution. I mostly care about the manifestation of the problem and ordinary users hardly being able to get to the root cause of this. I.e. to come to the conclusion that you recommend and we were able to figure out ourselves, you have to be familiar with so many details from how the Spring container works and populates the instance up to the default limitations of GraalVM, how the native image building works, the Graal way of tweaking the defaults and our programming model of controlling those means via annotations. All of that tied to the fact that the build is not really failing, but working in some but incomplete way (Spring creating the instance but not (being able to) properly populating it).

Does it make sense to explicitly document that field injection is not supported for `@Bean` method return types? Maybe even a broad brush of claiming it's not supported at all?

**Comment by odrotbohm** [comment]
I think, – to our all generous distaste – it is. On `@Component` and stereotype classes. The only gap right now is on classes returned from `@Bean` methods, which really is an odd combination, admittedly.

**Comment by aclement** [comment]
I've done an experiment. I wrote the code to scan for these 'things'. (Autowired or Bean used in a non annotated class). As an example I used the webflux-netty sample. It found four:
```
[INFO] Scanning for lite uses of Autowired/Bean took 797ms and returned 4 results
[INFO] Discovered unmarked class using @Autowired/@Bean: org/springframework/boot/autoconfigure/orm/jpa/DataSourceInitializedPublisher
[INFO] Discovered unmarked class using @Autowired/@Bean: org/springframework/boot/autoconfigure/batch/JobLauncherApplicationRunner
[INFO] Discovered unmarked class using @Autowired/@Bean: org/springframework/boot/autoconfigure/data/rest/SpringBootRepositoryRestConfigurer
[INFO] Discovered unmarked class using @Autowired/@Bean: org/springframework/web/reactive/config/WebFluxConfigurationSupport
```
3 of them are not required in this sample. The 4th is picked up anyway due to a subclass of the Support class being marked `@Configuration`.

**Comment by aclement** [comment]
All of those ones are currently dealt with automatically I think. (so the first 3 are dismissed and the 4th is included). 

To support the particular issue raised here, I've done as per proposal: "does it make sense to let the type inspection generally enable field access if it finds @Autowired annotations on fields in factory method return types?"

**Comment by odrotbohm** [comment]
Awesome, thanks, Andy!
