### ISSUE TITLE
Add support for @RequestBody in WebComponentProcessor and update web samples accordingly

### ISSUE THREAD

**Issue by diogopeixoto** [spring-projects-experimental/spring-native#683]
I'm trying to run my `Spring Boot Application 2.4.4` docker image using `org.springframework.experimental.aot 0.9.1` and when I try to converter `@RequestBody` parameter into one of my class `EmpresaDTO`  is throwing me an error:

Commands
```
$ gradle :bootBuildImage
$ docker run --rm -p 8080:8080 docker.io/library/application:0.0.1
```

Stacktrace
```
2021-03-29 14:00:23.737  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
Mar 29, 2021 2:00:23 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class io.prosperare.asset.manager.controller.empresas.EmpresaDTO]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.prosperare.asset.manager.controller.empresas.EmpresaDTO` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 2, column: 5]] with root cause
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.prosperare.asset.manager.controller.empresas.EmpresaDTO` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 2, column: 5]
```

However, my class has the default constructor. Am I missing something?
```
public class EmpresaDTO {

	public long id;
	public String cnpj;
	public String nomeFantasia;
	public String razaoSocial;

	public EmpresaDTO() {

	}
}
```

ps1: When I execute `gradle bootRun` it works fine, however, when I build a native image and run inside a docker container it does not. 
ps2: When I do not convert to native image, and run inside a docker container It also works fine

Am I missing something?

**Comment by sdeleuze** [comment]
It may be that we have to refine our `WebComponentProcessor` to handle this use case, could you please provide a repro project ?

**Comment by diogopeixoto** [comment]
Following the Github project as requested.

https://github.com/diogopeixoto/spring-native-example

**Comment by sgyeme** [comment]
EmpresaDTO must be registered in reflect-config Jackson uses reflection for serialisation

**Comment by diogopeixoto** [comment]
Added @TypeHint to my @SpringBootApplication class and worked. 

Thanks @sgyeme

**Comment by sdeleuze** [comment]
Ok so it seems we have a combination of 3 issues here:
 - `@ControllerAdvice` is not supported, see #498 related issue
 - We missed field reflection entries, this is fixed via 537bb4a7f80ed5746d86d05dc656d127a9d48cda
 - This (multi-module) Gradle project demonstrates that sometimes `EmpresaDTO` reflection entries are generated, sometimes not.

About the third point, I made a diff between the with/without versions, and I see 2 differences:
 - `io.prosperare.asset.manager.controller.empresas.EmpresaDTO`
- `org.springframework.http.HttpEntity`

@bclozel @aclement Any thoughts about the potential source of this transient issue?

**Comment by aclement** [comment]
@sdeleuze I would say next step check the `spring.components` created in either case (failing not/failing) - if that is different check the classpath used for the failing/not-failing case.

**Comment by bclozel** [comment]
I've found the problem that triggers the reflection data being there/absent depending on the run. I've created #729 to track that problem. I'm closing this issue since it's been superseded by others in the meantime.

Thanks!
