### ISSUE TITLE
ClassPathScanningCandidateComponentProvider does not find candidate components.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-native#691]
The `ClassPathScanningCandidateComponentProvider` seems to not make use of the `spring.components` file when using filters.

```
com.example.Address=javax.persistence.Entity
com.example.Customer=javax.persistence.Entity
```

```java
ApplicationContext ctx ...

ClassPathScanningCandidateComponentProvider provider = new ClassPathScanningCandidateComponentProvider(false, ctx.getEnvironment());

provider.setResourceLoader(ctx);
provider.setResourcePattern("**/*.class");
provider.setMetadataReaderFactory(new CachingMetadataReaderFactory(ctx));
provider.addIncludeFilter((reader, factory) -> true);

// set should contain at least Address & Customer but is empty
Set<BeanDefinition> candidateComponents = provider.findCandidateComponents("com.example");
```

Using the `CandidateComponentsIndex` via the `CandidateComponentsIndexLoader` directly allows to lookup the entries.

Related to: #661

**Comment by snicoll** [comment]
That's because of the `IncludeFilter` and it's not a bug in Spring Native as far as I understand the report. If you add an include filter with a lambda, it'll fail the [filter check](https://github.com/spring-projects/spring-framework/blob/58e40d1aa2c23f6d9c41d4289f5b5debc10868f6/spring-context/src/main/java/org/springframework/context/annotation/ClassPathScanningCandidateComponentProvider.java#L341-L351) in Spring Framework.

Since you seem to be interested by components annotated with `Entity`, can you try with `AnnotationTypeFilter`?

**Comment by christophstrobl** [comment]
Thanks @snicoll I'll give it a try without the lambda.

**Comment by christophstrobl** [comment]
@snicoll using the `AnnotationTypeFilter` works for the above but is unfortunately not an option for what we're trying to do.
To discover repository fragments, need to iterate all components within the index based on a resource pattern. Matching `BeanDefinition` are filtered in a later step.

Using an `AnnotationTypeFilter` would require people add `@Component` to their repository fragment implementation which is not desired. Using an `AssignableTypeFilter` with `Object.class` won't do the trick either due to the `@Indexed` lookup on the target type. 

Unless we've an option to add entries to the `spring.components` file during AOT I think adding `@Indexed` to the repository fragment implementation would be ok for now.

So we'd end up with something like this:

```java
@Indexed
public class ConferenceCustomRepositoryImpl implements ConferenceCustomRepository { 
  ...
}
```

```
com.example.data.ConferenceCustomRepositoryImpl=com.example.data.ConferenceCustomRepositoryImpl
```

What we'd need now is a way that is using the index to lookup all components filtering them by resource pattern.
Any suggestions?

**Comment by snicoll** [comment]
@christophstrobl shouldn't we rephrase this issue based on our recent conversation?

**Comment by christophstrobl** [comment]
I think we can close this one. Would it make sense to add an additional log entry to `ClassPathScanningCandidateComponentProvider` that indicates that the index is not used? Might be useful in native scenarios to find out why a component cannot be found.

**Comment by snicoll** [comment]
Framework already has such a log. It tells you whether it is using the index or performing a classpath check at runtime, based on the presence of the index and whether the include filters are supported.

**Comment by christophstrobl** [comment]
There's a lot of detailed logging once you got past the check if the index can be used at all, but none that can tell you if the the `indexSupportsIncludeFilters`.

**Comment by snicoll** [comment]
Feel free to raise a framework issue with more details of what you'd like to see.
