### ISSUE TITLE
Minimal Sample Project from start.spring.io not working

### ISSUE THREAD

**Issue by shimatai** [spring-projects-experimental/spring-native#701]
I've downloaded a minimal project from [start.spring.io](https://start.spring.io) only containing Spring Native Experimental, with no other frameworks, just Spring Native.

When I try to build running the command `mvn spring-boot:build-image`, I got a lot of messages with error **"[creator] WARNING: Could not register reflection metadata for org.springframework.boot..... Reason: java.lang.NoClassDefFoundError"**

The last error description is:
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image (default-cli) on project demo: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image failed: Builder lifecycle 'creator' failed with status code 145 -> [Help 1]
[ERROR]
```

I'm using the following Java version, running on macOS Catalina:

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

**Comment by snicoll** [comment]
@shimatai the warnings are to be expected at this time, see #502. It's hard to tell what is going on based on that partial error. Can you double check your environment meets the [system requirements](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_system_requirements) first? If that doesn't help, can you run again with `-X` and paste the relevant extra information?

**Comment by UkonnRa** [comment]
Same error for me, this is the minimal demo: https://github.com/UkonnRa/native-test

**Comment by snicoll** [comment]
@UkonnRa looking at the original description, your sample project is not the same at all "only containing Spring Native Experimental, with no other frameworks, just Spring Native.". 

Please don't add a comment here but create your own issue. The sample is very useful for the team to look at.

**Comment by UkonnRa** [comment]
> @UkonnRa looking at the original description, your sample project is not the same at all "only containing Spring Native Experimental, with no other frameworks, just Spring Native.".
> 
> Please don't add a comment here but create your own issue. The sample is very useful for the team to look at.

Oh I get it, I will create my own issue

**Comment by sdeleuze** [comment]
Superseeded by #709.

**Comment by sdeleuze** [comment]
@shimatai Could you please provide the feedback asked by @snicoll?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
