### ISSUE TITLE
how to hide the 'cmd window' when run on windows PC

### ISSUE THREAD

**Issue by zhouzipeng** [spring-projects-experimental/spring-native#705]
I compile my springboot-native project to .exe which run on windows PC.
But when i open the .exe, it shows a 'cmd windows',i don't want it,because i use 127.0.0.1/index.html to interact with my program.
Because of i will send my .exe to my client , the black 'cmd window' is not user friendly.
How to hide the 'cmd/terminal window' when run on windows PC?
Or can i use Java GUI(like AWT, SWing) to instead of the 'cmd window'.

**Comment by zhouzipeng** [comment]
I compile my project to .exe which run on windows PC.
But when i open the .exe, it shows a 'cmd windows',i don't want it,because i use 127.0.0.1/index.html to interact with my program.

**Comment by zhouzipeng** [comment]
or can i use Java GUI(like AWT SWing) to instead of the 'cmd window'

**Comment by sdeleuze** [comment]
I don't know and I don't think that's something under our control. For Java GUI with native image, I would advise to ask in the `#native-image` channel of [GraalVM Slack](https://www.graalvm.org/slack-invitation/).
