### ISSUE TITLE
Support for serving JSP pages in a native app out of the box

### ISSUE THREAD

**Issue by gradinac** [spring-projects-experimental/spring-native#706]
Currently, JSP pages in a Spring native app with an embedded Tomcat do not work out of the box.
The issue is two-fold:
1. Tomcat is unable to locate these pages
2. The JSP pages have to be translated to Java code and then compiled and dynamically loaded. This would currently not work on native-image

For our use-case, we've managed to get it to work in the following way:
1. We've used the following gradle plugin to precompile the JSP pages to Java code: https://github.com/bmuschko/gradle-tomcat-plugin. Apart from precompiling the JSP pages, this plugin also generates an xml file with the servlet definitions and servlet mappings that can be registered in Tomcat.
2. We've added the generated sources to the `bootWar` target
3. We've used the snippet from https://stackoverflow.com/a/35651338 to register the servlet definitions and mappings during the servlet context initialization, from the xml file generated in step 1.

A custom Gradle plugin is probably not required for JSP precompilation - it seems like it can be done directly in gradle using JSPC: https://stackoverflow.com/a/42830116

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
