### ISSUE TITLE
Improve guidelines for spring boot custom starters

### ISSUE THREAD

**Issue by jvmlet** [spring-projects-experimental/spring-native#710]
Would you please  summarize the general guidelines for custom spring boot starters development in order to support `spring native`  applications?

**Comment by sdeleuze** [comment]
For GRPC use case, do you need dynamic configuration (based on user provided classes for example) or just static configuration that could be provided as [native hints](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints)?

**Comment by jvmlet** [comment]
Thanks for the reply, @sdeleuze. This is generic question. 
Reading the spring native reference documentation, it's stated that some spring boot starters are already supported by `spring native`, like `spring-boot-starter-data-jdbc` or `spring-boot-starter-data-jpa`. Looking at these repositories source code I don't see any usage of `native-hints`, as well as any dependencies on spring-native libraries. So I'm after the general guidelines, like 

* Don't use reflection API
* Don't load classes dynamically
* Always rely on spring boot beans discovery API instead of manual class path scanning

Regarding `grpc-spring-boot-starter`, all customizations are discovered via `applicationContext.getBeanNamesForType(class)` or `applicationContext.getBeansWithAnnotation(annotationType)`, also I do `class.newInstance()` calls

**Comment by sdeleuze** [comment]
I have updated the reference documentation to provide more information about what is and what is not supported for external native configuration. Dynamic native configuration is not yet supported when provided externally, but as documented you can provide native hints for now, and if you really need dynamic configuration, you can implement a native image feature for now.

Regarding to the guidelines, we don't say "Don't use reflection API", read carefully the 0.9.2 how to contribute section for more information.

We will try to provide more external dynamic configuration capabilities in [Spring Native 0.11](https://github.com/spring-projects-experimental/spring-native/milestone/15).
