### ISSUE TITLE
Spring native application for AWS Lambda custom runtime

### ISSUE THREAD

**Issue by tehioant** [spring-projects-experimental/spring-native#711]
How would you retrieve or add an export to the build of the native image ?

My issue is that I am trying to use the native application with AWS Lambda custom runtime. I am able to do it with graalvm :)
For my custom runtime to be built I need the application not as a jar but an executable which is available during the build.
I am able to zip the executable along with a bootstrap all prepared for aws lambda.

Is it possible to do so with spring native beta ?

This is the code I am using:
`docker run --rm -v $(pwd):/working ghcr.io/graalvm/graalvm-ce:latest \`
     `/bin/bash -c " `
                  `gu install native-image; \`
                 ` native-image --enable-url-protocols=http,https \
                    -H:+AllowIncompleteClasspath \
                    -H:+ReportExceptionStackTraces \
                    -H:ReflectionConfigurationFiles=/working/src/main/resources/reflect.json \
                    -H:+ReportUnsupportedElementsAtRuntime --no-server \
                    -jar /working/target/MyProject.jar \
                  ; \`
                 ` cp MyProject /working/target/server"`

`cp MyProject /working/target/server` <- copy the executable on my disk.

**Comment by dsyer** [comment]
This sample builds a native image for AWS Lambda: https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws. Are you trying to do something different to that?

**Comment by tehioant** [comment]
Thank you :) 
It is what I was looking for although I cannot make the native.xml assembly file work 
![Screenshot 2021-04-09 at 11 42 24](https://user-images.githubusercontent.com/47829208/114161748-b76c4600-9928-11eb-866e-17fc8de08e17.png)

**Comment by dsyer** [comment]
Did you run `mvn install -P native-image` (should work on "main" branch now - remember that the master branch changed).

**Comment by tehioant** [comment]
I ran `./mvnw package -P native`
but running `mvn install -P native` (since my profile is referred as 'native' and not 'native-image') does not change anything. I still get the same error declared as `http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by sdeleuze** [comment]
There are 2 profiles involved (one in the parent pom) so just using `./mvnw package -P native` won't work, please try to update to latest `main` branch and run `mvn install -P native-image`.

**Comment by tehioant** [comment]
Thank you fir your input 
I got it the build was successful :)
