### ISSUE TITLE
AWS lamda - Failed to create the function nativeImage: Image runtime config size is larger than 16 KB

### ISSUE THREAD

**Issue by muyen** [spring-projects-experimental/spring-native#717]
I was trying out the cloud-function-aws in the sample.

I built a native container image and tried to deploy aws lamda. However, I got the follow error message.

"Failed to create the function nativeImage: Image runtime config size is larger than 16 KB."

May I ask what is the configuration? How can I reduce the size so it could work?

**Comment by dsyer** [comment]
Works for me, but I needed to activate 2 profiles ("native-image" and "native"). I think maybe we could just use "native-image" in both pom files.

**Comment by sdeleuze** [comment]
Indeed, that was probably a miss when we renamed `native` profile to `native-image` so +1 for using only `native-image`.

**Comment by dsyer** [comment]
Done see e3581365
