### ISSUE TITLE
Nested classes in custom Condition implementations are not registered in the image

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#719]
When running the sample Sleuth application provided in #673 with the native image, we're getting the following:
 
```
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.sleuth.autoconfig.otel.OtelAutoConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ...
...
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: class path resource [org/springframework/cloud/sleuth/autoconfig/otel/AnyTracerModePropertySetCondition$OnAutoTracerMode.class] cannot be opened because it does not exist
...
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/sleuth/autoconfig/otel/AnyTracerModePropertySetCondition$OnAutoTracerMode.class] cannot be opened because it does not exist
```

Tracing back to the source of the problem, we're seeing that an auto-configuration class is annotated with a custom condition:

```java
@ConditionalOnOtelEnabled
public class OtelAutoConfiguration {
```

And that condition itself points to the condition implementation:

```java
@Conditional({AnyTracerModePropertySetCondition.class})
public @interface ConditionalOnOtelEnabled {
}
```

While we are providing a `@NativeHint` to register all classes in the `@Conditional` annotation, it seems that in this case the condition is relying on a package private static class, which is causing this issue:

```java
package org.springframework.cloud.sleuth.autoconfig.otel;

import org.springframework.boot.autoconfigure.condition.AnyNestedCondition;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.ConfigurationCondition.ConfigurationPhase;

final class AnyTracerModePropertySetCondition extends AnyNestedCondition {
    private AnyTracerModePropertySetCondition() {
        super(ConfigurationPhase.REGISTER_BEAN);
    }

    @ConditionalOnProperty(
        value = {"spring.sleuth.tracer.mode"},
        havingValue = "AUTO",
        matchIfMissing = true
    )
    static class OnAutoTracerMode {
        OnAutoTracerMode() {
        }
    }
}
```

At this point, I'm not sure if we should consider this usage pattern as invalid or if we can improve the AOT processing to handle this case.

**Comment by sdeleuze** [comment]
Any thoughts @aclement ?

**Comment by aclement** [comment]
I feel like I've seen this kind of pattern in another place too. Including `@Conditional` annotated nested classes within a type implementing `Condition` doesn't seem totally unreasonable to catch these.

**Comment by aclement** [comment]
I had already done part of it (the support  was there for recognizing NestedCondition types). I think I was playing around with it when working with actuator hints. So I finished that off. I updated the features sample app to include a scenario like above to verify correctness.

**Comment by aclement** [comment]
It found another couple of situations actually too, including `JCacheAvailableCondition`
