### ISSUE TITLE
Fail to starts server in Kotlin+Webflxux+R2DBC+OATH - Error : Class java.lang.Iterable[] is instantiated reflectively but was never registered. 

### ISSUE THREAD

**Issue by mmuniz75** [spring-projects-experimental/spring-native#724]
I got a code snippet of my system built with Kotlin ,Webflux , RDBC2 and Spring Oauth 2.
The image generation is fine but when I try up the server I got the error bellow.

The code is in : https://github.com/mmuniz75/native-test
There is a docket compose in the path to starts the container

Caused by: java.lang.IllegalArgumentException: Class java.lang.Iterable[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
askalien-admin_1  |     at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:281) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.impl.descriptors.runtime.structure.ReflectClassUtilKt.createArrayType(reflectClassUtil.kt:78) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.impl.descriptors.runtime.structure.ReflectClassUtilKt.getDesc(reflectClassUtil.kt:74) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.RuntimeTypeMapperKt$signature$1.invoke(RuntimeTypeMapper.kt:156) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.RuntimeTypeMapperKt$signature$1.invoke(RuntimeTypeMapper.kt) ~[na:na]
askalien-admin_1  |     at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85) ~[na:na]
askalien-admin_1  |     at kotlin.collections.ArraysKt___ArraysKt.joinTo(_Arrays.kt:23102) ~[na:na]
askalien-admin_1  |     at kotlin.collections.ArraysKt___ArraysKt.joinToString(_Arrays.kt:23319) ~[na:na]
askalien-admin_1  |     at kotlin.collections.ArraysKt___ArraysKt.joinToString$default(_Arrays.kt:23318) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.RuntimeTypeMapperKt.getSignature(RuntimeTypeMapper.kt:156) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.RuntimeTypeMapperKt.access$getSignature$p(RuntimeTypeMapper.kt:1) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.JvmFunctionSignature$JavaMethod.asString(RuntimeTypeMapper.kt:76) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KFunctionImpl.<init>(KFunctionImpl.kt:49) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.CreateKCallableVisitor.visitFunctionDescriptor(util.kt:245) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.CreateKCallableVisitor.visitFunctionDescriptor(util.kt:222) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.impl.descriptors.impl.FunctionDescriptorImpl.accept(FunctionDescriptorImpl.java:782) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:61) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$inheritedNonStaticMembers$2.invoke(KClassImpl.kt:166) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$inheritedNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data.getInheritedNonStaticMembers(KClassImpl.kt) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data.access$getInheritedNonStaticMembers$p(KClassImpl.kt:47) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:171) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:177) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:47) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllMembers(KClassImpl.kt) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.jvm.internal.KClassImpl.getMembers(KClassImpl.kt:195) ~[na:na]
askalien-admin_1  |     at kotlin.reflect.full.KClasses.getFunctions(KClasses.kt:90) ~[edu.muniz.askalien.admin.AskalienAdminApplicationKt:1.4.31-release-344 (1.4.31)]
askalien-admin_1  |     at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:136) ~[na:na]
askalien-admin_1  |     at org.springframework.data.util.KotlinReflectionUtils.findKotlinFunction(KotlinReflectionUtils.java:79) ~[na:na]
askalien-admin_1  |     at org.springframework.data.util.KotlinReflectionUtils.isSuspend(KotlinReflectionUtils.java:95) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.AbstractRepositoryMetadata.getReturnType(AbstractRepositoryMetadata.java:90) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.DefaultRepositoryInformation.getReturnType(DefaultRepositoryInformation.java:254) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.QueryMethod.potentiallyUnwrapReturnTypeFor(QueryMethod.java:274) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.QueryMethod.<init>(QueryMethod.java:81) ~[na:na]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.query.R2dbcQueryMethod.<init>(R2dbcQueryMethod.java:83) ~[na:na]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactory$R2dbcQueryLookupStrategy.resolveQuery(R2dbcRepositoryFactory.java:186) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:100) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(QueryExecutorMethodInterceptor.java:93) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
askalien-admin_1  |     at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
askalien-admin_1  |     at java.util.Collections$UnmodifiableCollection$1.forEachRemaining(Collections.java:1054) ~[na:na]
askalien-admin_1  |     at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:95) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:85) ~[na:na]
askalien-admin_1  |     at java.util.Optional.map(Optional.java:265) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:85) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:303) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[edu.muniz.askalien.admin.AskalienAdminApplicationKt:2.4.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.data.util.Lazy.getNullable(Lazy.java:230) ~[na:na]
askalien-admin_1  |     at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[edu.muniz.askalien.admin.AskalienAdminApplicationKt:2.4.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactoryBean.afterPropertiesSet(R2dbcRepositoryFactoryBean.java:167) ~[edu.muniz.askalien.admin.AskalienAdminApplicationKt:1.2.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[na:na]
askalien-admin_1  |     ... 31 common frames omitted

**Comment by sdeleuze** [comment]
Looks like https://youtrack.jetbrains.com/issue/KT-44594[KT-44594], could you please try with Kotlin `1.5.0-M2` to see if the error still happen?

**Comment by mmuniz75** [comment]
Hi Sebastien, 

With kotlin 1.5.0-M2 the server starts fine. thanks

But now I tried access a end point and got other error :  Cannot calculate JVM erasure for type: kotlin.collections.List<edu.muniz.askalien.admin.Answer>

In the sample webflux-kotlin I saw that domain class has this entry :
@TypeHint(types = [Bar::class], access = AccessBits.FULL_REFLECTION)

is this the same issue  ? 
Should I open other issue for handle that ?

**Comment by mmuniz75** [comment]
Hi Sebastien,

Works fine with kotlin 1.5.0-M2 . thanks
