### ISSUE TITLE
Add missing Thymeleaf expression language hints

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#725]
The org.thymeleaf.expression package contains a variety of classes that can be used in Thymeleaf templates e.g. `org.thymeleaf.expression.Arrays`, which is accessed in a template via `${#arrays.xxx()}`. This requires reflection config like the below example:

```
@TypeHint(types = {org.thymeleaf.expression.Arrays.class},
					access = AccessBits.LOAD_AND_CONSTRUCT_AND_PUBLIC_METHODS)}
```

On the basis that the project added IterStatusVar in https://github.com/spring-projects-experimental/spring-native/issues/679, I think the project could logically add something like the following for the 15-20 classes in the `org.thymeleaf.expression` package?

Happy to send a PR (including tests) if you think this makes sense.

**Comment by aclement** [comment]
Yes, I am not surprised we need to add some more. It is perhaps just a shame we will end up adding those that aren't being used to some apps, but I suspect working out which are required in a particular app is not easy.

Happy to take a PR, could perhaps enhance the existing sample to cover more kinds of expression.

**Comment by leccelecce** [comment]
PR provided to add the expression classes; I will look at improving the sample separately as having some issues getting the tests to pass on my machine even prior to the change.

I did think about whether I could create some kind of processor to scan through any templates found and identify which #xxx expressions were being used - but it felt like quite a bit of effort given the expression classes themselves look fairly small and straightforward.
