### ISSUE TITLE
Fail to generate image in Webflux+R2DBC+Validation project.

### ISSUE THREAD

**Issue by mmuniz75** [spring-projects-experimental/spring-native#731]
Fail to generate image in Webflux+R2DBC+Validation project.

The project is : https://github.com/mmuniz75/native-test2

Following the log :

Fatal error:java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurer
[INFO]     [creator]            at java.base/java.lang.Class.getDeclaringClass0(Native Method)
[INFO]     [creator]            at java.base/java.lang.Class.getEnclosingClass(Class.java:1517)
[INFO]     [creator]            at java.base/sun.reflect.annotation.AnnotatedTypeFactory.nestingForType(AnnotatedTypeFactory.java:96)
[INFO]     [creator]            at java.base/sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
[INFO]     [creator]            at java.base/java.lang.reflect.Executable.getAnnotatedReturnType0(Executable.java:642)
[INFO]     [creator]            at java.base/java.lang.reflect.Constructor.getAnnotatedReturnType(Constructor.java:618)
[INFO]     [creator]            at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedReturnTypeComputer.compute(Target_java_lang_reflect_Executable.java:168)
[INFO]     [creator]            at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:269)
[INFO]     [creator]            at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
[INFO]     [creator]            at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
[INFO]     [creator]            at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:178)
[INFO]     [creator]            at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:346)
[INFO]     [creator]            at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
[INFO]     [creator]            at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:388)
[INFO]     [creator]            at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1

**Comment by sdeleuze** [comment]
Maybe relayed to #730.

@mmuniz75 Are you using `0.9.2-SNAPSHOT`?

**Comment by mmuniz75** [comment]
Yes I am using 0.9.2-SNAPSHOT.

I just have the issue when I add : spring-boot-starter-validation

In fact I got the same issue of #730 so I added :
                <dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
		</dependency>

And just after that got the : Fatal error:java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurer

So looks like the same issue

**Comment by sdeleuze** [comment]
Shoukd be fine with latest snapshot (you can use `mvn -U` to force the fetch) since #730 has just been fixed. Please comment if still broken.

**Comment by mmuniz75** [comment]
I did the update and now without the javax.servlet:javax.servlet-api:4.0.1 entry I still got the same error to generate de image : 
Fatal error:java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurer
Please reopen the issue, I updated the pom.xml from the git repository with my code example.

**Comment by sdeleuze** [comment]
I had a deeper look, but it seems to be something broken at `native-image` level. Could you please create an issue on https://github.com/oracle/graal/issues with your repro and the error message, asking the GraalVM team to tag it with the `spring` label. Please also share the reference of the issue here.

**Comment by mmuniz75** [comment]
A issue was open to GraalVM team : https://github.com/oracle/graal/issues/3345
