### ISSUE TITLE
Getting test failures in packaging cloud-function-aws sample

### ISSUE THREAD

**Issue by Rohit-nagbhidkar** [spring-projects-experimental/spring-native#734]
I am using latest of spring native main branch
getting following error in test cases while doing
mvn install -P native-image

```
[ERROR] Failures: 
[ERROR]   ContainerTests.test:57 
Expecting:
 <"{"errorType":"exitError","errorMessage":"RequestId: 98a01853-76d6-1d96-182d-b3c6befe1701 Error: fork/exec /var/task/bootstrap: no such file or directory"}">
to contain:
 <"hi foo!"> 
```
build is failing for same
docker is getting up and running for the test case and then its failing

Using windows 10 64 bit
Java 11 and graalvm 21.0.0.2

**Comment by sdeleuze** [comment]
Did you use x64 Native Tools Command Prompt as recommended in the [GraalVM native-image prerequisite](https://www.graalvm.org/reference-manual/native-image/#prerequisites)?

**Comment by Rohit-nagbhidkar** [comment]
> Did you use x64 Native Tools Command Prompt as recommended in the [GraalVM native-image prerequisite](https://www.graalvm.org/reference-manual/native-image/#prerequisites)?

yes using x64 native tools
here is full command
"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && mvn package -Pnative

**Comment by sdeleuze** [comment]
@dsyer Do you now if this sample has something OS specific that would prevent it to work on Windows (since I tried and it work on my Linux machine)?

**Comment by dsyer** [comment]
The test (and the AWS lambda) runs in a Linux container? I never tried this in Windows so I don’t know, but I think you’ll have to build a Linux image for AWS anyway, so building using Windows graalvm is not going to work in the end on Amazon.

**Comment by Rohit-nagbhidkar** [comment]
> The test (and the AWS lambda) runs in a Linux container? I never tried this in Windows so I don’t know, but I think you’ll have to build a Linux image for AWS anyway, so building using Windows graalvm is not going to work in the end on Amazon.

tried on ubuntu wsl as well, still getting the same result
attaching the ouput of the build
[output.txt](https://github.com/spring-projects-experimental/spring-native/files/6315838/output.txt)

**Comment by dsyer** [comment]
I don't know how WSL works, but it's not building a Linux executable is it? I don't see how you can use the project as it is on Windows, unless you run inside a container. Have you tried using the `run-dev-container.sh` script in the root of this project?

**Comment by Rohit-nagbhidkar** [comment]
> @Rohit-nagbhidkar Are you using WSL or WSL 2?

using WSL-2

**Comment by sdeleuze** [comment]
`native-image` does not support cross compilation so indeed if you are using WSL2 make sure to a Linux version of native image. Also keep in mind I am not sure this is supported by GraalVM.

As suggested by @dsyer, your best bet is to build it using `run-dev-container.sh` script as documented [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#how-to-contribute-using-container-build-env).

**Comment by sdeleuze** [comment]
I am closing this issue since I don't see what we can do concretly. Please comment or send a PR if you think we should improve something.
