### ISSUE TITLE
Document how to generate a native image from Spring Boot executable JAR

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-native#736]
Hi

We would like to generate native image by native-image utility in Dockerfile:

native-image -jar custom-spring-boot.jar

But it seems that in generated fat jar META-INF/native-image folder is not root as described in GraalVM documentation:
https://docs.oracle.com/en/graalvm/enterprise/20/docs/reference-manual/native-image/BuildConfiguration/

It's located under BOOT-INF/classes and native-image is unable to detect it. Whereas Micronaut (and Micronaut plugins) create META-INF/native-image in the root folder in the generated jar.
So the question is: is it possible to generate GraalVM native image (using plugin or by another approach)?

**Comment by sdeleuze** [comment]
`native-image` does not recognize Spring Boot executable JAR format, and we currently provide 2 ways of creating native images via build plugins as documented https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started[here].

That said, native image creation being designed to be run on CI/CD platform and given the fact that most containers are CPU architecture specific, I see some value in providing the capability to turn a Spring Boot executable JAR to a native image. Just not sure how we could/should implement that.

Any thoughts @bclozel @snicoll @aclement ?

**Comment by sdeleuze** [comment]
Maybe [`pack`](https://buildpacks.io/docs/tools/pack/) already allows to do that ?

**Comment by sergey-morenets** [comment]
> 
> 
> `native-image` does not recognize Spring Boot executable JAR format, and we currently provide 2 ways of creating native images via build plugins as documented [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started).
> 
> That said, native image creation being designed to be run on CI/CD platform and given the fact that most containers are CPU architecture specific, I see some value in providing the capability to turn a Spring Boot executable JAR to a native image. Just not sure how we could/should implement that.
> 
> Any thoughts @bclozel @snicoll @aclement ?

Yes, that's correct. But **spring-boot:build-image** goal generates OCI image with native image application. Sometimes I want to build OCI (Docker) image by myself. In that case I just need a goal to compile native image but Spring Boot plugin doesn't support that now.

**Comment by sdeleuze** [comment]
For that you can use `native-image-maven-plugin` documented [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-image).

**Comment by sergey-morenets** [comment]
@sdeleuze 

Yes, but I will get fallback image, because unfortunately Native Image Builder doesn't recognize and support Spring Boot JAR Layout. So I will need JDK/JRE to run it.

**Comment by sdeleuze** [comment]
I mean from sources not the executable JAR (btw we disable fallback in Spring Native).
From executable JAR, you should be able to generate a container image (follow https://github.com/spring-projects-experimental/spring-native/issues/738). I am discussing with the GraalVM team if we should or not supporting generating a native image from a Spring Boot executable JAR, I will reopen this issue if we decide to support that.
