### ISSUE TITLE
How to specify a cert for creator

### ISSUE THREAD

**Issue by yswang1024** [spring-projects-experimental/spring-native#748]
Due to the company’s security policy, a self-signed certificate will be used when accessing GitHub. 
When I called command : mvn spring-boot:build-image -X and the process of [creator] started downloading "graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz",It throwed an Exception:

> [INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     4 of 11 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/graalvm        6.0.0
[INFO]     [creator]     paketo-buildpacks/executable-jar 5.0.0
[INFO]     [creator]     paketo-buildpacks/spring-boot    4.2.0
[INFO]     [creator]     paketo-buildpacks/native-image   4.0.0
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Previous image with name "docker.io/library/dc:0.0.1-SNAPSHOT" not found
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]
[INFO]     [creator]     Paketo GraalVM Buildpack 6.0.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/graalvm
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_VERSION              11.*            the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0               the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes  the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250             the number of threads in memory calculation
[INFO]     [creator]         $JAVA_TOOL_OPTIONS                           the JVM launch flags
[INFO]     [creator]       GraalVM JDK 11.0.10: Contributing to layer
[INFO]     [creator]         Downloading from https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency jdk
[INFO]     [creator]     unable to download https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
[INFO]     [creator]     unable to request https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
[INFO]     [creator]     Get "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz": x509: certificate signed by unknown authority
[INFO]     [creator]     ERROR: failed to build: exit status 1

How can I add cert for this, thx.

**Comment by sdeleuze** [comment]
@scottfrederick @dmikusa-pivotal Do you know if that's possible, and if yes how?

**Comment by dmikusa-pivotal** [comment]
The first thing I would suggest trying is https://paketo.io/docs/buildpacks/configuration/#ca-certificates. You'd provide the CA certificate that your company uses as a binding. The binding get's picked up by the ca-certs buildpack and added to the system truststore. The buildpack processes, which is what downloads the JVM in this case, should read those certs and trust what you've added.

If that doesn't work, or you can't find the right CA certificate to use, you can configure a dependency mapping which would allow you to relocate the downloads (you'd need to download the resources in advance and host them on your network) that are failing onto your network (or even locally on your machine). That way you don't have to connect to the Internet. See https://paketo.io/docs/buildpacks/configuration/#dependency-mappings

Hope that helps!

**Comment by sdeleuze** [comment]
Thanks @dmikusa-pivotal for the useful feedback.

**Comment by yswang1024** [comment]
Thanks for solutions, it works. @dmikusa-pivotal
