### ISSUE TITLE
Document properly Gradle tasks in Spring AOT refdoc

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#758]

**Comment by bclozel** [comment]
Many Gradle tasks contributed by our build plugin aren't meant to be called by users directly. Which tasks precisely did you have in mind?

**Comment by sdeleuze** [comment]
If I remember well, my use case was to make sure that the generated code and resources are up to date in JVM mode, and I found weird that we document nothing about that. Maybe we could document what the plugin provide with a warning to not use that directly, as well as the regular "public" tasks that people are expected to use?. That's useful to help to build a mental model of what happens.

I tentatively assign it to you since you will provide a more accurate documentation than me, please let me know if you prefer I take care with your guidance.
