### ISSUE TITLE
Add spring-cloud-schema-registry-client support

### ISSUE THREAD

**Issue by ivangfr** [spring-projects-experimental/spring-native#763]
Hi, I have [this project](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers) that uses `spring-native` and `spring-cloud` dependencies.

I know that `spring-cloud` is not yet fully supported but, maybe this issue can be analysed in future developments.

The problem is, when I use `spring-native` and `spring-cloud-schema-registry-client`, the response of REST endpoints are all in `XML` format instead of `JSON`.

For now, I am setting the MediaType `JSON` directly in the `@RequestMapping`
```
@RequestMapping(path = "/api/users", produces = MediaType.APPLICATION_JSON_VALUE)
```

However, for instance, if I get `HttpStatus.BAD_REQUEST`, I get the response in `XML`
```
<?xml version="1.0" encoding="UTF-8"?>
<Map>
   <timestamp>2021-05-01T10:12:17.325+00:00</timestamp>
   <status>400</status>
   <error>Bad Request</error>
   <exception>org.springframework.web.bind.MethodArgumentNotValidException</exception>
   ...
</Map>
```

Thanks!

**How to reproduce**

- git clone https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers.git
- cd spring-cloud-stream-event-sourcing-testcontainers
- git checkout xml-response-issue
- docker-compose up -d zookeeper kafka mysql schema-registry zipkin
- ./mvnw clean package spring-boot:run --projects user-service -DskipTests
- Valid call
  ```
  curl -i -X POST localhost:9080/api/users -H  "Content-Type: application/json" -d '{"email":"user@test.com","fullName":"User Test","active":true}'
  ```
- Invalid call (without `email` field that is required)
  ```
  curl -i -X POST localhost:9080/api/users -H  "Content-Type: application/json" -d '{"fullName":"User Test","active":true}'
  ```

**Comment by sdeleuze** [comment]
`spring-cloud-schema-registry-client` hints are probably required indeed.

**Comment by ivangfr** [comment]
Hi @sdeleuze . I've updated the project to **spring-boot** `2.5.1` and **spring-native** `0.10.0`, and the problem is fixed, at least, I am getting (by default) responses with JSON format. We can close the issue if you want. Thanks!

**Comment by sdeleuze** [comment]
@ivangfr Thanks for your feedback.
