### ISSUE TITLE
SpringFox 3.0 / Swagger Support

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#777]
Hello,
I am having basically the same setup and problems indicated within this issue:
https://github.com/spring-projects-experimental/spring-native/issues/635

It at least tried to dig in a little deeper by figuring out a lot of Typehints that need to be added.
But after a couple of hours still not working, i honestly gave up.
It should be doable, because micronaut and quarkus seem to support it.
Would be great to have it supported out of the box.

-- cut ---

@TypeHint(typeNames = {
        "springfox.documentation.spi.schema.ModelBuilderPlugin",
        "springfox.documentation.spi.schema.ModelPropertyBuilderPlugin",
        "springfox.documentation.spi.schema.SyntheticModelProviderPlugin",
        "springfox.documentation.spi.schema.TypeNameProviderPlugin",
        "springfox.documentation.spi.schema.ViewProviderPlugin",
        "springfox.documentation.spi.service.DocumentationPlugin",
        "springfox.documentation.spi.service.ApiListingBuilderPlugin",
        "springfox.documentation.spi.service.ApiListingScannerPlugin",
        "springfox.documentation.spi.service.DefaultsProviderPlugin",
        "springfox.documentation.spi.service.ExpandedParameterBuilderPlugin",
        "springfox.documentation.spi.service.ModelNamesRegistryFactoryPlugin",
        "springfox.documentation.spi.service.OperationBuilderPlugin",
        "springfox.documentation.spi.service.OperationModelsProviderPlugin",
        "springfox.documentation.spi.service.ParameterBuilderPlugin",
        "springfox.documentation.spi.service.ResponseBuilderPlugin",

        "springfox.documentation.service.PathDecorator",
        "springfox.documentation.spi.DocumentationType"
}, access = AccessBits.ALL)

**Comment by sdeleuze** [comment]
We try to limit what we support to dependencies managed on start.spring.io, and SpringFox 3.0 / Swagger is not part of that. That said, I understand this is a popular one, could you please create an issue on SpringFox side and link it here, I can try to provide guidance to them for a generic support.

**Comment by goafabric** [comment]
Thanks for your reply .. I can do that .. but I am honestly skeptical that the people there will do it.
Thanks for looking into the other flyway issue

**Comment by goafabric** [comment]
Opened:
https://github.com/springfox/springfox/issues/3816

**Comment by sdeleuze** [comment]
If somebody is interested to contribute it, please comment on the SpringFox issue.

**Comment by sdeleuze** [comment]
See also https://github.com/springdoc/springdoc-openapi/issues/1164.

**Comment by goafabric** [comment]
Thank you everybody for the work
