### ISSUE TITLE
Dependency injection from library

### ISSUE THREAD

**Issue by furkansavsatli** [spring-projects-experimental/spring-native#782]
I am using spring-native 0.9.2 and can run my services by removing bean injections. I also put 2 projects in the same directory so that the @ComponentScan annotation is not needed. If I add @Autowire annotations back, I get an error while inject the service beans defined in the libraries into the project I will use. 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'config': Unsatisfied dependency expressed through field 'sampleService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.sample.service.SampleService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired}

Other than that, ResourceUtils in the library may not be able to access the library resource. Likewise, if I use it only in the library, I get an error.

**Comment by sdeleuze** [comment]
Please provide a repro project.

**Comment by furkansavsatli** [comment]
Of cource.
https://github.com/furkansavsatli/Sample-Spring-Native

**Comment by erikknaake** [comment]
This seems to be the exact issue I am having, is there a way to get access to an early release, or compile it myself?

**Comment by sdeleuze** [comment]
0.10.0 has been pleased, otherwise yes you can use snapshots from https://repo.spring.io/snapshot.
