### ISSUE TITLE
Creating second MongoDB Template causes UnsupportedFeatureError

### ISSUE THREAD

**Issue by dmuecke** [spring-projects-experimental/spring-native#788]
In my application a primary MongoTemplate gets created using auto configuration. A second MongoTemplate gets created based on some business logic. Both databases are MongoDB Atlas clusters. During the creation of the second template I get an exception as shown below whereas the primary template works as expected.

Springboot: 2.4.5
spring-native: 0.9.2
Builder: paketobuildpacks/builder:tiny
Language: Kotlin
Java Version: 11

```

Exception in thread "cluster-ClusterId{value='60a4fa37759deb3f805b5b23', description='null'}-srv-rtds-prod-cluster-2-pl-0.ezl3n.mongodb.net" com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.trySetObjectField(String name, Object obj)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at java.lang.ClassLoader.trySetObjectField(ClassLoader.java:315)
	at java.lang.ClassLoader.createOrGetClassLoaderValueMap(ClassLoader.java:2993)
	at java.lang.System$2.createOrGetClassLoaderValueMap(System.java:2126)
	at jdk.internal.loader.AbstractClassLoaderValue.map(AbstractClassLoaderValue.java:266)
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:189)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:711)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at javax.naming.InitialContext.init(InitialContext.java:236)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:151)
	at com.mongodb.internal.dns.DefaultDnsResolver.resolveHostFromSrvRecords(DefaultDnsResolver.java:59)
	at com.mongodb.internal.connection.DefaultDnsSrvRecordMonitor$DnsSrvRecordMonitorRunnable.run(DefaultDnsSrvRecordMonitor.java:77)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)


```

**Comment by sdeleuze** [comment]
Could you please share a repro project?

**Comment by dmuecke** [comment]
The original code contains company code and can't be shared. 

The three classes involved are attached now. I'm getting the exception when calling function resolveMongoTemplateForCountry(...)




[native-image-mongodb.zip](https://github.com/spring-projects-experimental/spring-native/files/6509168/native-image-mongodb.zip)

**Comment by sdeleuze** [comment]
Sorry but yeah I will need a repro project with a demo to work on it.

**Comment by dmuecke** [comment]
Here the repo. If you need more details let me know.
[Example Repo](https://github.com/dmuecke/native-image-ex-1)

**Comment by sdeleuze** [comment]
I tried the sample, but tests fail on the JVM. Please make sure the app works fine on the JVM.

```
mvn test

The port 'password' is not a valid, it must be an integer between 0 and 65535
```

**Comment by dmuecke** [comment]
I've update the repo in order to pass mvn test. However the mogodb.uri points to an non-existing db `spring.data.mongodb.uri=mongodb://usr:password@localhost/RTDS-1?authSource=admin&ssl=true&tls=true`

I'm not sure if it's important to find the root cause of this issue but my original URI looks like 
`mongodb+srv://user:pwd@cluster-1.ezln.mongodb.net/DBXX?authSource=admin&ssl=true&tls=true`

**Comment by sdeleuze** [comment]
The previous URL was invalid so Spring Boot was not even starting in both JVM or native mode.

Now that compiles, but impossible to reach a MongoDB server, so please update `docker-compose.yml` to start a MongoDB server and update Boot config to reach it. The goal is to provide me a self reprodutible sample to allow me to help you solving this issue.

**Comment by dmuecke** [comment]
I've updated docker-compose.yml so it starts now with two databases. I've also updated README.md as you have to add a collection into both databases for positive tests.

**Comment by sdeleuze** [comment]
How do you add those 2 values from the host?

**Comment by dmuecke** [comment]
I was using IntelliJ/Database Tool to connect to first RTDS-1 and then to RTDS-2 but any mongo client should do it.
Then execute `db.BalanceStoreLiveStock.insert({"uploadDate":"2021-05-27","livestock": 1})`

**Comment by sdeleuze** [comment]
Sure, I have the mongo client installed, my question is more what URL are you using to access from the MongoDB instance that are running  inside containers on a bridge Docker network from the host.

**Comment by dmuecke** [comment]
Do you mean this `mongodb://localhost:27017/RTDS-1` and `mongodb://localhost:27018/RTDS-2`

**Comment by dmuecke** [comment]
I forgot to add usr/pwd in connection URI. I also made a small change in my repo so pls do a git pull first.

```
[~/dev/rtds/native-image-ex-1]$ mongo mongodb://usr1:password123@localhost:27017/RTDS-1                                                                                                                [github]
MongoDB shell version v4.4.5
connecting to: mongodb://localhost:27017/RTDS-1?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("866ab5ec-d239-455b-a6b2-21ef118b15f6") }
MongoDB server version: 4.4.6
> show dbs
RTDS-1  0.000GB
>
```

**Comment by sdeleuze** [comment]
Thanks, I was able to make your sample working, but no exception (I modified the value in the DB) and building an image with the JVM provide the exact same behavior.

**Comment by dmuecke** [comment]
I've written a comment in README.md that it's not always throwing an exception. In that case the line `val mongoTemplate = mongoTemplateResolver.resolveMongoTemplateForCountry(country)
            ?: return emptySequence()` returns with emptySequence(). To me it looks like `MongoTemplate(config.value.mongoDbFactory())` in `class MongoTemplateResolver` returns null.

**Comment by sdeleuze** [comment]
Sorry but I already spent a lot of time on this and without a way to reproduce it I can't do much more. Please reopen or recreate with a reliable way to reproduce it.

**Comment by dmuecke** [comment]
Ok, finally I figured out why you and even I couldn't reproduce the exception. It happens only if you have a connection uri like mongodb+srv://user:pwd@database/.... 
If you change it to mongo://user:pwd@database:port .... everything works as expected.
