### ISSUE TITLE
cloud-function-aws: cannot execute binary file

### ISSUE THREAD

**Issue by akuzni2** [spring-projects-experimental/spring-native#789]
I am trying to build and deploy in an AWS lambda function using spring native. I am using the project under samples called `cloud-function-aws` .

When I run the build script it says the build is successful. After building - I've uploaded the zip file to an AWS lambda function where I've specified the custom run time as Amazon Linux 2. After setting the handler I tried a test event and I get the following error:

```
START RequestId: <reqid> Version: $LATEST
/var/task/bootstrap: line 5: ./cloud-function-aws: cannot execute binary file
END RequestId: <reqid>
REPORT RequestId: <reqid>	Duration: 4.21 ms	Billed Duration: 5 ms	Memory Size: 512 MB	Max Memory Used: 7 MB	
RequestId: <reqid> Error: Runtime exited with error: exit status 126
Runtime.ExitError
```

**Comment by sdeleuze** [comment]
Any thoughts @spencergibb @dsyer ?

**Comment by dsyer** [comment]
From the `bash` man pages: `If a command is found but is not executable, the return status is 126.`. Usually in this context it means you compiled on Windows or MacOS and tried to run it on Linux (AWS). If you are not on Linux you have to build in a container.

**Comment by sunilinteti** [comment]
@dsyer Could you please post the docker file to run this ? I am on macOs and getting this return status as 126.  Many thanks

**Comment by dsyer** [comment]
There are scripts and docker images available as part of the project. Check out the docs: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#how-to-contribute-using-container-build-env

**Comment by dsyer** [comment]
It’s a custom runtime. There’s no way for the “normal” Java runtime to execute native code.
