### ISSUE TITLE
please add Automatic-Module-Name to MANIFEST.MF

### ISSUE THREAD

**Issue by wangxufire** [spring-projects-experimental/spring-native#790]
```xml
<manifestEntries>
   <Automatic-Module-Name>spring.graalvm</Automatic-Module-Name>
</manifestEntries>
```

current  automatic name is spring.native

Can't extract module name from spring-native-0.10.0-SNAPSHOT.jar: spring.native: Invalid module name: 'native' is not a Java identifier

because native is a java keyword

**Comment by sdeleuze** [comment]
I used `spring.nativex` like we do for packages.
