### ISSUE TITLE
Problem occurs when adding to gradle plugin

### ISSUE THREAD

**Issue by rhqnrehf** [spring-projects-experimental/spring-native#800]
This appears when testing.
When using the gradle wrapper, the above error continues to occur even if you set it in properties.

--

> Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
Task :generateTestAot FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':generateTestAot'.
Java heap space

**Comment by sdeleuze** [comment]
- Could you try with `--no-daemon` and let us know if that works (to be sure that's not a leak in another plugin, like Kotlin 1.5.0 Gradle plugin has)?
- Do you have any customization in `~/.gradle/gradle.properties`?
- Could you share a repro project?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by rhqnrehf** [comment]
Dear 
Try running it about 3 times while sout changing the getIssue TEST method in the test package.
The error is reproduced.

![캡처](https://user-images.githubusercontent.com/13612271/121177970-f838fa80-c898-11eb-8c73-2ca6008bdb7e.PNG)

project : https://github.com/rhqnrehf/spring-native-issue-temp

**Comment by sdeleuze** [comment]
Indeed, I can reproduce, this is a pretty bad one cc @bclozel @aclement.

First time I run it:
```
Failed verification check: this type was requested to be added to configuration but is not resolvable: io.netty.channel.socket.nio.NioSocketChannel it will be skipped
Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.web.reactive.socket.server.upgrade.TomcatRequestUpgradeStrategy it will be skipped
```

Second time I run it:
```
Failed verification check: this type was requested to be added to configuration but is not resolvable: io.netty.channel.socket.nio.NioSocketChannel it will be skipped
Failed verification check: this type was requested to be added to configuration but is not resolvable: io.netty.channel.socket.nio.NioSocketChannel it will be skipped
Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.web.reactive.socket.server.upgrade.TomcatRequestUpgradeStrategy it will be skipped
Failed verification check: this type was requested to be added to configuration but is not resolvable: org.springframework.web.reactive.socket.server.upgrade.TomcatRequestUpgradeStrategy it will be skipped
```

Third time I run it:
```
Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory
```
I am going to move 0.10.1 earlier than expected to solve this.
