### ISSUE TITLE
Runtime error when upgrading to Spring Boot 2.4.5 and Spring Boot Native 0.9.2

### ISSUE THREAD

**Issue by lujijiang** [spring-projects-experimental/spring-native#802]
Hi

I'm running spring-graalvm-native 0.9.2, Spring Boot 2.4.5 and java 11.
mvn spring-boot:build-image completes successfully and when I run the docker image I get the error below.

/workspace/com.saasxx.app.demo.AppDemoApplicationKt: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

**Comment by sdeleuze** [comment]
libz is a GraalVM `native-image` dependency documented [here](https://www.graalvm.org/reference-manual/native-image/#prerequisites).
