### ISSUE TITLE
Multi modules support

### ISSUE THREAD

**Issue by itziklavon** [spring-projects-experimental/spring-native#807]
Hi,
when viewing the note in samples regarding multi modules:
`the "core" module is a library used by our application. In general, such modules should hold dependencies to other libraries, but not Spring Boot starters.`

is there any way to make it so that core modules can hold spring starters?
thanks!

**Comment by bclozel** [comment]
Hello @itziklavon

This is already possible with our current support. This note in the sample is merely a general best practice for Spring Boot applications.

Starters should be applied on the actual Spring Boot application. If you'd like to add (optional) dependencies to modules, you can always add them explicitly and still apply the Spring Boot BOM without applying the actual Spring Boot build plugin.
