### ISSUE TITLE
Question: Limit Paketo Native Build Memory Usage

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#810]
Build Native Images with Paketo
inside Github Actions will hang eventually, the more libraries are on the classpath.
Because the System will run into an out of memory situation.

Within Quarkus it is possible to limit the memory usage of the native build:
 <quarkus.native.native-image-xmx>4096m</quarkus.native.native-image-xmx>

Is there something similar for the spring native paketo builds ?
At least nothing I could find in the documentation

**Comment by scottfrederick** [comment]
There are hints in the documentation, but for this use case you need to make some connections between a few pieces of information. Spring Native documents [how to set options for `native-image`](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-image-options) in the Paketo buildpacks, and GraalVM documents [the available options for `native-image`](https://www.graalvm.org/reference-manual/native-image/Options/). Putting those together, your build configuration including `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` might look something like this: 


```
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <image>
      <builder>paketobuildpacks/builder:tiny</builder>
      <env>
        <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
        <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>-J-Xmx4096m</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
      </env>
      <pullPolicy>IF_NOT_PRESENT</pullPolicy>
    </image>
  </configuration>
</plugin>
```

**Comment by goafabric** [comment]
Hi Scott .. thank you for the fast answer.
Yes this would work thank you very much.
Unfortunately the build still hangs / crashes .. sometimes a GC Out of Memor.
So i guess up to a certain point of libraries, currently 4 GB are not enough as stated in the spring native documentation.

Quarkus seems to be less demanding on the memory side.
So i guess the only thing i could dow now, either increase the memory at github actions
or waiting until the spring native builds are more memory friendly

**Comment by sdeleuze** [comment]
For your use case, Spring Native [0.11](https://github.com/spring-projects-experimental/spring-native/milestone/15) should come with less memory required for the build, so let's try again when it will be released.
