### ISSUE TITLE
Question: Can I configure the image as I do within a Dockerfile?

### ISSUE THREAD

**Issue by kambei** [spring-projects-experimental/spring-native#812]
Using Spring Native and Gradle, with `bootBuildImage` Gradle command, I can create the Docker image very easily.

There is a way for configure the image, for example adding an `HEALTHCHECK` or modifying the `ENTRYPOINT` with a custom configuration, the same way I can do within a Dockerfile???

Sorry if it is documented somewhere, but I have not found any info about it.

**Comment by wilkinsona** [comment]
This looks like a duplicate of https://stackoverflow.com/questions/67925092/how-can-i-configure-the-image-created-by-the-bootbuildimage-command.

**Comment by kambei** [comment]
Yes, that question on StackOverflow is mine too.

**Comment by sdeleuze** [comment]
This question seems not related to Spring Native, so Stackoverflow is probably better suited to get and answer.
