### ISSUE TITLE
bootBuildImage still uses GraalVM 21.0

### ISSUE THREAD

**Issue by joeyslalom** [spring-projects-experimental/spring-native#819]
I updated my 0.9.2 project to the new 0.10.0 release (congrats!) but noticed my `./gradlew boottBuildImage` command doesn't use GraalVM 21.1:
```
[creator]       Native Image: Contributing to layer
[creator]         GraalVM Version 21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)
```

From the "Upgrade to 21.1" commit https://github.com/spring-projects-experimental/spring-native/issues/578 I noticed this configuration from `samples`:
```
// TODO Bring back "paketobuildpacks/builder:tiny" before 0.10.0 release    
builder = "dmikusa/graalvm-tiny"
```

I can use `dmikusa/graalvm-tiny` builder as a workaround, but wanted to give a heads up in case this TODO was missed

**Comment by sdeleuze** [comment]
Sorry, we had an unexpected issue during the release that delayed of a few hours the Buildpacks update, but it should now uses GraalVM 21.1 as expected.
