### ISSUE TITLE
Duplicate warnings after consecutive generateAot gradle task

### ISSUE THREAD

**Issue by ArjanSchouten** [spring-projects-experimental/spring-native#820]
Every time I execute the `./gradlew clean test` task on a project from start.spring.io, I get more and more log output.

**Reproduction**
1. Download: https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.5.1.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native
2. Run `./gradlew test` and repeat a few times.

In my experience it doesn't matter if I run with `./gradlew clean` or remove the build directory 😕 .

The only thing that works is to run `./gradlew clean test --no-daemon`., so it looks like something is left in the [gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html) process.

**Comment by sdeleuze** [comment]
Please raise this issue on https://github.com/graalvm/native-build-tools/ side.
