### ISSUE TITLE
Spring Native 0.10.0 bootBuildImage error, MongoDB DefaultDbRefResolver can't be loaded

### ISSUE THREAD

**Issue by magnus-larsson** [spring-projects-experimental/spring-native#823]
With the final release of Spring Native 0.10.0 I get the following error when creating a native image of a Spring Boot app that use `spring-boot-starter-data-mongodb-reactive`:

```
[creator]     Error: Cannot find org.springframework.data.mongodb.core.convert.DefaultDbRefResolver.createLazyLoadingProxy, 
org.springframework.data.mongodb.core.convert.DefaultDbRefResolver can not be loaded, 
due to com/mongodb/client/MongoCollection not being available in the classpath. 
Are you missing a dependency in your classpath?
```

I did not see the error with earlier 0.10.0-SNAPSHOT versions. 
I guess it is related to https://github.com/spring-projects-experimental/spring-native/pull/811 - `Add substitution for Spring Data MongoDB LazyLoadingProxies`.

It seems like the substitution is not happening when I build the native image.

If I add an empty  `MongoCollection` - interface, the native image can be built.

I have created a Git-repo with a code example that demonstrates the error and that the error is gone after adding an empty  `MongoCollection` - interface. See https://github.com/magnus-larsson/ml-spring-native-issue-mongodb-defaultdbrefresolver and its `README.md` file.

Do I miss some configuration for the substitution to happen when the native image is built or what could be the problem?

**Comment by sdeleuze** [comment]
@christophstrobl Could you please qualify this one?

**Comment by christophstrobl** [comment]
@magnus-larsson thanks for reporting!
True, the substitution is missing another check that prevents it from being applied when only the reactive client is available. Sorry for the inconvenience.
