### ISSUE TITLE
Ignore AOT code generated in Eclipse with Maven

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-native#825]
In 0.10.0, the AOT plugin creates factory code for libraries that are bound to the `runtime` scope. E.g. Spring Data REST's HAL Explorer module is one, that is usually depended on in runtime scope. It ships with the package scoped `HalExplorerConfiguration` class for which I see a factory method generated by Spring AOT. That code of course refers to the type but it's not available in the compile scope.

I understand why the code is generated but wonder whether we need to stick to not doing that for code found in runtime dependencies?

**Comment by bclozel** [comment]
The AOT sources are compiled is a separate compilation pass - so the application sources are still compiled with the compile classpath. If the AOT plugin doesn't use the runtime classpath as a reference for source generation, then in this case the HAL explorer won't be compiled in the resulting native image.

Would that be the expected outcome in this case? Should runtime dependencies be treated differently in native images?

**Comment by odrotbohm** [comment]
The ultimate effect I see is that the project doesn't compile in the IDE anymore as the generated code references types from the runtime classpath. AFAIU, the step towards the AOT generated code is to avoid classpath scanning and reflection on Spring beans and configuration classes. I wonder if that could be somehow rather expressed through a `NativeConfiguration` for processing during the image build step.

The project builds fine on the command line so it's more of an inconvenience than a hard problem. In my case however, it breaks the entire project build in the IDE as I use ByteBuddy to enhance some classes and it finds the problematic type generated by Spring AOT and fails in turn.

**Comment by bclozel** [comment]
I see, that's a different issue then. Since we've moved the code generation to the package phase only and the application code is not supposed to know about the generated sources. Running the app in the IDE should not exercise the AOT code. Do we still want IDEs to be aware of those locations @sdeleuze ?

@odrotbohm Are you using Eclipse? I think we have an arrangement to let Eclipse know about the generated sources, maybe we should remove that.

**Comment by odrotbohm** [comment]
> @odrotbohm Are you using Eclipse? I think we have an arrangement to let Eclipse know about the generated sources, maybe we should remove that.

Yes. In Eclipse, the AOT generated code seems to be considered just like ordinary APT generated sources and thus are part of the in-IDE compile process. And I think you're right. They shouldn't be as that code doesn't actually need to be compiled during editing.

**Comment by sdeleuze** [comment]
Indeed I think we should probably ignore actions for `generate` like we do for `test-generate` [here](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-aot-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml).

**Comment by sdeleuze** [comment]
@odrotbohm Please test with `0.10.1-SNAPSHOT` and a fresh import in Eclipse when [the build](https://ci.spring.io/teams/spring-native/pipelines/spring-native) will be done.
