### ISSUE TITLE
Automatically register class proxy hint for user components that need it

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-native#826]
User components that do not implement interfaces but make use of annotations that case the type needing to be proxied (e.g. `@Async`, `@Transactional` etc.) currently need an explicit `@AotTypeHint` declared. We should be able to detect that the proxy class is needed and automatically register that fact so that the explicit hint is not needed.

**Comment by sdeleuze** [comment]
@aclement Should we target 0.10.1 or 0.11 for this one?

**Comment by aclement** [comment]
I'd like to get some work done on it in the 0.10.x line. @odrotbohm do you have suitable test projects lying around for the most important situations?

Also, in discussing Spring Data needs with Christoph, any code that currently doesn't go through the default proxy factory will either need to be adapted to do so, or it will need another substitution. So there can be more to it than just smartly computing `AotProxyHint`s.

**Comment by odrotbohm** [comment]
I am currently upgrading RESTBucks to 0.10 to see what explicit hints are still needed. So far, I've been able to remove most of them I had before. So great job already! I'll ping you once the branch is in place. Im gonna link the tickets I file for each of the explicit hints I think we can get rid of once we fix those tickets.

**Comment by odrotbohm** [comment]
The [`hacking/native-buildpacks`](https://github.com/odrotbohm/spring-restbucks/tree/hacking/native-buildpacks) branch here has the necessary setup to build RESTBucks as a native image. `NativeConfiguration` contains a few explicit hints with the tickets linked which I think make those obsolete. It should build and work fine, just take a while (25 Minutes on my machine).

**Comment by aclement** [comment]
`@Async` and `@Transactional` are now being handled and produce Aot class proxies (new sample added for async).

**Comment by odrotbohm** [comment]
Verified to be working on 0.10.1 snapshots.
