### ISSUE TITLE
Register first generic type of JPA attribute converters for reflective inspection

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-native#829]
A JPA `AttributeConverter`'s first generic type needs to be available for reflection with `AccessBits.LOAD_AND_CONSTRUCT`. The hint currently has to be added manually but should be easily detectable generically when inspecting the application code. From `AttributeConverter<X, Y>` we need to register `X` with aforementioned settings.

**Comment by sdeleuze** [comment]
I will let @schauder and/or @christophstrobl qualify this one.

**Comment by odrotbohm** [comment]
This seems to be working already. The problematic case I had at hand was using an interface in the signature and Hibernate trying to reflect on the implementation class, which is of course not appearing in any declaration. In my particular case I was able to declare the `convertToEntityAttribute(…)` to actually return the implementation type and that renders the custom hint previously necessary obsolete.
