### ISSUE TITLE
Paketo Native Build compatible with Apple Silicon M1 and Curl

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#836]
Hello everybody,
it would be great to have a Paketo Native Build that also works with Apple Silicon M1.
While the Quarkus People don't support this out of the box,
they allow to set an alternative Builder Image:
https://dev.to/nevernull/building-a-native-java-application-for-arm64-with-quarkus-2n9m

Note, the mentioned base is now: ghcr.io/graalvm/graalvm-ce:java11-21.0.0.2 

There just an universal graalvm build image by oracle is used, that works on both amd64 + arm64 ..
Works like a charm an apple silicon.
Unfortunately there is also currently no graalvm natively for macos on apple silicon.
So this solves also this issue.

And 2nd .. i do not want to open an extra issue for this rather small thing:

Is there a way to get a Docker image with CURL included, except for using "paketobuildpacks/builder:full" ?
Because this result in insanely big image sizes of 700MB .. i would expect that at least the builder:base would contain curl ... as needed for Docker Healthchecks.

Thank u very much

**Comment by sdeleuze** [comment]
Please raise those issues at https://github.com/paketo-buildpacks/native-image.

**Comment by scottfrederick** [comment]
@goafabric You can follow these Paketo issues for M1 / ARM64 support in buildpacks: 

- https://github.com/buildpacks/lifecycle/issues/435
- https://github.com/paketo-buildpacks/stacks/issues/51

**Comment by goafabric** [comment]
thank you scott
