### ISSUE TITLE
Investigate spring.factories key processing for all keys

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#842]
Earlier today I committed some changes so that instead of just processing the EnableAutoConfiguration key, we processed the values of some other keys that had a test prefix. The more general rule should be processing all configurations regardless of the key. We should investigate the impact of this and what would break if we went that far. Perhaps in normal apps it is only EnableAutoConfiguration listed entries but the test scenarios have revealed anyone could be listing configs under a different key.

**Comment by aclement** [comment]
Not going to get to this in 0.10.2 - likely unnecessary with 0.11 re-architecture?

**Comment by sdeleuze** [comment]
Yes let's close it then.
