### ISSUE TITLE
How to debug running service in native-image mode

### ISSUE THREAD

**Issue by kennygitchen** [spring-projects-experimental/spring-native#843]
hi guys,
It's more of a question other than an issue I guess. 

I have a garage project that I am using Spring-Native to build a reactive RESTFul service. Instead of using pure Reactor, I am using coroutine. With little marking around, I have got service up and running with the native image build. 

Is there a way that I can debug/inspect the service that is running in native mode?

**Comment by sdeleuze** [comment]
You can debug it using GDB, we will provide more documentation on that via #227.
