### ISSUE TITLE
Non-ASCII Java classes produce errors

### ISSUE THREAD

**Issue by plcrdv** [spring-projects-experimental/spring-native#846]
having non-ascii Java classes (in my case, using Japanese characters) and attempting to use spring native in the project results in exceptions being thrown during compile time, or during run time (if these files are first packaged in a jar and included in the project), even if encoding parameters are explicity set to UTF8 via command line, or via parameters in creating a docker image.

**Comment by sdeleuze** [comment]
Could you please share the error messages you get and/or a repro project?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
