### ISSUE TITLE
Native application performance goes down dramatically.

### ISSUE THREAD

**Issue by shiliangshuai** [spring-projects-experimental/spring-native#848]
Dears,

Follow https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-build-tools, I find the performance reduced by half, TPS reduce from 50699.66 to 19531.48

Environment:
- CentOS Linux release 8.3.2011
- GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
- Spring Boot 2.5.1
- Spring Native 0.10.0

JMeter: 100 Threads, 50000 Loops

Performance Result:
![image](https://user-images.githubusercontent.com/4186744/122731045-7b048100-d2ad-11eb-923f-9b1b94b5a3c6.png)

Is there any thing I missed? 

Thanks a lot.

**Comment by phejl** [comment]
Perhaps this more for the GraalVM team and some inspection of compilation actually happening. OTOH people often think in terms native -> fast, jvm -> slow while it is a trade of (at least for the time being). You get instant startup and smaller memory footprint with Native Image but peak performance is usually better with JIT compiler.

**Comment by sdeleuze** [comment]
Indeed, JVM is expected to have better throughput and lower latency if you have enough memory while native usually perform better on memory contraints environnement. We will do more performance toward end of the year. In the meantime, if you find something unusual please report to GraalVM team.
