### ISSUE TITLE
Proxy entries for annotations on interface not created

### ISSUE THREAD

**Issue by phejl** [spring-projects-experimental/spring-native#854]
When controller extends interface which defines the contract (ie openapi generator generates such) the annotations present on the interface are not processed and thus proxy entries containing `SynthesizedAnnotation` are not created.

**Comment by phejl** [comment]
I'll try to provide a patch.

**Comment by phejl** [comment]
Hopefully fixed in https://github.com/spring-projects-experimental/spring-native/pull/857

**Comment by aclement** [comment]
PR is merged
