### ISSUE TITLE
Support for @EntityListeners

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#869]
Now with version 0.10.1 adding Transactional out of the box for classes .. thats a very good step in the right direction.
What is currently not working is the Annoation of @EntityListners
e.g 

@EntityListeners(AuditJpaListener.class)
public class PersonBO{}

The class just never gets called .. funny enough no error during aot compilation or bootstrap .. just seems to be ignored.
Works of course in JVM mode.

Would be nice to get this fixed, or a hint into the right direction.
Thx

**Comment by phejl** [comment]
@goafabric I'm not an expert but only thing I needed to do in my simple test case was to add TypeHint for the listener class. Sure it would be nicer if this was detected automatically. Just providing workaround and checking with you whether it is the same problem you observe.
Try to add `@NativeHint(types = @TypeHint(types = AuditJpaListener.class))` to your application class.

**Comment by phejl** [comment]
I'll try to provide a fix.

**Comment by goafabric** [comment]
Hi @phejl,
thanks for your support .. yes that might actually work .. in Quarkus you have to do something similar.
I just tried to avoid Typehints in general ,.. but i see that you also provided a fix ...

**Comment by goafabric** [comment]
@phejl 
do you also have an Idea for the not working ApplicationContextAware

**Comment by phejl** [comment]
> @phejl
> do you also have an Idea for the not working ApplicationContextAware

@goafabric Hm, I don't think it is directly related. Would you please file a separate issue with details of your usecase?

**Comment by goafabric** [comment]
> > @phejl
> > do you also have an Idea for the not working ApplicationContextAware
> 
> @goafabric Hm, I don't think it is directly related. Would you please file a separate issue with details of your usecase?

Its indirectly related .. i opened the #949 for this

**Comment by sdeleuze** [comment]
Let see how that goes with 0.11.

**Comment by venkataklagisetty** [comment]
hi ,I got same problem with entityListener, is that resolved?

**Comment by snicoll** [comment]
@venkataklagisetty this issue is open so it's likely not resolved.

**Comment by venkataklagisetty** [comment]
> @venkataklagisetty this issue is open so it's likely not resolved.

@snicoll  Thanks for confirming that, is there any alternate approach available to resolve this issue now?
