### ISSUE TITLE
[Gradle plugin] Is there a way to pass native image options for native binary build ?

### ISSUE THREAD

**Issue by gvart-sellics** [spring-projects-experimental/spring-native#872]
The documentation says that there's a way to pass [Native image options](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/index.html#native-image-options) using BP_NATIVE_IMAGE_BUILD_ARGUMENTS variable, but how to pass those variables for build with **Native Build Tools** via **nativeBuild** task?

**Comment by phejl** [comment]
@gvart-sellics If you mean https://github.com/graalvm/native-build-tools I think you can just provide `buildArgs` - both gradle and maven provide this option.

**Comment by gvart-sellics** [comment]
Finally found here's an parameters that could be configured.
![image](https://user-images.githubusercontent.com/82597139/124047377-5f6b4a00-da14-11eb-9818-74114db9ecd5.png)

**Comment by sdeleuze** [comment]
Sorry I missed that one, yes `@TypeHint(options = ...)` is probably the best way to configure that since that will work for a wide range of use cases (Gradle and Maven, Buildpacks and Native build tools).
