### ISSUE TITLE
Add support for Spring Data MongoDB (lazy loading) DocumentReference annotation.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-native#875]
Spring Data MongoDB 3.3 (part of the 2021.1 release) will introduce `@DocumentReference` as an alternative to `@DBRef`. The annotation needs to be considered when creating proxy configuration for the domain types, just as `@DBRef` is now.

----

Relates to: #853
Depends on: #874

**Comment by sdeleuze** [comment]
Fixed by 8ce2019cbfae6dbc1545fe44602cf5f8365b9dd3 and 6ba10575efd0ada99bb6a5fe95c56cb5b947e5c1.
