### ISSUE TITLE
Avoid confusing message when using logback.xml

### ISSUE THREAD

**Issue by phejl** [spring-projects-experimental/spring-native#877]
The message says the extension of logback.xml is unexpected and should be groovy or xml. It should be way clearer.

Relates to https://github.com/spring-projects-experimental/spring-native/issues/625

**Comment by sdeleuze** [comment]
Indeed, I have refined it. Notice there is not yet a clean early error handing that would display the error message with the build time init error. The purpose of this substitution is mainly to avoid XML infra to be reachable by native image static analysis.

**Comment by phejl** [comment]
@sdeleuze Nice! You faster than me :)
