### ISSUE TITLE
Build failure - No instances of com.fasterxml.jackson.core.io.SerializedString are allowed in the image heap

### ISSUE THREAD

**Issue by kewats** [spring-projects-experimental/spring-native#885]
Hi, I am working on switching a module inside an existing spring-boot project to use native. My `nativeBuild` is failing with the error below.

> Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.fasterxml.jackson.core.JsonFactory._createGenerator(java.io.Writer, com.fasterxml.jackson.core.io.IOContext)
> Parsing context:
>         parsing com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1318)
>         parsing com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1164)
>         parsing com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3725)
>         parsing a.b.c.Util.writeManifest(Util.java:61)

> Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of com.fasterxml.jackson.core.io.SerializedString are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=com.fasterxml.jackson.core.io.SerializedString.
>         at parsing com.fasterxml.jackson.core.JsonFactory.<clinit>(JsonFactory.java:186)
>         at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2601)

This is triggered at this piece of code:

```
      ObjectMapper mapper = new ObjectMapper();
      mapper.writeValue(writer, convertedResults);
```

I am using:
```
  id 'org.springframework.boot' version '2.5.2'
  id 'org.springframework.experimental.aot' version '0.10.1'
  id 'org.graalvm.buildtools.native' version '0.9.0'
```
```
nativeBuild {
  buildArgs("--trace-object-instantiation=com.fasterxml.jackson.core.io.SerializedString --verbose -H:+ReportExceptionStackTraces")
}
```

> openjdk version "11.0.11" 2021-04-20
> OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
> OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

I tried reproducing this issue in a standalone spring native project, however, did not run into the same problem.
Would you have any pointers on how I can go about investigating this further?

Thanks!

**Comment by sdeleuze** [comment]
I would suggest putting a breakpoint in `com.fasterxml.jackson.core.io.SerializedString` on the JVM to understand where it is used the first time. In your application, it is maybe used early (logging?) by a class that is itself initialized at build time. Please share a repro to allow us to move forward.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kewats** [comment]
I haven't been able to spend time on carving out a standalone repro for this issue. I will close this issue for now and reach out for help in future when I am able to get back to this. Thanks for your help!
