### ISSUE TITLE
Perform AOT processing for event listeners

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#910]
Event listeners beans defined in `AnnotationConfigUtils` were disabled via 16b62d5 because it was using reflection on all the autoconfigurations which defeats the purpose of `0.11.x` branch in term of efficiency.

After discussion with @bclozel and @jhoeller, it seems we'd have to perform the scanning part at AOT level, and generate the code that will perform the injection at runtime.

For `@EventListener`, we could programmatically register a corresponding `ApplicationListenerMethodAdapter` for every method that we detect at build time. We'd still reflectively invoke the listener method then but we wouldn't use reflection to find those annotated methods anymore.

**Comment by snicoll** [comment]
I already have a prototype for this.

**Comment by snicoll** [comment]
Fixed by 49cdd09
