### ISSUE TITLE
Add AOT processing for ApplicationContexts used in tests

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#911]
That would allow to support the `*-agent` samples.

**Comment by sdeleuze** [comment]
It probably makes sense to wait for #912 to be fixed to work on this one.

**Comment by snicoll** [comment]
I've started to investigate this, using `MergedContextConfiguration` that's quite easy to call at build time using a source test class. This can also be used to figure out if the configuration of this test class matches another one. I have a prototype that generates the code but I haven't really tried to hook the test engine to it yet.

**Comment by snicoll** [comment]
This turned out to be quite significant but we have things working on the AOT/JVM side of things with additional issues to cover what doesn't work yet on native.
