### ISSUE TITLE
Merge native-next mode behavior into native mode

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#912]
I don't think it is worth maintaining both `native` and `native-next` modes in parallel. Maintaining hints is already a challenge and it will be even more with 2 different variants. Also we need to use this opportunity to simplify our code base and not add more complexity. `0.10.x` development is almost frozen and we can rebase `0.11.x` branch on top of `main` as of `0.10.2` is released. We could then use `main` to have the current `native` behavior and compare it to the `0.11.x` native behavior based on `ContextBootstrap` generation.

**Comment by aclement** [comment]
It's merged and native-next is gone (there is a little more tidy up to do as we go). `commandlinerunner` and `webmvc-tomcat` are working, although I am quite nervous how things will shake down as more samples are brought online but let's see what happens.

Difference in lines in reflect-config.json between 0.10 and 0.11:
`commandlinerunner` was 1236, now 505 (can be lower if property reflection entries not included). (RSS from 24.1 > 20.1)
`webmvc-tomcat` was 2526, now 1071 (can be lower if property reflection entries not included). (RSS from 53.5 > 38.5)

This is a further 300 lines less for each sample compared to what I had the other day with early 0.11 work. There is more we will be able to remove too.

**Comment by sdeleuze** [comment]
Thanks Andy, great results! Other samples will be challenging for sure but that's the right path IMO also we will probably start using extension points in the new AOT mechanism as discussed with @bclozel and @snicoll.
