### ISSUE TITLE
Support Spring GraphQL

### ISSUE THREAD

**Issue by cnolte** [spring-projects-experimental/spring-native#914]
I know spring graphql is still experimental. But are there any plans to support it?

**Comment by sdeleuze** [comment]
Yes, I have added to the backlog, just we are working on other priorities right now.

**Comment by joshlong** [comment]
Hi - i have an example that demonstrates Spring GraphQL and the graphiql console working with [Spring Native 0.11.x here](https://github.com/joshlong/graphql-spring-native)

**Comment by cnolte** [comment]
Thank you so much. With your help I was able to run my App native.
