### ISSUE TITLE
Useful `multi-module` sample

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects-experimental/spring-native#915]
I'm facing issues packaging a multi-module application. I followed `multi-module` sample but have issues with components from lib modules not being packaged in fat-jar nor native app.

What works: the app starts from my IDE and with `mvn spring-boot:run`.

What doesn't: `java -jar target/app-0.0.1-SNAPSHOT.jar` and `docker run --rm -p 8080:8080 app:0.0.1-SNAPSHOT`

What I'd like from `multi-module` sample: being slightly more consistent, I mean something with a `@Service` (or any other `@Component` like a `@Repository`) in a lib and an app using it done in like https://spring.io/guides/gs/multi-module/

**Comment by ch4mpy** [comment]
Actually, I updated the sample as mentioned and ... it works. I'll propose a PR tomorrow with enrichment once I have written tests.

**Comment by bclozel** [comment]
Alright thanks, we'll discuss the changes on your PR.
Note that this sample is really about build configuration and it's not meant to be a canonical example of a multi-module Spring application.
