### ISSUE TITLE
Problem when add JNA library

### ISSUE THREAD

**Issue by hoangvantu** [spring-projects-experimental/spring-native#919]
I builded success.
But when run exe 
problem JNA: Problems loading core IDs: java.lang.Object
I used Pom with config spring-aot with config native-agent

> 	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.experimental</groupId>
				<artifactId>spring-aot-maven-plugin</artifactId>
				<version>${spring-native.version}</version>
				<executions>
					<execution>
						<id>test-generate</id>
						<goals>
							<goal>test-generate</goal>
						</goals>
					</execution>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<mode>native-agent</mode>
					
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<classifier>${repackage.classifier}</classifier>
					<image>
						<builder>paketobuildpacks/builder:tiny</builder>
						<env>
							<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
						</env>
					</image>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>create-native-image-config-folder</id>
						<phase>test-compile</phase>
						<configuration>
							<target>
								<mkdir dir="target/classes/META-INF/native-image"/>
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<argLine>-DspringAot=true -agentlib:native-image-agent=access-filter-file=src/test/resources/access-filter.json,config-merge-dir=target/classes/META-INF/native-image</argLine>
				</configuration>
			</plugin>

		</plugins>
	</build>

Please help me to use native hint or add config build argument for run .

**Comment by sdeleuze** [comment]
Hi, GraalVM native does not provide support for JNA as stated [here](https://github.com/oracle/graal/issues/673#issuecomment-583413789) so I close this issue.
