### ISSUE TITLE
Revisit generated sources contribution in Gradle plugin

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#922]
As underlined in #873, the AOT Gradle plugin currently operates in a way that the native GraalVM plugin cannot know about sources and resources contributed during the AOT generation phase. Our plugin is currently manually adding those to the `bootRun` and `bootJar` tasks, as we've initially considered a tight coupling between this plugin and the Spring Boot Gradle plugin.

This issue should be considered with the maintainers of the native GraalVM plugin, so that we can revisit the contribution mechanism our plugin is using for generated sources and resources. 

We could consider an easy fix: only use the compile classpath of the main sourceset instead of the runtime classpath, and contribute the generated sources/resources to the runtime classpath. This could cause two issues:
1. the generation phase would not consider the runtime classpath of the application, possibly leaving out dependencies expressed by the build
2. the generated sources/resources would be present in the runtime classpath adn this could have unintended consequences for IDEs and other tools. This could also be a good thing if we consider the generated sources as useful for the non-native use case

**Comment by sdeleuze** [comment]
See potentially related comment https://github.com/spring-projects-experimental/spring-native/issues/873#issuecomment-890334744.

**Comment by sdeleuze** [comment]
See [this comment](https://github.com/spring-projects-experimental/spring-native/issues/948#issuecomment-899696049) and [this related PR](https://github.com/graalvm/native-build-tools/pull/98) which will modify the DSL.

**Comment by bclozel** [comment]
Blocked on #1031
