### ISSUE TITLE
Infer @AotProxyHint for @Scope beans

### ISSUE THREAD

**Issue by pugazhendhit** [spring-projects-experimental/spring-native#928]
How to use the '@.Bean' with  '@RequestScope' in Spring  Native , with constructor injection ? .  

Currently i am getting the bellow issue in the logs , under this  . 

```
@Configuration
public class CommonConfig {

    @Bean
    @RequestScope
    public HeaderRequest headerRequest() {
        return new HeaderRequest();
    }

    @Bean
    public BuildHeaderResponse buildHeaderResponse(HeaderRequest headerRequest) {
        return new BuildHeaderResponse(headerRequest);
    }
}
```

```
@Slf4j
@Configuration
public class RequestResponseFilter implements Filter {

    private final HeaderRequest headerRequest;

    public RequestResponseFilter(HeaderRequest headerRequest) {
        this.headerRequest = headerRequest;
    }

}

```

**Logs** 

2021-07-25 17:09:33.024  INFO 1 --- [           main] c.k.p.c.c.PaotangCommonConfigApplication : Starting PaotangCommonConfigApplication using Java 11.0.11 on bc691b63bc80 with PID 1 (/workspace/com.krungthai.paotang.common.config.PaotangCommonConfigApplication started by cnb in /workspace)
2021-07-25 17:09:33.024  INFO 1 --- [           main] c.k.p.c.c.PaotangCommonConfigApplication : No active profile set, falling back to default profiles: default
2021-07-25 17:09:33.079  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
Jul 25, 2021 5:09:33 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jul 25, 2021 5:09:33 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jul 25, 2021 5:09:33 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.48]
2021-07-25 17:09:33.081  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 56 ms
Jul 25, 2021 5:09:33 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
2021-07-25 17:09:33.086  WARN 1 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
**2021-07-25 17:09:33.093 ERROR 1 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'requestResponseFilter' defined in class path resource [com/krungthai/paotang/common/config/filters/RequestResponseFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'headerRequest' defined in BeanDefinition defined in class path resource [com/krungthai/paotang/common/config/configs/CommonConfig.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.aop.scope.ScopedProxyFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.aop.scope.ScopedProxyFactoryBean.<init>()
Jul 25, 2021 5:09:33 PM org.apache.catalina.core.StandardService stopInternal**
INFO: Stopping service [Tomcat]
2021-07-25 17:09:33.094  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2021-07-25 17:09:33.096  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-07-25 17:09:33.096 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for org.springframework.aop.scope.ScopedProxyFactoryBean.<init>() is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

**Comment by ttddyy** [comment]
Hi,

I just tried `@RequestScope` bean and reproduced the same error.

After adding this hint, it worked.

```java
@NativeHint(
        types = @TypeHint(types = {ScopedProxyFactoryBean.class},
                access = AccessBits.LOAD_AND_CONSTRUCT | AccessBits.PUBLIC_METHODS),
        aotProxies = @AotProxyHint(targetClass = Foo.class,   // <== request scoped class 
                interfaces = {ScopedObject.class, Serializable.class, AopInfrastructureBean.class})
)
```

**Comment by pugazhendhit** [comment]
@ttddyy   It works after adding the above Hint . Thanks  

Where i can find the documentation for the NativeHint  ? .

**Comment by sdeleuze** [comment]
@pugazhendhit [Here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints).

@ttddyy Thanks for your help on this.

@aclement We should maybe wait for 0.11 to be available to add the right "trigger" since we should be able to add those on `@RequestScope` annotated beans more easily.

**Comment by snicoll** [comment]
@sdeleuze I am not sure this one is still applicable. It might and we could infer those hints perhaps if you can guide me?

**Comment by sdeleuze** [comment]
With `0.11.0-SNAPSHOT`, we only need the `@AotProxyHint(targetClass = Foo.class, interfaces = { ScopedObject.class, Serializable.class, AopInfrastructureBean.class })` part for `Foo` beans annotated with `@RequestScope`.

@snicoll Could you please provide quick guidance on where/how to implement that?

**Comment by snicoll** [comment]
Something like this?

```java
new BeanFactoryProcessor(beanFactory).processBeansWithAnnotation(Scope.class, (beanName, beanType) ->
		registry.proxy().add(NativeProxyEntry.ofClass(beanType, ProxyBits.NONE,
				ScopedObject.class, Serializable.class, AopInfrastructureBean.class)));
```

That would take all scope so you may want to narrow it down as not all scope requires a proxy.

**Comment by sdeleuze** [comment]
Ok thanks I will try and let you know.
