### ISSUE TITLE
Unable to invoke `cloud-function-aws` sample on AWS Lambda

### ISSUE THREAD

**Issue by samuel-bach** [spring-projects-experimental/spring-native#941]
I built and deployed the sample [cloud-function-aws](https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws) to AWS but are not able to call it.
I set the handler in AWS Console to `org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest` according to [cloud-function docs](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_aws_request_handlers) but only get this output when invoking the Lambda:

```
:: Spring Boot :: (v2.5.3)
[ main] com.example.demo.DemoApplication : Starting DemoApplication v0.0.1-SNAPSHOT using Java 11.0.10 on 169.254.24.205 with PID 9 (/var/task/cloud-function-aws started by sbx_user1051 in /var/task)
[ main] com.example.demo.DemoApplication : No active profile set, falling back to default profiles: default
[ main] o.s.c.f.web.source.SupplierExporter : Starting
[ main] o.s.c.f.c.c.SimpleFunctionRegistry : Failed to locate function: origin\|org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
[ main] o.s.c.f.web.source.SupplierExporter : No such Supplier: origin\|org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
[ main] com.example.demo.DemoApplication : Started DemoApplication in 0.17 seconds (JVM running for 0.317)
Started
```

Do I need to provide a different handler when using spring-native?

**Comment by sdeleuze** [comment]
@dsyer Could you please have a look to this issue?

**Comment by sdeleuze** [comment]
@olegz Please qualify this one.

**Comment by mhalbritter** [comment]
Could you please try this with Spring Boot 3 and the new Cloud release (will be released 2022-12-14 according to https://calendar.spring.io/) and report an issue if this still doesn't work? Thanks!
