### ISSUE TITLE
Update nativeBuild/nativeTest configuration in samples and docs 

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#948]
See https://github.com/spring-projects-experimental/spring-native/issues/873#issuecomment-890334744

**Comment by sdeleuze** [comment]
@darxriggs Any thoughts on what should be the equivalent for `nativeTest`?

I tried:
```
nativeTest {
	classpath(processAotTestResources.outputs, aotTestClasses.outputs)
}
```
But got `java.lang.NoSuchMethodException: org.springframework.test.context.web.ServletTestExecutionListener.<init>()` despite  `build/generated/resources/aotTest/META-INF/native-image/org.springframework.aot/spring-aot/reflect-config.json`containing the `org.springframework.test.context.web.ServletTestExecutionListener` when I run `./gradlew clean nativeTest`.

(tested with native build tools 0.9.3-SNAPSHOT from https://github.com/graalvm/native-build-tools/)

**Comment by sdeleuze** [comment]
It seems to work with:

```
nativeTest {
	classpath(processAotTestResources.outputs, compileAotTestJava.outputs)
}
```
So I guess we should use that for `nativeBuild`:
```
nativeBuild {
	classpath(processAotResources.outputs, compileAotJava.outputs)
}
```

**Comment by darxriggs** [comment]
@sdeleuze It looks like you figured out the proper targets.

My initial comment was based on the task dependency diagrams of Gradle's [Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html) and [Groovy plugin](https://docs.gradle.org/current/userguide/groovy_plugin.html).

I was aiming for all potential languages and therefore suggested the aggregate task `aotClasses` (like `classes` for the Java/Groovy plugin). My understanding of task dependencies vs. outputs was not correct. The output of an aggregated task is not the aggregated output of the tasks it depends on. This can be verified using the task graph as described in [here](https://discuss.gradle.org/t/how-to-print-the-inputs-and-outputs-for-a-task/3255/2).

So as long as there are only Java-based compile tasks in this plugin, using them explicitly in the examples (as you did) seems to be the way to go.
