### ISSUE TITLE
Resource file from library

### ISSUE THREAD

**Issue by furkansavsatli** [spring-projects-experimental/spring-native#952]
There is a case similar to the previously opened issue https://github.com/spring-projects-experimental/spring-native/issues/782. If I put the file in resource, I can't access it. If I move the file to the core project without making any changes to the code, there will be no problem. I also updated the relevant project https://github.com/furkansavsatli/Sample-Spring-Native.

**Comment by ttddyy** [comment]
Hi @furkansavsatli 

I tried your project.

First, there is a typo in `SampleService` in your `SampleLibrary`.
It tries to read `files.txt`, but it should be `file.txt`.

Then, in `pom.xml` in `SampleCore`, change the `-H:IncludeResources='.*/file.txt$'` to `-H:IncludeResources=file.txt`(exact filename without single quote). It worked.
I tried a couple of regex but couldn't make it work. It worked for me if it was the exact filename.
I think the regex is more for the native-image-maven-plugin side issue and not for the spring-native.

**Comment by furkansavsatli** [comment]
There was a typo error while preparing the github project in another computer, sorry. I tried the second part you said and it worked. Thank you. however this kind of usage is a bit diffucult. It would be nice if we didn't need IncludeResources.

**Comment by ttddyy** [comment]
The spring-aot plugin automatically adds files under `src/main/resources` directory to the `resource-config.json`.
So, if the resource file is in the main module(`SampleCore`), it is automatically added and discoverable at run time.
However, resource files in the dependent libraries(e.g. `SampleLibrary` jar) would not *automatically* exposed.
If it automatically exposes all resources in the dependent libraries, I guess it would increase the size of the final image unnecessary.

**Comment by sdeleuze** [comment]
@ttddyy Thanks for your help on this.
