### ISSUE TITLE
Spring Native - 0.10.2 with Spring HATEOAS throw NullPointerException

### ISSUE THREAD

**Issue by marzelwidmer** [spring-projects-experimental/spring-native#973]
Sample Repository

https://github.com/marzelwidmer/kboot-native

```
mvn spring-boot:build-image
```
			
```
[INFO] --- spring-aot-maven-plugin:0.10.2:test-generate (test-generate) @ kboot-native ---
[INFO] Spring Native operating mode: native
[ERROR] java.lang.NullPointerException
[ERROR] [org.springframework.hateoas.config.HateoasHints.lastInvocationAwareProxyDescriptor(HateoasHints.java:356),
```

**Comment by sdeleuze** [comment]
@christophstrobl Could you please have a look when you will be back?

**Comment by christophstrobl** [comment]
The project deliberately excludes `spring-boot-starter-web` in the ` spring-boot-starter-hateoas` dependency. Therefore required `@Mapping` annotations are not present, leading to a failure in method return type evaluation, that then causes the NPE.

**Comment by marzelwidmer** [comment]
@christophstrobl and @sdeleuze this is a reactive (coroutine) project
