### ISSUE TITLE
Samples Project Cloud-Function-Aws Created Zip Causes an Error in Custom Runtime on Amazon Linux 2

### ISSUE THREAD

**Issue by patrik-paradis-wcar** [spring-projects-experimental/spring-native#983]
Hello.

I tried to run the, cloud-function-aws-0.0.1-SNAPSHOT-java-zip.zip, that you get from following the README.md file in: 
https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws

however after testing the lambda with this zip file in AWS Console I get the following error:

*****************************************
Execution result: failed Details:
{
  "errorMessage": "RequestId: 449e3583-f8f5-4489-b727-5f2f8c70e806 Error: Runtime exited with error: exit status 127",
  "errorType": "Runtime.ExitError"
}

LOG OUTPUT:
START RequestId: 449e3583-f8f5-4489-b727-5f2f8c70e806 Version: $LATEST
/var/task/bootstrap: line 5: java: command not found
/var/task/bootstrap: line 5: java: command not found
END RequestId: 449e3583-f8f5-4489-b727-5f2f8c70e806
REPORT RequestId: 449e3583-f8f5-4489-b727-5f2f8c70e806	Duration: 10.92 ms	Billed Duration: 11 ms	Memory Size: 512 MB	Max Memory Used: 8 MB	
RequestId: 449e3583-f8f5-4489-b727-5f2f8c70e806 Error: Runtime exited with error: exit status 127
Runtime.ExitError
********************************************

Have I missed something here or does the sample need some kind of update?

Many Thanks!

**Comment by sdeleuze** [comment]
@dsyer Could you please provide a feedback on this one?

**Comment by dsyer** [comment]
I think you just picked the wrong zip file. You need to build with the "native-image" profile and use the zip file from the target dir (`cloud-function-aws-0.0.1-SNAPSHOT-native-zip.zip`). There is a misprint in the README (wrong profile name), so that might be the problem. We can fix that.

**Comment by patrik-paradis-wcar** [comment]
Thank you for the fix in the POM. It appears that the "java command not found error" no longer occurs, however when I used the new ZIP file I instead got the following error in the AWS Console:  

Execution result: failed Details:
{
  "errorMessage": "RequestId: d352be6c-d954-471a-8833-b9144c99d667 Error: Runtime exited with error: exit status 126",
  "errorType": "Runtime.ExitError"
}

Log output:
START RequestId: d352be6c-d954-471a-8833-b9144c99d667 Version: $LATEST
/var/task/bootstrap: ./cloud-function-aws: /home/linuxbrew/.linuxbrew/lib/ld.so: bad ELF interpreter: No such file or directory
/var/task/bootstrap: ./cloud-function-aws: /home/linuxbrew/.linuxbrew/lib/ld.so: bad ELF interpreter: No such file or directory
END RequestId: d352be6c-d954-471a-8833-b9144c99d667
REPORT RequestId: d352be6c-d954-471a-8833-b9144c99d667	Duration: 2.88 ms	Billed Duration: 3 ms	Memory Size: 512 MB	Max Memory Used: 7 MB	
RequestId: d352be6c-d954-471a-8833-b9144c99d667 Error: Runtime exited with error: exit status 126
Runtime.ExitError

Might it be that the executable binary in the ZIP file is not compatible with Amazon Linux 2?

**Comment by dsyer** [comment]
It would be compatible if you built it on Linux, or in a Linux container. We publish suitable containers (see docs for more details) if you need one.
