### ISSUE TITLE
Compatibility with spring-data - Example.class is instantiated reflectively but was never registered

### ISSUE THREAD

**Issue by israeljesus2zup** [spring-projects-experimental/spring-native#984]
I'm trying to migrate a microsservice from spring 'default' to spring native, but some things are going wrong. When my application is starting, I get this error:

```
2021-08-19 20:19:59.513 ERROR [CUSTOMER-APP,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: 

Error creating bean with name 'customerService' defined in class path resource [br/com/project/customer/service/v1/CustomerService.class]: 
Unsatisfied dependency expressed through constructor customer 0; nested exception is org.springframework.beans.factory.BeanCreationException: 

Error creating bean with name 'customerRepository' defined in br.com.project.customer.repository.CustomerRepository 
defined in @EnableMongoRepositories declared on MongoRepositoriesRegistrar.EnableMongoRepositoriesConfiguration: 
Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: 
Could not create query for public abstract 
java.util.Optional br.com.project.customer.repository.CustomerRepository.findByKey(java.lang.String)! 

Reason: Class org.springframework.data.domain.Example[] is instantiated reflectively but was never registered. 

Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection; 
nested exception is java.lang.IllegalArgumentException: Class org.springframework.data.domain.Example[] 
is instantiated reflectively but was never registered. 
Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
```
Reading the exception, I understood that I need to register the Example class, so I put this code on my Application
```
@AotProxyHints(
    value = [
        AotProxyHint(
            targetClass = ConfigServicePropertySourceLocator::class,
            interfaces = [Retryable::class],
            proxyFeatures = IS_STATIC
        ),
        AotProxyHint(
            targetClass = Application::class,
            interfaces = [ScopedObject::class, Serializable::class, AopInfrastructureBean::class]
        )
    ]
)
@NativeHints(
    value = [
        NativeHint(
            types = [
                TypeHint(
                    types = [Example::class],
                    access = ALL
                )],
        )
    ]
)
@InitializationHint(types = [Example::class], initTime = BUILD)
@SpringBootApplication
class Application {

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            System.setProperty("spring.cloud.bootstrap.enabled", "true")
            SpringApplication.run(Application::class.java, *args)
        }
    }
}
```

After build, the generated reflect-config.json has the expected configuration, but it had no effect, the error continues
...
  {
    "name": "org.springframework.data.domain.Example",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  }
...

This is the definition of the Example class: https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Example.html

Spring Version: "2.5.2"
experimental.aot: "0.10.2"
buildtools.native: "0.9.1"
spring-data-commons: 2.5.3

Someone can help me with this?

**Comment by sdeleuze** [comment]
Hi, please check the samples and reference documentation, `@NativeHints` and `@AotProxyHints` are designed for repeatable annotation support, you should use `@NativeHint` and `@AotProxyHint` instead, and in your case since there is no trigger, use directly a top level annotation.

Another point is that you need reflection hint on `org.springframework.data.domain.Example[]` not `org.springframework.data.domain.Example`. But that's probably because you have not updated Kotlin version, try to update to Kotlin 1.5+ and you should only need reflection hint on `org.springframework.data.domain.Example` not `org.springframework.data.domain.Example[]`.
