### ISSUE TITLE
Pass the AOT options from the plugin to BootstrapCodeGeneratorRunner

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#989]
This is a high priority regression we should fix, since currently AOT options like `removeYamlSupport` have no effect.

I am wondering if we should use a configuration file instead of command line parameters for passing options from plugins to `BootstrapCodeGeneratorRunner`.

**Comment by bclozel** [comment]
Closed with a1629968f32f8
