### ISSUE TITLE
Add support for `@ConstructorBinding` configuration properties

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#997]
Spring Boot creates a dedicated bean definition for this with an instance supplier that's responsible for the binding. We should provide a similar infrastructure.

See ConfigurationPropertiesValueObjectBeanDefinition

**Comment by snicoll** [comment]
A challenge with this is that `BeanValueWriterSupplier` does get the merged bean definition that doesn't have that special type because `ConfigurationPropertiesValueObjectBeanDefinition` extends from `GenericBeanDefinition`, rather than `RootBeanDefinition`.

**Comment by snicoll** [comment]
This is more challenging than I thought due to [this check](https://github.com/spring-projects/spring-boot/blob/dff7af3ea8c01c84325635c368c8a21e9e9f9e3e/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessor.java#L98). This forces us to rewrite the bean definition as is  (including the package protected type). 

I've started a discussion with the Spring Boot team to see if we can rearrange things a bit.

**Comment by snicoll** [comment]
A fix is now available and can be merged once we switch to Spring Boot 2.6

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
> Spring Boot creates a dedicated bean definition for this with an instance supplier that's responsible for the binding. We should provide a similar infrastructure.
> 
> See ConfigurationPropertiesValueObjectBeanDefinition

Hi @snicoll, just out of curiosity, I wanted to see how `ConfigurationPropertiesValueObjectBeanDefinition` will look for 2.6 and see how it was in previous commits, but it seems that the file has been moved or renamed.

Any idea on top of you mind where that file/logic went on the main branch on the spring-boot repo? 

----
I tracked a bit the commit history and here is gone:
https://github.com/spring-projects/spring-boot/blob/ee074d3af34efa8ad4fd45d2f7e201b4fadba4bb/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesValueObjectBeanDefinition.java
and here was present:
https://github.com/spring-projects/spring-boot/blob/ef8f402942d94adafb47cd4f48c79bd305293f4c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesValueObjectBeanDefinition.java


https://github.com/spring-projects/spring-boot/commit/ef8f402942d94adafb47cd4f48c79bd305293f4c
is a parent commit of
https://github.com/spring-projects/spring-boot/commit/ee074d3af34efa8ad4fd45d2f7e201b4fadba4bb

**Comment by snicoll** [comment]
It is gone because it is no longer necessary.

**Comment by snicoll** [comment]
Fixed by 74d09dc7f
