### ISSUE TITLE
Handle @PersistenceContext in reflection metadata

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#998]
Consider the following:

https://github.com/spring-projects-experimental/spring-native/blob/76da6837d0a9db3d009b634c739ffb1700e65f11/samples/hibernate/src/main/java/app/main/SampleApplication.java#L22-L29

On the JVM (with AOT) the field is injected because the jvm sees the `PersistenceContext` annotation. It does not on native because no reflection config exists for it. We could fix this by adding a dedicated class that scans and add the reflection metadata. We don't really have an SPI around this now so it would be worth creating one.

**Comment by sdeleuze** [comment]
This is currently handled by `PersistentContextMarkedComponentProcessor` and migrating this should be part of the wider effort to port `ComponentProcessor` to the new AOT engine, so moving it to `0.11.x`.

**Comment by snicoll** [comment]
I believe this one is now a duplicate of #1297. Please reopen if I have misunderstood.
