### ISSUE TITLE
Add reflection configuration for Actuator endpoints

### ISSUE THREAD

**Issue by bclozel** [spring-projects-experimental/spring-native#999]
After the fix for #992, we're seeing that the `actuator-webmvc` sample fails with the following behavior:

* all 15 endpoints are detected by actuator
* the `CustomNoComponent` endpoint is created as a bean as expected
* fetching `localhost:8080/actuator/customnc` fails with a 404

It seems that reflection information is registered for the `Custom` endpoint, because it is annotated with `@Component`:

```json
  {
    "name": "com.example.demo.Custom",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
```

On the other hand, nothing is registered for the `CustomNoComponent` endpoint - actuator cannot look for a `@ReadOperation`-annotated method and won't register that as an endpoint.

**Comment by snicoll** [comment]
Fixed by 7298292a6c3287
